export const DEFAULT_SELECTED_GAME_SHOWCASE_CONFIG = {
  canvas: {
    vw: 1920,
    vh: 1080,
    pad: 12,
    whitePreviewBg: true,
    svgBgOpacity: 0,
    showDebugLabels: false,
  },
  visibility: {
    tabGroup: true,
    pageFrame: true,
    bodyOverlay: true,
    sideA: true,
    hero: true,
    stats: true,
    sideAImage: true,
    sideB: true,
    divider: true,
    overview: true,
    overviewImage: true,
    howTo: true,
    howToCards: true,
    strip: true,
    tip: true,
    button: true,
  },
  page: {
    width: 1784,
    x: 68,
    y: 64,
    height: 980,
    radius: 14,
    strokeWidth: 1.7,
    shadowBlur: 18,
    shadowY: 15,
    shadowOpacity: 0.7,
  },
  tabGroup: {
    y: 18,
    tabW: 166,
    tabH: 50,
    tabGap: 10,
    bgPadX: 12,
    bgPadY: 8,
    radius: 10,
    tabTopRadius: 7,
    tabBottomRadius: 0,
    fontSize: 17,
    activeLineH: 3,
    shineH: 14,
  },
  body: {
    bottomInset: 24,
    rowGap: 18,
    leftWidth: 500,
    useABRatio: true,
    aRatio: 0.28,
    dividerWidth: 1.4,
    dividerConnectToStrip: true,
    dividerConnectorWidth: 1.4,
    dividerConnectorOpacity: 0.48,
    overlayRadius: 14,
    overlayDither: false,
    overlayDitherOpacity: 0.015,
    overlayDitherScale: 8,
    overlayMidStop: 0.36,
    overlaySoftStop: 0.72,
  },
  sideA: {
    logoXPad: 26,
    logoY: 30,
    logoFont: 62,
    taglineFont: 21,
    taglineGap: 30,
    statsY: 274,
    statsH: 60,
    statsGap: 10,
    statRadius: 8,
    artY: 374,
    artBottomPad: 280,
    artTopFade: 0.12,
    artBottomFade: 0.82,
  },
  overview: {
    xPad: 22,
    textX: 30,
    titleY: 44,
    titleFont: 23,
    titleLetterSpacing: 4,
    bodyY: 86,
    bodyFont: 18,
    lineGap: 29,
    paraGap: 53,
    imageRatio: 0.43,
    imageBottomHowToRatio: 1,
    imageCornerFadeCx: 1,
    imageCornerFadeCy: 0,
    imageCornerFadeInner: 0.18,
    imageCornerFadeSoft1: 0.42,
    imageCornerFadeSoft2: 0.68,
    imageCornerFadeOuter: 0.95,
    imageCornerFadeMidOpacity: 0.62,
    imageCornerFadeSoftOpacity: 0.22,
    imageMaskBlur: 18,
  },
  howTo: {
    yOffset: 26,
    topGap: 18,
    height: 265,
    xPad: 22,
    headerH: 54,
    bodyPadX: 18,
    bodyPadBottom: 16,
    arrowW: 34,
    titleFont: 22,
    titleLetterSpacing: 4,
    boxRadius: 12,
    stepRadius: 10,
    stepCircleMaxR: 34,
    stepIconScale: 0.78,
    stepTitleFont: 15,
    stepBodyFont: 11.5,
    stepsPerPage: 3,
    pagerArrowWidth: 34,
    pagerArrowHeight: 46,
    pagerSideInset: 8,
    pagerPillW: 10,
    pagerActivePillW: 24,
    pagerPillH: 6,
    pagerPillGap: 6,
  },
  strip: {
    yOffset: 0,
    topGap: 18,
    insetX: 24,
    height: 198,
    radius: 14,
    fillOpacity: 0.42,
    shineH: 34,
    carouselPadTop: 18,
    carouselPadBottom: 31,
    carouselSidePad: 14,
    arrowWidth: 46,
    arrowHeight: 46,
    arrowOutsideGap: 8,
    arrowYOffset: -6,
    arrowRadius: 10,
    cardGap: 14,
    forceUniformCardWidth: false,
    uniformCardWidth: 230,
    cardMinWidth: 150,
    cardMaxWidth: 300,
    cardTextPadRight: 20,
    headerTextExtraPad: 18,
    cardRadius: 12,
    headerStripHeight: 38,
    headerIconSize: 21,
    headerIconInsetX: 18,
    headerTitleFont: 15,
    headerTitleInsetX: 48,
    headerLetterSpacing: 2.4,
    bulletTop: 58,
    bulletFont: 11.5,
    bulletGap: 6,
    bulletInsetX: 18,
    bulletDotSize: 2.8,
    bodyLineHeight: 15,
    footerLineOffset: -5,
    footerPillY: 4,
    footerPillW: 14,
    footerActivePillW: 30,
    footerPillH: 8,
    footerPillGap: 7,
  },
  tip: {
    yOffset: 0,
    topGap: 18,
    height: 74,
    sideInset: 360,
    radius: 10,
    iconX: 32,
    textX: 130,
    iconFont: 20,
    textFont: 18,
  },
  button: {
    yOffsetFromBottom: 34,
    edgeOffsetY: 0,
    railHeight: 86,
    railInsetX: 0,
    width: 356,
    height: 62,
    radius: 9,
    fontSize: 23,
    letterSpacing: 3,
    strokeOpacity: 0.68,
    shineH: 16,
    innerBoxW: 42,
    innerBoxInset: 0,
    innerBoxInsetLeft: 0,
    innerBoxInsetTop: 0,
    innerBoxInsetRight: 0,
    innerBoxInsetBottom: 0,
    innerBoxRadius: 4,
    innerBoxStrokeWidth: 1.1,
    innerBoxStrokeOpacity: 0.78,
    innerBoxShineH: 12,
    innerBoxShineOpacity: 0.16,
    arrowSize: 11,
    arrowOffsetX: 0,
    arrowOffsetY: 0,
  },
  glow: {
    page: true,
    pageBlur: 7,
    pageOpacity: 0.55,
    tabs: true,
    tabsBlur: 5,
    tabsOpacity: 0.58,
    panels: true,
    panelsBlur: 5,
    panelsOpacity: 0.35,
    strip: true,
    stripBlur: 6,
    stripOpacity: 0.5,
    button: true,
    buttonBlur: 8,
    buttonOpacity: 0.55,
    color: '#64d8ff',
    activeColor: '#ffe187',
  },
  colors: {
    pageStroke: '#64d8ff',
    tabStroke: '#5fc9ff',
    tabInactiveFill: '#071827',
    tabActiveTop: '#332904',
    tabActiveMid: '#0e314b',
    tabActiveBottom: '#071827',
    tabActiveLine: '#63dfff',
    bodyOverlayTop: '#071d4b',
    bodyOverlayMid: '#08223a',
    bodyOverlayBottom: '#061221',
    cardPanelFill: '#061827',
    panelStroke: '#64d8ff',
    textPrimary: '#e8edff',
    textMuted: '#cbd5ff',
    titlePurple: '#c9b7ff',
    iconPurple: '#9d86ff',
    success: '#49d36d',
    tipGold: '#ffd66b',
    stripStroke: '#64d8ff',
    stripCardStroke: '#64d8ff',
    stripActiveStroke: '#ffe187',
    arrowHover: '#47f29a',
    buttonLeft: '#62bcff',
    buttonMid: '#7569ee',
    buttonRight: '#c927d5',
  },
};

export type SelectedGameShowcaseConfig = typeof DEFAULT_SELECTED_GAME_SHOWCASE_CONFIG;

export const NARROW_SELECTED_GAME_SHOWCASE_CONFIG_OVERRIDES = {
  canvas: { vw: 760, vh: 1320 },
  page: { x: 24, y: 92, width: 712, height: 1040 },
  tabGroup: { y: 28, tabW: 92, tabH: 40, tabGap: 4, fontSize: 11, bgPadX: 8 },
  body: { aRatio: 0.34, rowGap: 12, bottomInset: 18 },
  sideA: { logoFont: 36, taglineFont: 13, statsY: 132, statsH: 46, statsGap: 5, artY: 210, artBottomPad: 420 },
  overview: { titleFont: 15, titleLetterSpacing: 2, bodyFont: 10, lineGap: 16, paraGap: 32, imageRatio: 0.28 },
  howTo: { yOffset: -2, topGap: 12, height: 300, titleFont: 16, stepTitleFont: 11, stepBodyFont: 8, arrowW: 12, stepsPerPage: 2 },
  strip: { topGap: 12, height: 210, insetX: 18, arrowOutsideGap: -4, cardMinWidth: 116, cardMaxWidth: 160, bulletFont: 8, headerTitleFont: 10, headerTitleInsetX: 34, headerLetterSpacing: 1 },
  tip: { sideInset: 54, height: 92, textFont: 12, textX: 96 },
  button: { railHeight: 74, width: 260, height: 52, fontSize: 15, letterSpacing: 1.5 },
};
