export const ErrorMessage = {
  BadRequest: 'Bad Request',
  Unauthorized: 'Unauthorized',
  Forbidden: 'Forbidden',
  NotFound: 'Not Found',
  MethodNotAllowed: 'Method Not Allowed',
  PayloadTooLarge: 'Payload Too Large',
  RateLimitExceeded: 'Rate Limit Exceeded',
  InternalServerError: 'Internal Server Error',
  ServiceUnavailable: 'Service Unavailable',
  AuthenticationRequired: 'Authentication required',
  AuthenticationNotConfigured: 'Authentication not configured',
  TokenOrAuthenticationRequired: 'Token or authentication required to access matches',
  AuthenticationRequiredForMatchOperations: 'Authentication required for match operations',
  AuthenticationRequiredForDisputeOperations: 'Authentication required for dispute operations',
  AuthenticationRequiredForEvidenceUpload: 'Authentication required for evidence upload',
  AuthenticationRequiredToCreateDisputes: 'Authentication required to create disputes',
  AuthenticationRequiredToGenerateSignedUrls: 'Authentication required to generate signed URLs',
  AuthenticationRequiredForDataExport: 'Authentication required for data export',
  AuthenticationRequiredForDataDeletion: 'Authentication required for data deletion',
  AuthenticationRequiredToUploadAssets: 'Authentication required to upload assets',
  AuthenticationRequiredForAssetAccess: 'Authentication required for asset access',
  AdminAccessRequired: 'Admin access required',
  AdminAccessRequiredForScanOperation: 'Admin access required for scan operation',
  AdminAccessRequiredForUploadOperation: 'Admin access required for upload operation',
  AdminAccessRequiredForUpdateOperation: 'Admin access required for update operation',
  AdminAccessRequiredForDeleteOperation: 'Admin access required for delete operation',
  AdminAccessRequiredForUploads: 'Admin access required for uploads',
  AdminAccessRequiredToGenerateSignedUrls: 'Admin access required to generate signed URLs',
  MatchIdRequired: 'Match ID required',
  MatchIdMismatch: 'Match ID mismatch',
  UserIdRequired: 'User ID required',
  DisputeIdRequired: 'Dispute ID required',
  MatchNotFound: 'Match not found',
  DisputeNotFound: 'Dispute not found',
  YouCanOnlyExportYourOwnData: 'You can only export your own data',
  YouCanOnlyDeleteYourOwnData: 'You can only delete your own data',
  UserIdMismatch: 'User ID mismatch',
  CorsOriginMismatch: 'CORS origin mismatch',
  CorsErrorKeyword: 'CORS',
  OriginMismatchKeyword: 'origin mismatch',
  CorsOriginCannotBeWildcardInProduction: 'CORS_ORIGIN cannot be "*" in production. Set a specific origin.',
  OriginNotInWhitelistButAllowingDevMode: 'Origin not in whitelist, but allowing (dev mode)',
  AllowingOriginDevelopmentModeNoWhitelist: 'Allowing origin (development mode - no whitelist)',
  OriginDoesntMatchConfiguredButAllowingDevMode: "Origin doesn't match configured, but allowing (dev mode)",
  CorsConfigurationError: 'CORS configuration error',
  MissingAuthorizationHeaderOrToken: 'Missing Authorization header or token',
  InvalidTestTokenFormat: 'Invalid test token format',
  InvalidTokenMissingUserId: 'Invalid token: missing user ID',
  TokenVerificationFailed: 'Token verification failed',
  AuthenticationCheckFailed: 'Authentication check failed',
  RequireAuthFailed: 'requireAuth failed',
  PathComponentMustBeNonEmptyString: 'Path component must be a non-empty string',
  PathComponentBecameEmptyAfterSanitization: 'Path component became empty after sanitization',
  SignatureRequired: 'Signature required for match upload in production',
  SignedUrlSecretNotConfigured: 'Signed URL secret not configured',
  SignedUrlExpired: 'Signed URL expired',
  AiServiceNotAvailable: 'AI service not available',
  TestEndpointsDevOnly: 'Test endpoints are only available in development environment',
  ConfirmationRequired: 'Confirmation required. Set confirm=true in request body or query param.',
  FirebaseNotConfigured: 'Firebase not configured',
  MissingAuthorizationHeader: 'Missing Authorization header',
  UserDocumentNotFound: 'User document not found',
  FirestoreErrorPrefix: 'Firestore error:',
  FailedToGetAdminStatusFromKvCache: 'Failed to get admin status from KV cache',
  FailedToCacheAdminStatusInKv: 'Failed to cache admin status in KV',
  FailedToCheckAdminStatus: 'Failed to check admin status',
  TooManyAIRequests: 'Too many AI requests. Please try again later.',
  AIEventRequestExceedsMaxSize: 'AI event request exceeds maximum size of 1MB',
  MissingRequiredFields: 'Missing required fields: matchId, playerId, eventType',
  AIServiceDomainNotAllowedPrefix: 'AI service domain not allowed:',
  AIServiceErrorPrefix: 'AI service error:',
  FailedToCallAIService: 'Failed to call AI service',
  AIServiceURLValidationFailed: 'AI Service URL validation failed',
  RateLimitKvCheckFailed: 'Rate limit KV check failed',
  FailedToSanitizePathComponentsForAIDecisionStorage: 'Failed to sanitize path components for AI decision storage',
  NoAIServiceConfiguredUsingDefaultAction: 'No AI service configured - using default action',
  RequestBodyExceedsMaximumSizePrefix: 'Request body exceeds maximum size of',
  UnknownError: 'Unknown error',
  FailedToEmitMetrics: 'Failed to emit metrics',
  FailedToSendAlerts: 'Failed to send alerts',
  UnhandledError: 'Unhandled error',

  OriginCannotBeNull: 'Origin cannot be null or undefined',
  OriginMustBeString: 'Origin must be a string, got',
  OriginMustStartWithHttp: 'Origin must start with http:// or https://, got:',
  InvalidOriginFormat: 'Invalid origin format:',
  FailedToExtractOrigin: 'Failed to extract origin from request URL:',
  FailedToConstructDOUrl: 'Failed to construct DO URL from path:',
  ConstructedDOUrlInvalid: 'Constructed DO URL is invalid:',
  BuildApiUrlRequiresOriginOrBaseUrl: 'buildApiUrl requires either origin or baseUrl option',
  BuildLogsApiUrlRequiresOriginOrBaseUrl: 'buildLogsApiUrl requires either origin or baseUrl option',
  PathCannotBeNull: 'Path cannot be null or undefined',
  PathMustBeString: 'Path must be a string, got',
  BuildFullUrlRequiresOriginOrBaseUrl: 'buildFullUrl requires either origin or baseUrl option',
  BuildApiUrlWithQueryParamsRequiresOrigin: 'buildApiUrlWithQueryParams requires either origin or baseUrl option',
  UserIdMustBeNonEmptyString: 'userId must be a non-empty string',
  ActionMustBeNonEmptyString: 'action must be a non-empty string',
  BuildCreditsApiUrlRequiresOrigin: 'buildCreditsApiUrl requires either origin or baseUrl option',
  BuildApiUrlWithPathParamsRequiresOrigin: 'buildApiUrlWithPathParams requires either origin or baseUrl option',
  BuildApiUrlWithPathAndQueryRequiresOrigin: 'buildApiUrlWithPathAndQuery requires either origin or baseUrl option',

  IdempotencyKeyMustBeNonEmptyString: 'Idempotency key must be a non-empty string',
  IdempotencyKeyCannotBeEmptyOrWhitespace: 'Idempotency key cannot be empty or whitespace only',
  IdempotencyKeyMinLength: 'Idempotency key must be at least',
  IdempotencyKeyMaxLength: 'Idempotency key must not exceed',
  IdempotencyKeyAllowedCharacters: 'Idempotency key must contain only alphanumeric characters, hyphens, and underscores',
  IdempotencyKeyCustomMinLength: 'Custom idempotency key must be at least',
  IdempotencyKeyNoLeadingTrailingWhitespace: 'Idempotency key cannot have leading or trailing whitespace',
  InvalidIdempotencyKeyFormat: 'Invalid idempotency key format',

  TransactionIdCannotBeNull: 'Transaction ID cannot be null, undefined, or empty string',
  TransactionIdCannotBeEmptyAfterSanitization: 'Transaction ID cannot be empty or whitespace only after sanitization',

  IdempotencyKeyCannotBeNull: 'IdempotencyKey cannot be null, undefined, or empty string',
  IdempotencyKeyCannotBeEmpty: 'IdempotencyKey cannot be empty or whitespace only',
  IdempotencyKeyCannotHaveWhitespace: 'IdempotencyKey cannot have leading or trailing whitespace',
  IdempotencyKeyMustBeAtLeast: 'IdempotencyKey must be at least',
  IdempotencyKeyMustNotExceed: 'IdempotencyKey must not exceed',
  CharacterUnit: { Singular: ' character', Plural: ' characters' },
  IdempotencyKeyMustContainOnly: 'IdempotencyKey must contain only alphanumeric characters, hyphens, and underscores',
  CustomIdempotencyKeyMinLength: 'Custom idempotency key must be at least',

  MatchIdCannotBeNull: 'MatchId cannot be null, undefined, or empty string',
  MatchIdCannotBeEmpty: 'MatchId cannot be empty or whitespace only',
  MatchIdCannotHaveWhitespace: 'MatchId cannot have leading or trailing whitespace',
  MatchIdMustBeExactLength: 'MatchId must be exactly',
  MatchIdCharactersUuidV4Format: ' characters (UUID v4 format)',
  MatchIdMustBeValidUuidV4: 'MatchId must be a valid UUID v4 (format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx)',
  InvalidMatchIdFormat: 'Invalid MatchId format',

  PathParamMustBeNonEmptyString: 'must be a non-empty string',
  PathParamContainsInvalidChars: 'contains invalid characters',
  PathParamContainsPathTraversal: 'contains path traversal characters',
  PathParamContainsControlChars: 'contains control characters',
  PathParamContainsDoubleEncoding: 'contains double-encoded characters',
  PathParamContainsUnicodeNormalization: 'contains unicode normalization attack',
  PathParamContainsWhitespace: 'contains leading or trailing whitespace',
  InvalidMatchIdFormatPath: 'Invalid matchId format',
  ParamRequiredSuffix: ' is required',
  InvalidParamPrefix: 'Invalid ',

  AssetsNotConfigured: 'Assets not configured',
  LegacyResourcesDisabled: 'Legacy /api/v1/resources is disabled',
  ManifestNotFoundSeedFirst: 'Asset index not found. Seed R2 first (editor responsibility)',
  MissingGuidHashOrChecksum: 'Missing guid, hash, or checksum',
  AssetNotFound: 'Asset not found',
  AssetPresignNotConfigured:
    'Asset download presign is not configured (CLOUDFLARE_ACCOUNT_ID and R2 S3 API credentials)',
  AssetDirectFetchDisabled:
    'Direct asset bytes on the worker are disabled; use GET /api/v1/assets/download-url for a URL',
  ForbiddenAdminRequired: 'Forbidden: Admin required',
} as const;

export type ErrorMessage = typeof ErrorMessage[keyof typeof ErrorMessage];
