import { ApiEndpoint } from './cloudflare';

const DisputeIdExample = 'D-123-456';
const MatchIdExample = '00000000-0000-4000-8000-000000000000';
const UserIdExample = 'user-123';
const FriendIdExample = 'friend-123';
const ConversationIdExample = 'conversation-123';
const TournamentIdExample = 'tournament-123';
const ListingIdExample = 'listing-1';
const PromoCodeExample = 'schemathesis-promo';
const RoomIdExample = MatchIdExample;
const ReplayPathExample = ApiEndpoint.Replay.ByMatchId(MatchIdExample);
const TransparencyReplayPathExample = ApiEndpoint.Transparency.Replay(MatchIdExample);
const MatchRecordUrlExample = `https://ocentra.com/matches/${MatchIdExample}`;
const AnonymizedMatchUrlExample = `/assets/matches/anonymized/${MatchIdExample}.json`;

export const OpenApiDefaultValue = {
  CurrentSeasonId: 'current',
  ConfirmTrue: 'true',
} as const;

export const OpenApiExampleValue = {
  SemanticVersion: '1.0.0',
  UuidZero: '00000000-0000-4000-8000-000000000000',
  UuidOne: '00000000-0000-4000-8000-000000000001',
  AiProviderId: 'localai',
  AiApiKey: 'schemathesis-localai',
  IdempotencyKeyEarn: 'earn-schemathesis-001',
  AuthorizationBearerAdmin: 'Bearer test-token:schemathesis:admin',
  PlayerId: 'player-123',
  UserId: UserIdExample,
  FriendId: FriendIdExample,
  ConversationId: ConversationIdExample,
  ListingId: ListingIdExample,
  TournamentId: TournamentIdExample,
  PromoCode: PromoCodeExample,
  AssetHash: 'schemathesis-asset',
  HashHex64: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
  WalletAddress: '0x123...',
  MatchWalletAddress: '675S9ZqD3QndK4Yh7o2zT6qT6qT6qT6qT6qT6qT6qT6q',
  Pda: 'pda-123',
  Signature: 'sig-1',
  InitialHash: 'initial-hash',
  FinalHash: 'final-hash',
  TransitionFromPending: { from: 'pending', to: 'complete' },
  PlayerMove: { playerId: 'user-123', move: 'check' },
  VrfSource: 'vrf',
  Commitment: { commitment: 'commit-1' },
  AiPlayer: { playerId: 'ai-1', model: 'gpt-5.4' },
  ProgressionUpdate: {
    amount: 50,
    reason: 'Match win',
    idempotencyKey: 'earn-schemathesis-001',
  },
  FraudCheckRequest: {
    amount: 100,
    paymentMethod: 'pm_test_123',
    currency: 'USD',
  },
  TournamentStartRequest: {},
  TournamentRegisterRequest: {
    userId: UserIdExample,
    displayName: 'Tournament Player',
    elo: 1200,
  },
  TournamentResultRequest: {
    matchId: '00000000-0000-4000-8000-000000000000',
    winnerId: 'user-123',
  },
  MarketplaceBuyRequest: {
    listingId: 'listing-1',
  },
  MarketplaceSellRequest: {
    itemId: 'item-123',
    itemType: 'card',
    price: 10,
    currency: 'GP',
  },
  CreditsRedeemRequest: {
    code: 'schemathesis-promo',
  },
  RewardDailyClaimRequest: {
    idempotencyKey: 'earn-schemathesis-001',
    userId: 'user-123',
  },
  DisputeSummary: { disputeId: DisputeIdExample, status: 'open' },
  DisputeId: DisputeIdExample,
  IsoDateTime: '2026-04-08T00:00:00.000Z',
  SignedUrl: 'https://r2.ocentra.com/matches/0000_signed',
  PendingStatus: 'pending',
  CheatingDetected: 'Cheating detected',
  SpeedHackDescription: 'Observed speed hacking in round 3',
  DisputeUpdateDescription: 'More details added',
  EvidenceReason: 'Evidence for cheating',
  EvidenceDescription: 'Round 3 replay data',
  EvidencePackageHash: 'abc123hash',
  MatchPlayerDisplayName: 'Player One',
  MatchEventType: 'game_start',
  MatchMove: 'e4',
  MatchBoardFen: 'startpos',
  MatchId: MatchIdExample,
  MatchRecordUrl: MatchRecordUrlExample,
  AnonymizedMatchUrl: AnonymizedMatchUrlExample,
  ReplayPath: ReplayPathExample,
  TransparencyReplayPath: TransparencyReplayPathExample,
  MatchTransparencyRecord: {
    matchId: MatchIdExample,
    solanaMatchPda: 'pda-123',
    transactionSignatures: ['sig-1'],
    initialStateHash: 'initial-hash',
    finalStateHash: 'final-hash',
    stateTransitions: [{ from: 'pending', to: 'complete' }],
    moves: [{ playerId: UserIdExample, move: 'check' }],
    randomnessSource: 'vrf',
    randomnessCommitments: [{ commitment: 'commit-1' }],
    aiPlayers: [{ playerId: 'ai-1', model: 'gpt-5.4' }],
    disputes: [{ disputeId: DisputeIdExample, status: 'open' }],
    replayAvailable: true,
    replayLocation: ReplayPathExample,
  },
  MatchVerificationResult: {
    matchId: MatchIdExample,
    verifiedAt: 1712520000000,
    checks: {
      hashChain: true,
      moves: true,
      randomness: true,
      onChain: true,
      replay: true,
    },
    overall: true,
    details: {
      failedMoves: [],
    },
  },
  Replay: {
    matchId: MatchIdExample,
    version: '1.0',
    createdAt: 1712520000000,
    initialState: { stateHash: 'initial-hash', turnCount: 0 },
    timeline: [
      {
        type: 'STATE',
        timestamp: 1712520000000,
        data: { stateHash: 'initial-hash' },
        hash: 'initial-hash',
      },
      {
        type: 'MOVE',
        timestamp: 1712520001000,
        data: { move: 'e4' },
        hash: 'final-hash',
        playerId: UserIdExample,
      },
    ],
    finalState: { stateHash: 'final-hash', turnCount: 1 },
    verification: {
      solanaMatchPda: 'pda-123',
      stateHashes: ['initial-hash', 'final-hash'],
      merkleRoot: 'merkle-root',
    },
  },
  ReplayVerification: {
    matchId: MatchIdExample,
    verified: true,
  },
  MatchCache: {
    matchId: MatchIdExample,
    solanaMatchPda: 'pda-123',
    lastSyncedSlot: 1,
    lastSyncedAt: 1712520000000,
    syncStatus: 'synced',
    gameType: 0,
    status: 'active',
    turnCount: 0,
    stateHash: 'abc',
    merkleRoot: 'merkle-root',
    gameState: { stateHash: 'abc' },
    initialState: { stateHash: 'abc' },
    initialStateHash: 'abc',
    finalStateHash: 'def',
    moveHistory: [
      {
        moveId: 'move-1',
        playerId: UserIdExample,
        timestamp: 1712520000000,
        data: { move: 'e4' },
      },
    ],
    createdAt: 1712520000000,
    updatedAt: 1712520001000,
    disputes: [{ disputeId: DisputeIdExample, status: 'open' }],
    transactionSignatures: ['sig-1'],
    randomnessSource: 'vrf',
    randomnessCommitments: ['commit-1'],
  },
  ReconciliationReport: {
    matchId: MatchIdExample,
    timestamp: 1712520000000,
    discrepancies: [
      {
        field: 'stateHash',
        solanaValue: 'abc',
        cloudflareValue: 'def',
      },
    ],
    resolution: 'no_conflict',
  },
  SyncFromSolanaRequest: {
    matchId: MatchIdExample,
    solanaMatchPda: 'pda-123',
    state: { stateHash: 'abc', turnCount: 0, gameType: 0, status: 'active' },
    slot: 1,
  },
  SyncReconcileRequest: {
    matchId: MatchIdExample,
    repair: false,
  },
  SyncFromSolanaResponse: {
    matchId: MatchIdExample,
    solanaMatchPda: 'pda-123',
    lastSyncedSlot: 1,
    lastSyncedAt: 1712520000000,
    syncStatus: 'synced',
    gameType: 0,
    status: 'active',
    turnCount: 0,
    stateHash: 'abc',
    createdAt: 1712520000000,
    updatedAt: 1712520001000,
  },
  SyncReconcileResponse: {
    matchId: MatchIdExample,
    timestamp: 1712520000000,
    discrepancies: [],
    resolution: 'no_conflict',
  },
  FraudCheckResponse: {
    risk: 'low',
    score: 12,
  },
  AntiCheatAnalyzeRequest: {
    matchId: MatchIdExample,
    events: [{ type: 'move' }],
    moveTimingMs: 5,
  },
  AntiCheatAnalyzeResponse: {
    risk: 'low',
    score: 10,
    trustScore: 95,
  },
  AntiCheatStatusResponse: {
    status: 'clear',
    trustScore: 95,
  },
  LobbyRoom: {
    roomId: RoomIdExample,
    roomType: 'lobby',
    maxPlayers: 8,
    currentPlayers: 1,
    currentSpectators: 0,
    gameStatus: 'waiting',
    hostId: UserIdExample,
    gameType: 'poker',
    isPrivate: false,
    createdAt: 1712520000000,
  },
  LobbyRoomsResponse: {
    rooms: [
      {
        roomId: RoomIdExample,
        roomType: 'lobby',
        maxPlayers: 8,
        currentPlayers: 1,
        currentSpectators: 0,
        gameStatus: 'waiting',
        hostId: UserIdExample,
        gameType: 'poker',
        isPrivate: false,
        createdAt: 1712520000000,
      },
    ],
  },
  LobbyCreateResponse: {
    roomId: RoomIdExample,
    joined: true,
    spectating: false,
    room: {
      roomId: RoomIdExample,
      roomType: 'lobby',
      maxPlayers: 8,
      currentPlayers: 1,
      currentSpectators: 0,
      gameStatus: 'waiting',
      hostId: UserIdExample,
      gameType: 'poker',
      isPrivate: false,
      createdAt: 1712520000000,
    },
  },
  LobbyJoinResponse: {
    joined: true,
    roomId: RoomIdExample,
    spectating: false,
    room: {
      roomId: RoomIdExample,
      roomType: 'lobby',
      maxPlayers: 8,
      currentPlayers: 2,
      currentSpectators: 0,
      gameStatus: 'waiting',
      hostId: UserIdExample,
      gameType: 'poker',
      isPrivate: false,
      createdAt: 1712520000000,
    },
  },
  LobbySpectateResponse: {
    joined: true,
    roomId: RoomIdExample,
    spectating: true,
    room: {
      roomId: RoomIdExample,
      roomType: 'lobby',
      maxPlayers: 8,
      currentPlayers: 1,
      currentSpectators: 1,
      gameStatus: 'waiting',
      hostId: UserIdExample,
      gameType: 'poker',
      isPrivate: false,
      createdAt: 1712520000000,
    },
  },
  LobbyLeaveResponse: {
    left: true,
  },
  CreditsRedeemResponse: {
    success: true,
    already_redeemed: false,
    ac_added: 0,
    gp_added: 50,
    new_ac_balance: 0,
    new_gp_balance: 50,
  },
  DisputeCreateRequest: {
    match_id: MatchIdExample,
    reason: 'cheating',
    description: 'Observed cheating in round 3',
    reported_player_id: UserIdExample,
    dispute_id: DisputeIdExample,
  },
  DisputeUpdateRequest: {
    match_id: MatchIdExample,
    reason: 'bug',
    description: 'Updated description with additional context',
  },
  DisputeCreateResponse: {
    success: true,
    disputeId: DisputeIdExample,
    dispute: {
      dispute_id: DisputeIdExample,
      match_id: MatchIdExample,
      status: 'open',
      reason: 'cheating',
      description: 'Observed cheating in round 3',
      created_at: '2026-04-08T00:00:00.000Z',
      updated_at: '2026-04-08T00:00:00.000Z',
      evidence: [],
    },
  },
  DisputeUpdateResponse: {
    success: true,
    disputeId: DisputeIdExample,
  },
  DisputeEvidenceRequest: {
    match_id: MatchIdExample,
    reason: 'Evidence for cheating',
    description: 'Round 3 replay data',
    evidence: 'evidence.txt',
  },
  DisputeEvidenceResponse: {
    success: true,
    dispute_id: DisputeIdExample,
    evidence_package_hash: 'abc123hash',
    evidence_files: 1,
    evidence: [
      {
        filename: 'evidence.txt',
        type: 'text/plain',
        size_bytes: 15,
        hash: 'abc123hash',
        url: 'r2://disputes/evidence.txt',
        uploaded_at: '2026-04-08T00:00:00.000Z',
      },
    ],
    uploaded_at: '2026-04-08T00:00:00.000Z',
  },
  TournamentPrizesDistributedResponse: {
    distributed: 1,
    total: 1,
  },
  LobbyCreateRequest: {
    roomId: RoomIdExample,
    hostId: UserIdExample,
    hostDisplayName: 'Host Player',
    roomType: 'lobby',
    maxPlayers: 8,
    gameType: 'poker',
    isPrivate: false,
  },
  LobbyJoinRequest: {
    userId: FriendIdExample,
    displayName: 'Guest Player',
  },
  LobbySpectateRequest: {
    userId: FriendIdExample,
    displayName: 'Guest Spectator',
  },
  LobbyLeaveRequest: {
    userId: FriendIdExample,
  },
  AntiCheatReportRequest: {
    reporterId: UserIdExample,
    targetId: 'target-user',
    reason: 'suspicious',
    matchId: MatchIdExample,
  },
  FeedFanoutRequest: {
    type: 'activity',
    payload: {
      actorId: UserIdExample,
    },
  },
  DiscoverySearchQuery: 'poker',
  ReportId: '00000000-0000-4000-8000-000000000001',
} as const;
