export const QueryParam = {
  Guid: 'guid',
  Hash: 'hash',
  Checksum: 'checksum',
  Type: 'type',
  Info: 'info',
  GameId: 'gameId',
  UserId: 'userId',
  GameType: 'gameType',
  RoomId: 'roomId',
  AssetPath: 'assetPath',
  Category: 'category',
  GameModeCategory: 'gameModeCategory',
  CopyFromGame: 'copyFromGame',
  Dir: 'dir',
  IncludeMeta: 'includeMeta',
  AssetType: 'assetType',
  Action: 'action',
  Guids: 'guids',
  Confirm: 'confirm',
  Token: 'token',
  Level: 'level',
  Source: 'source',
  Context: 'context',
  Since: 'since',
  Limit: 'limit',
  Cursor: 'cursor',
  Offset: 'offset',
  Sort: 'sort',
  Status: 'status',
  Scope: 'scope',
  PaymentId: 'paymentId',
  StripeEventId: 'stripeEventId',
  Url: 'url',
  Search: 'q',
  Mode: 'mode',
  Visibility: 'visibility',
  StakeType: 'stakeType',
  AllowAI: 'allowAI',
  AiOnly: 'ai_only',
  RoomCode: 'roomCode',
  AdminDebug: 'adminDebug',
} as const;

export type QueryParam = typeof QueryParam[keyof typeof QueryParam];

export const QueryValue = {
  True: 'true',
  False: 'false',
} as const;

export type QueryValue = typeof QueryValue[keyof typeof QueryValue];
