export const CATEGORY_VALUES = [
  "Abstract strategy",
  "Accumulation",
  "Banking",
  "Climbing",
  "Domino",
  "Fishing",
  "Gambling",
  "Matching",
  "Miscellaneous",
  "Other",
  "Patience",
  "Poker",
  "Race",
  "Rummy",
  "Shedding",
  "Social",
  "Tile",
  "Trick-taking",
  "Unknown",
  "Vying",
  "War",
] as const;

export const CATEGORY = {
  ABSTRACT_STRATEGY: "Abstract strategy",
  ACCUMULATION: "Accumulation",
  BANKING: "Banking",
  CLIMBING: "Climbing",
  DOMINO: "Domino",
  FISHING: "Fishing",
  GAMBLING: "Gambling",
  MATCHING: "Matching",
  MISCELLANEOUS: "Miscellaneous",
  OTHER: "Other",
  PATIENCE: "Patience",
  POKER: "Poker",
  RACE: "Race",
  RUMMY: "Rummy",
  SHEDDING: "Shedding",
  SOCIAL: "Social",
  TILE: "Tile",
  TRICK_TAKING: "Trick-taking",
  UNKNOWN: "Unknown",
  VYING: "Vying",
  WAR: "War",
} as const;

export type Category = (typeof CATEGORY_VALUES)[number];

export const SUB_CATEGORY_VALUES = [
  "2-Player / Card Battle",
  "21 / Blackjack Variant",
  "Ace-Ten / Draw",
  "Ace-Ten / Jass",
  "All Fours / Dom Pedro Family",
  "All Fours / Pitch",
  "Andar Bahar",
  "Arithmetic Capture",
  "Arithmetic Capture / Sweep",
  "Asymmetrical Point-trick",
  "Attack-Defense",
  "Attack-Defense / Transfer",
  "Auction / Preference",
  "Auction Whist",
  "Auction Whist / Belgian Whist",
  "Avoidance",
  "Avoidance / Elimination",
  "Avoidance / Hearts Family",
  "Avoidance / Misere",
  "Baccarat Family",
  "Banking",
  "Beating",
  "Belote Family",
  "Bid Euchre",
  "Bidding",
  "Bidding / Partnership",
  "Bidding / Social",
  "Blind / Social",
  "Block / Blind",
  "Block / Line Game",
  "Bluffing",
  "Board + Cards",
  "Board / Multi-stage",
  "Board-Card Hybrid",
  "Board-Card Hybrid / Sequence",
  "Brag Variant",
  "Bridge Family",
  "Building Capture",
  "Canasta / Hand and Foot",
  "Canasta Family / Partnership",
  "Canasta Variant",
  "Capture / Elimination",
  "Capture / Matching",
  "Capture / Ronda",
  "Capturing",
  "Casino",
  "Casino / Capture",
  "Casino / High-Roller",
  "Casino / High-Stake",
  "Casino Family",
  "Casino Poker",
  "Children's",
  "Chinese Dominoes",
  "Chosen Suit",
  "Classic Point-scoring",
  "Classic Point-scoring (American)",
  "Classic Point-scoring (Caribbean)",
  "Classic Point-scoring (Regional)",
  "Climbing",
  "Climbing / Rank-exchange",
  "Combination / Comparison",
  "Combination Capture",
  "Community Card",
  "Community Card / High-Low Split",
  "Compendium",
  "Connecting / Matador",
  "Connecting / Train",
  "Contract / Meld-Capture",
  "Contract Rummy",
  "Contracts",
  "Crazy Eights",
  "Crazy Eights Variant",
  "Cribbage ancestor",
  "Cross",
  "Cross / Block Game",
  "Cross Layout",
  "Domino / Adding",
  "Draw",
  "Draw / Lowball",
  "Draw Game / European",
  "Draw Game / Gambling",
  "Draw Poker",
  "Draw and Discard",
  "Draw and Discard / Meld",
  "Draw and Replace",
  "Draw-Discard / Meld",
  "Draw-Meld (Ancestor Rummy)",
  "Draw-and-Discard",
  "Draw-and-Discard / Basic Rummy",
  "Eights family",
  "Euchre / Auction",
  "Euchre Family / Individual",
  "Evasion",
  "Evolving-Hand Bidding",
  "Exact Bidding",
  "Exact Bidding / Special Deals",
  "Fives and Threes Family",
  "Follow-Suit / Inflation",
  "Gambling",
  "Gambling / Banking",
  "Gambling / Card Race",
  "Gaps / Solitaire",
  "Hanafuda",
  "Hand Building",
  "Hearts / Penalty Avoidance",
  "Hidden Partnership",
  "High-Low Stud",
  "Hombre / Point-trick",
  "Hombre Family",
  "House Game / Stud Poker",
  "Indian Partnership",
  "Indian Poker / Vying",
  "Individual Bidding / Fixed Trump",
  "Inflation / Follow-Suit Shedding",
  "Irish/British Traditional",
  "Italian",
  "Jass",
  "Jass / Ace-Ten / Marriage",
  "Jass / Belote",
  "Jass / Bidding",
  "Jass / Marriage",
  "Jass / Marriage Family",
  "Jass / Point-trick",
  "Jass Family",
  "Jass Family / Point-Trick",
  "Jass-Tarokk Fusion",
  "Karnöffel-style",
  "Last-Trick",
  "Last-Trick / Betting",
  "Last-trick",
  "Last-trick / Elimination",
  "Last-trick / Knocking",
  "Layout / Grid-Based",
  "Layout / Power Card",
  "Line / Block Game",
  "Line / Draw",
  "Line / Partnership",
  "Line / Scoring",
  "Lose Last Trick",
  "Lowball",
  "Lowball Draw",
  "Lowball Stud",
  "Manipulation",
  "Manipulation / Contract Rummy",
  "Mariage / Call",
  "Marriage",
  "Marriage / Ace-Ten",
  "Marriage Group",
  "Matching",
  "Matching / Eights Family",
  "Matching / Melding",
  "Medieval",
  "Meld and Layoff",
  "Melding",
  "Melding / Pay-Card Gambling",
  "Memory",
  "Memory / Partnership",
  "Memory / Quartets",
  "Mixed",
  "Multi-Layer",
  "Non-Builder",
  "Nordic Casino",
  "One-Deck",
  "Open Information",
  "Open Packer",
  "Pai Gow / Casino Game",
  "Pair Collection",
  "Partition / Banking",
  "Partition / Points-Based",
  "Partitioning",
  "Partnership",
  "Partnership / Bidding",
  "Partnership / Contract Bidding",
  "Partnership / Draw-and-Discard",
  "Partnership / Hidden Trump",
  "Partnership / Personal Trump",
  "Partnership / Secret Alliance",
  "Partnership / Shedding",
  "Partnership Line Game",
  "Partnership Meld / Draw-Discard",
  "Partnership Signal",
  "Partnership with Secret Alliances",
  "Penalty / Pot-building",
  "Pitch / All Fours Family",
  "Plain Tricks / No Trump",
  "Plain-Trick",
  "Plain-trick Whist",
  "Plain-trick with Trump",
  "Point-Trick",
  "Point-Trick / All Fours",
  "Point-Trick / Draw",
  "Point-collection",
  "Point-oriented / Cross",
  "Point-trick",
  "Point-trick / No Trump",
  "Point-trick with Bidding",
  "Poker Family",
  "Poker Hand Collection",
  "Poker-based",
  "Preference / Auction",
  "Pure Chance",
  "Puzzle",
  "Quartet / Collecting",
  "Quartet / Go Fish",
  "Quartets",
  "Quota / Card Exchange",
  "Quota / Exchange",
  "Quota Whist",
  "Rams / Bid",
  "Rams / Gambling",
  "Rams / Ramsch",
  "Reaction / Children's",
  "Rummy / Set-Collection",
  "Rummy-like",
  "Schafkopf / Kop Family",
  "Schafkopf Family",
  "Scopa / Capture",
  "Scopa Family",
  "Scopa-variant",
  "Secret Partnership",
  "Secret Partnership (Boston)",
  "Sedma / Point-trick",
  "Seven Card Stud / Split Pot",
  "Seven Card Stud Variant",
  "Shared Card / Omaha Variant",
  "Shedding",
  "Shedding / Deduction",
  "Shedding / Hidden Role",
  "Short Hand / Truco-like",
  "Showdown / Prime",
  "Slap Game",
  "Slap-Jack family",
  "Social / Party",
  "Social Drinking",
  "Social Hierarchy",
  "Solitaire",
  "Solitaire-style",
  "Solo Whist / Contract",
  "Solo vs Partnership",
  "Spanish Deck Games",
  "Speed",
  "Speed Match",
  "Split-Target Totaling",
  "Stud",
  "Stud / Community Card",
  "Stud / Exchange",
  "Stud / Lowball",
  "Stud / Penalty",
  "Stud / Roll-Your-Own",
  "Stud / Wild Cards",
  "Stud Poker",
  "Stud Variant",
  "Stud/Draw Hybrid",
  "Tarokk / Preferansz Family",
  "Tarot",
  "Tarot / Ace-Ten",
  "Tile",
  "Traditional Chinese",
  "Train Building",
  "Tressette / Italian",
  "Tressette Family",
  "Trick Avoidance / Reverse",
  "Trick-Avoidance",
  "Trick-Taking / Children's Game",
  "Trick-avoidance",
  "Trick-taking",
  "Trick-taking / Avoidance",
  "Trick-taking / Chinese Dominoes",
  "Trick-taking / Multi-game",
  "Triple Draw / High-Low Split",
  "Triple Draw / Split Pot",
  "Two-Deck Patience",
  "Two-Phase",
  "Two-Player Draw-and-Discard",
  "Two-phase",
  "Two-player",
  "Vying",
  "War / Accumulation",
  "Watten Family / Alpine Games",
  "Whist",
  "Whist / Ancestor",
  "Whist / Bridge Family",
  "Whist Family",
  "Whist Family (Somali)",
  "Whist Variant",
  "Wild Card Stud",
] as const;

export type SubCategory = (typeof SUB_CATEGORY_VALUES)[number] | null;
