import { SUB_CATEGORY_VALUES } from './categories';

export const SUB_CATEGORY_TO_CATEGORIES: Record<string, readonly string[]> = {
  "2-Player / Card Battle": ["Vying", "Shedding"],
  "21 / Blackjack Variant": ["Banking", "Gambling"],
  "Ace-Ten / Draw": ["Trick-taking"],
  "Ace-Ten / Jass": ["Trick-taking"],
  "All Fours / Dom Pedro Family": ["Trick-taking"],
  "All Fours / Pitch": ["Trick-taking"],
  "Andar Bahar": ["Banking", "Gambling"],
  "Arithmetic Capture": ["Fishing"],
  "Arithmetic Capture / Sweep": ["Fishing"],
  "Asymmetrical Point-trick": ["Trick-taking"],
  "Attack-Defense": ["Trick-taking"],
  "Attack-Defense / Transfer": ["Trick-taking"],
  "Auction / Preference": ["Trick-taking"],
  "Auction Whist": ["Trick-taking"],
  "Auction Whist / Belgian Whist": ["Trick-taking"],
  Avoidance: ["Trick-taking"],
  "Avoidance / Elimination": ["Trick-taking"],
  "Avoidance / Hearts Family": ["Trick-taking"],
  "Avoidance / Misere": ["Trick-taking"],
  "Baccarat Family": ["Banking", "Gambling"],
  Banking: ["Banking", "Gambling"],
  Beating: ["Climbing", "Vying"],
  "Belote Family": ["Trick-taking"],
  "Bid Euchre": ["Trick-taking"],
  Bidding: ["Trick-taking"],
  "Bidding / Partnership": ["Trick-taking"],
  "Bidding / Social": ["Social"],
  "Blind / Social": ["Social"],
  "Block / Blind": ["Domino"],
  "Block / Line Game": ["Domino"],
  Bluffing: ["Poker", "Vying"],
  "Board + Cards": ["Miscellaneous"],
  "Board / Multi-stage": ["Miscellaneous"],
  "Board-Card Hybrid": ["Miscellaneous"],
  "Board-Card Hybrid / Sequence": ["Miscellaneous"],
  "Brag Variant": ["Poker", "Vying"],
  "Bridge Family": ["Trick-taking"],
  "Building Capture": ["Fishing"],
  "Canasta / Hand and Foot": ["Rummy"],
  "Canasta Family / Partnership": ["Rummy"],
  "Canasta Variant": ["Rummy"],
  "Capture / Elimination": ["Fishing", "Shedding"],
  "Capture / Matching": ["Fishing"],
  "Capture / Ronda": ["Fishing"],
  Capturing: ["Fishing"],
  Casino: ["Fishing"],
  "Casino / Capture": ["Fishing"],
  "Casino / High-Roller": ["Fishing"],
  "Casino / High-Stake": ["Fishing"],
  "Casino Family": ["Fishing"],
  "Casino Poker": ["Poker", "Gambling"],
  "Children's": ["Social", "Matching"],
  "Chinese Dominoes": ["Domino"],
  "Chosen Suit": ["Trick-taking"],
  "Classic Point-scoring": ["Trick-taking"],
  "Classic Point-scoring (American)": ["Trick-taking"],
  "Classic Point-scoring (Caribbean)": ["Trick-taking"],
  "Classic Point-scoring (Regional)": ["Trick-taking"],
  Climbing: ["Climbing"],
  "Climbing / Rank-exchange": ["Climbing"],
  "Combination / Comparison": ["Vying"],
  "Combination Capture": ["Fishing"],
  "Community Card": ["Poker"],
  "Community Card / High-Low Split": ["Poker"],
  Compendium: ["Miscellaneous"],
  "Connecting / Matador": ["Domino"],
  "Connecting / Train": ["Domino"],
  "Contract / Meld-Capture": ["Rummy"],
  "Contract Rummy": ["Rummy"],
  Contracts: ["Trick-taking"],
  "Crazy Eights": ["Shedding"],
  "Crazy Eights Variant": ["Shedding"],
  "Cribbage ancestor": ["Accumulation"],
  Cross: ["Domino"],
  "Cross / Block Game": ["Domino"],
  "Cross Layout": ["Patience"],
  "Domino / Adding": ["Domino"],
  Draw: ["Poker"],
  "Draw / Lowball": ["Poker"],
  "Draw Game / European": ["Trick-taking"],
  "Draw Game / Gambling": ["Poker"],
  "Draw Poker": ["Poker"],
  "Draw and Discard": ["Rummy"],
  "Draw and Discard / Meld": ["Rummy"],
  "Draw and Replace": ["Shedding"],
  "Draw-Discard / Meld": ["Rummy"],
  "Draw-Meld (Ancestor Rummy)": ["Rummy"],
  "Draw-and-Discard": ["Rummy"],
  "Draw-and-Discard / Basic Rummy": ["Rummy"],
  "Eights family": ["Shedding"],
  "Euchre / Auction": ["Trick-taking"],
  "Euchre Family / Individual": ["Trick-taking"],
  Evasion: ["Trick-taking"],
  "Evolving-Hand Bidding": ["Trick-taking"],
  "Exact Bidding": ["Trick-taking"],
  "Exact Bidding / Special Deals": ["Trick-taking"],
  "Fives and Threes Family": ["Domino"],
  "Follow-Suit / Inflation": ["Shedding"],
  Gambling: ["Gambling"],
  "Gambling / Banking": ["Banking", "Gambling"],
  "Gambling / Card Race": ["Race", "Gambling"],
  "Gaps / Solitaire": ["Patience"],
  Hanafuda: ["Tile", "Matching"],
  "Hand Building": ["Accumulation"],
  "Hearts / Penalty Avoidance": ["Trick-taking"],
  "Hidden Partnership": ["Trick-taking"],
  "High-Low Stud": ["Poker"],
  "Hombre / Point-trick": ["Trick-taking"],
  "Hombre Family": ["Trick-taking"],
  "House Game / Stud Poker": ["Poker"],
  "Indian Partnership": ["Trick-taking"],
  "Indian Poker / Vying": ["Poker", "Vying"],
  "Individual Bidding / Fixed Trump": ["Trick-taking"],
  "Inflation / Follow-Suit Shedding": ["Shedding"],
  "Irish/British Traditional": ["Miscellaneous"],
  Italian: ["Trick-taking"],
  Jass: ["Trick-taking"],
  "Jass / Ace-Ten / Marriage": ["Trick-taking"],
  "Jass / Belote": ["Trick-taking"],
  "Jass / Bidding": ["Trick-taking"],
  "Jass / Marriage": ["Trick-taking"],
  "Jass / Marriage Family": ["Trick-taking"],
  "Jass / Point-trick": ["Trick-taking"],
  "Jass Family": ["Trick-taking"],
  "Jass Family / Point-Trick": ["Trick-taking"],
  "Jass-Tarokk Fusion": ["Trick-taking"],
  "Karnöffel-style": ["Trick-taking"],
  "Last-Trick": ["Trick-taking"],
  "Last-Trick / Betting": ["Trick-taking"],
  "Last-trick": ["Trick-taking"],
  "Last-trick / Elimination": ["Trick-taking"],
  "Last-trick / Knocking": ["Trick-taking"],
  "Layout / Grid-Based": ["Patience"],
  "Layout / Power Card": ["Patience"],
  "Line / Block Game": ["Domino"],
  "Line / Draw": ["Domino"],
  "Line / Partnership": ["Domino"],
  "Line / Scoring": ["Domino"],
  "Lose Last Trick": ["Trick-taking"],
  Lowball: ["Poker"],
  "Lowball Draw": ["Poker"],
  "Lowball Stud": ["Poker"],
  Manipulation: ["Rummy"],
  "Manipulation / Contract Rummy": ["Rummy"],
  "Mariage / Call": ["Trick-taking"],
  Marriage: ["Trick-taking"],
  "Marriage / Ace-Ten": ["Trick-taking"],
  "Marriage Group": ["Trick-taking"],
  Matching: ["Matching"],
  "Matching / Eights Family": ["Matching", "Shedding"],
  "Matching / Melding": ["Matching", "Rummy"],
  Medieval: ["Miscellaneous"],
  "Meld and Layoff": ["Rummy"],
  Melding: ["Rummy"],
  "Melding / Pay-Card Gambling": ["Rummy", "Gambling"],
  Memory: ["Matching"],
  "Memory / Partnership": ["Matching"],
  "Memory / Quartets": ["Matching"],
  Mixed: ["Miscellaneous"],
  "Multi-Layer": ["Miscellaneous"],
  "Non-Builder": ["Patience"],
  "Nordic Casino": ["Fishing"],
  "One-Deck": ["Patience"],
  "Open Information": ["Abstract strategy"],
  "Open Packer": ["Patience"],
  "Pai Gow / Casino Game": ["Banking", "Gambling"],
  "Pair Collection": ["Matching"],
  "Partition / Banking": ["Banking"],
  "Partition / Points-Based": ["Accumulation"],
  Partitioning: ["Accumulation"],
  Partnership: ["Trick-taking"],
  "Partnership / Bidding": ["Trick-taking"],
  "Partnership / Contract Bidding": ["Trick-taking"],
  "Partnership / Draw-and-Discard": ["Rummy"],
  "Partnership / Hidden Trump": ["Trick-taking"],
  "Partnership / Personal Trump": ["Trick-taking"],
  "Partnership / Secret Alliance": ["Trick-taking"],
  "Partnership / Shedding": ["Shedding"],
  "Partnership Line Game": ["Domino"],
  "Partnership Meld / Draw-Discard": ["Rummy"],
  "Partnership Signal": ["Trick-taking"],
  "Partnership with Secret Alliances": ["Trick-taking"],
  "Penalty / Pot-building": ["Trick-taking"],
  "Pitch / All Fours Family": ["Trick-taking"],
  "Plain Tricks / No Trump": ["Trick-taking"],
  "Plain-Trick": ["Trick-taking"],
  "Plain-trick Whist": ["Trick-taking"],
  "Plain-trick with Trump": ["Trick-taking"],
  "Point-Trick": ["Trick-taking"],
  "Point-Trick / All Fours": ["Trick-taking"],
  "Point-Trick / Draw": ["Trick-taking"],
  "Point-collection": ["Accumulation"],
  "Point-oriented / Cross": ["Accumulation"],
  "Point-trick": ["Trick-taking"],
  "Point-trick / No Trump": ["Trick-taking"],
  "Point-trick with Bidding": ["Trick-taking"],
  "Poker Family": ["Poker"],
  "Poker Hand Collection": ["Poker"],
  "Poker-based": ["Poker"],
  "Preference / Auction": ["Trick-taking"],
  "Pure Chance": ["Miscellaneous"],
  Puzzle: ["Patience"],
  "Quartet / Collecting": ["Matching"],
  "Quartet / Go Fish": ["Matching"],
  Quartets: ["Matching"],
  "Quota / Card Exchange": ["Rummy"],
  "Quota / Exchange": ["Rummy"],
  "Quota Whist": ["Trick-taking"],
  "Rams / Bid": ["Trick-taking"],
  "Rams / Gambling": ["Trick-taking"],
  "Rams / Ramsch": ["Trick-taking"],
  "Reaction / Children's": ["Race", "Social"],
  "Rummy / Set-Collection": ["Rummy"],
  "Rummy-like": ["Rummy"],
  "Schafkopf / Kop Family": ["Trick-taking"],
  "Schafkopf Family": ["Trick-taking"],
  "Scopa / Capture": ["Fishing"],
  "Scopa Family": ["Fishing"],
  "Scopa-variant": ["Fishing"],
  "Secret Partnership": ["Trick-taking"],
  "Secret Partnership (Boston)": ["Trick-taking"],
  "Sedma / Point-trick": ["Trick-taking"],
  "Seven Card Stud / Split Pot": ["Poker"],
  "Seven Card Stud Variant": ["Poker"],
  "Shared Card / Omaha Variant": ["Poker"],
  Shedding: ["Shedding"],
  "Shedding / Deduction": ["Shedding"],
  "Shedding / Hidden Role": ["Shedding"],
  "Short Hand / Truco-like": ["Climbing", "Vying"],
  "Showdown / Prime": ["Poker", "Vying"],
  "Slap Game": ["Race"],
  "Slap-Jack family": ["Race"],
  "Social / Party": ["Social"],
  "Social Drinking": ["Social"],
  "Social Hierarchy": ["Social"],
  Solitaire: ["Patience"],
  "Solitaire-style": ["Patience"],
  "Solo Whist / Contract": ["Trick-taking"],
  "Solo vs Partnership": ["Trick-taking"],
  "Spanish Deck Games": ["Miscellaneous"],
  Speed: ["Race"],
  "Speed Match": ["Race"],
  "Split-Target Totaling": ["Accumulation"],
  Stud: ["Poker"],
  "Stud / Community Card": ["Poker"],
  "Stud / Exchange": ["Poker"],
  "Stud / Lowball": ["Poker"],
  "Stud / Penalty": ["Poker"],
  "Stud / Roll-Your-Own": ["Poker"],
  "Stud / Wild Cards": ["Poker"],
  "Stud Poker": ["Poker"],
  "Stud Variant": ["Poker"],
  "Stud/Draw Hybrid": ["Poker"],
  "Tarokk / Preferansz Family": ["Trick-taking"],
  Tarot: ["Trick-taking"],
  "Tarot / Ace-Ten": ["Trick-taking"],
  Tile: ["Tile"],
  "Traditional Chinese": ["Domino", "Tile"],
  "Train Building": ["Accumulation"],
  "Tressette / Italian": ["Trick-taking"],
  "Tressette Family": ["Trick-taking"],
  "Trick Avoidance / Reverse": ["Trick-taking"],
  "Trick-Avoidance": ["Trick-taking"],
  "Trick-Taking / Children's Game": ["Trick-taking"],
  "Trick-avoidance": ["Trick-taking"],
  "Trick-taking": ["Trick-taking"],
  "Trick-taking / Avoidance": ["Trick-taking"],
  "Trick-taking / Chinese Dominoes": ["Domino", "Trick-taking"],
  "Trick-taking / Multi-game": ["Trick-taking"],
  "Triple Draw / High-Low Split": ["Poker"],
  "Triple Draw / Split Pot": ["Poker"],
  "Two-Deck Patience": ["Patience"],
  "Two-Phase": ["Shedding"],
  "Two-Player Draw-and-Discard": ["Shedding"],
  "Two-phase": ["Shedding"],
  "Two-player": ["Shedding"],
  Vying: ["Vying", "Poker"],
  "War / Accumulation": ["War", "Accumulation"],
  "Watten Family / Alpine Games": ["Trick-taking"],
  Whist: ["Trick-taking"],
  "Whist / Ancestor": ["Trick-taking"],
  "Whist / Bridge Family": ["Trick-taking"],
  "Whist Family": ["Trick-taking"],
  "Whist Family (Somali)": ["Trick-taking"],
  "Whist Variant": ["Trick-taking"],
  "Wild Card Stud": ["Poker"],
};

const BANNED_CATEGORIES = new Set(["Unknown", "Other", "Miscellaneous"]);
const NA_LIKE = /^(NA|N\/A|Unknown|—|–|-|\.|TBD|placeholder|none)$/i;

function isNaLike(s: string | null | undefined): boolean {
  if (s == null || typeof s !== "string") return true;
  return s.trim().length === 0 || NA_LIKE.test(s.trim());
}

export function isValidCategorySubcategoryPair(
  category: string | null,
  subcategory: string | null
): boolean {
  if (category == null || BANNED_CATEGORIES.has(category) || isNaLike(category)) return false;
  if (subcategory == null || isNaLike(subcategory)) return false;
  const sub = subcategory.trim();
  const allowed = SUB_CATEGORY_TO_CATEGORIES[sub];
  if (!allowed) return false;
  return allowed.includes(category);
}

export function getValidSubcategoriesFor(category: string): readonly string[] {
  const out: string[] = [];
  for (const [sub, cats] of Object.entries(SUB_CATEGORY_TO_CATEGORIES)) {
    if (cats.includes(category)) out.push(sub);
  }
  return out.sort();
}

export function getCategorySubcategoryErrorMessage(category: string, subcategory: string): string {
  const allowed = getValidSubcategoriesFor(category);
  const list = allowed.length > 20 ? allowed.slice(0, 20).join(", ") + ", ..." : allowed.join(", ");
  return `overview.subCategory '${subcategory}' is not valid for overview.category '${category}'. Category '${category}' can only have subcategories: ${list}. Fix either category or subCategory to match the taxonomy.`;
}

const ALL_MAPPED = new Set(Object.keys(SUB_CATEGORY_TO_CATEGORIES));
const ALL_SUB = new Set(SUB_CATEGORY_VALUES as readonly string[]);
const UNMAPPED = [...ALL_SUB].filter((s) => !ALL_MAPPED.has(s));
if (UNMAPPED.length > 0) {
  throw new Error(`category-subcategory-map: unmapped subcategories: ${UNMAPPED.join(", ")}`);
}
