export const GameInfoCSSClasses = {
  ContentSection: 'content-section',
  TabButton: 'tab-button',
  TabButtonActive: 'active',
  TabPanel: 'tab-panel',
  TabHeading: 'tab-heading',
  TabSubtitle: 'tab-subtitle',
  TabFooter: 'tabs-footer',
  RuleBlock: 'rule-block',
  StrategyBlock: 'strategy-block',
  Example: 'example',
  ExampleBlock: 'example-block',
  Calculation: 'calculation',
  SetupGrid: 'setup-grid',
  SetupItem: 'setup-item',
  Highlight: 'highlight',
  CardValues: 'card-values',
  Formula: 'formula',
  BudgetInfo: 'budget-info',
  OrderedList: 'ol',
  UnorderedList: 'ul',
  Strong: 'strong',
  Emphasis: 'em',
} as const;

export type GameInfoCSSClasses = typeof GameInfoCSSClasses[keyof typeof GameInfoCSSClasses];
