import type { AutoFixOrphansEvent } from './assets/AutoFixOrphansEvent';
import type { BatchGetResourcesEvent } from './assets/BatchGetResourcesEvent';
import type { BatchUpdateMetadataEvent } from './assets/BatchUpdateMetadataEvent';
import type { CheckMetaFileSyncEvent } from './assets/CheckMetaFileSyncEvent';
import type { ClearDirtyAssetsEvent } from './assets/ClearDirtyAssetsEvent';
import type { CreateAssetTemplateEvent } from './assets/CreateAssetTemplateEvent';
import type { DeleteAssetEvent } from './assets/DeleteAssetEvent';
import type { DetectMimeTypeEvent } from './assets/DetectMimeTypeEvent';
import type { EnsureMetaFileEvent } from './assets/EnsureMetaFileEvent';
import type { FindAssetByTypeAndNameEvent } from './assets/FindAssetByTypeAndNameEvent';
import type { GenerateUniqueGuidEvent } from './assets/GenerateUniqueGuidEvent';
import type { GetAllAssetTypesEvent } from './assets/GetAllAssetTypesEvent';
import type { GetAssetConstructorEvent } from './assets/GetAssetConstructorEvent';
import type { GetAssetRegistryGuidEvent } from './assets/GetAssetRegistryGuidEvent';
import type { GetAssetRegistryResourcesEvent } from './assets/GetAssetRegistryResourcesEvent';
import type { GetAssetsByGameIdEvent } from './assets/GetAssetsByGameIdEvent';
import type { GetAssetTypeInfoEvent } from './assets/GetAssetTypeInfoEvent';
import type { GetAssetTypesByCategoryEvent } from './assets/GetAssetTypesByCategoryEvent';
import type { GetCloudLastModifiedEvent } from './assets/GetCloudLastModifiedEvent';
import type { GetDirtyAssetsEvent } from './assets/GetDirtyAssetsEvent';
import type { GetDiskGameModeEntriesEvent } from './assets/GetDiskGameModeEntriesEvent';
import type { GetGameModeEntriesEvent } from './assets/GetGameModeEntriesEvent';
import type { GetGameTemplateEvent } from './assets/GetGameTemplateEvent';
import type { GetImagesByGameIdEvent } from './assets/GetImagesByGameIdEvent';
import type { GetMetadataEvent } from './assets/GetMetadataEvent';
import type { GetResourceByGuidEvent } from './assets/GetResourceByGuidEvent';
import type { GetResourceByHashEvent } from './assets/GetResourceByHashEvent';
import type { GetResourceEvent } from './assets/GetResourceEvent';
import type { GetSyncMetadataEvent } from './assets/GetSyncMetadataEvent';
import type { GetSyncStatusEvent } from './assets/GetSyncStatusEvent';
import type { GetTreeFolderContentEvent } from './assets/GetTreeFolderContentEvent';
import type { HasAssetTypeEvent } from './assets/HasAssetTypeEvent';
import type { IsTypeOfEvent } from './assets/IsTypeOfEvent';
import type { MarkAssetCleanEvent } from './assets/MarkAssetCleanEvent';
import type { MarkAssetDirtyEvent } from './assets/MarkAssetDirtyEvent';
import type { ParseMetaJson5Event } from './assets/ParseMetaJson5Event';
import type { ProcessMetaFilesEvent } from './assets/ProcessMetaFilesEvent';
import type { ReadMetaFileEvent } from './assets/ReadMetaFileEvent';
import type { RegisterGuidEvent } from './assets/RegisterGuidEvent';
import type { RegisterIResourceEntryEvent } from './assets/RegisterResourceEntryEvent';
import type { ReplaceAllResourcesEvent } from './assets/ReplaceAllResourcesEvent';
import type { ResourceRegisteredEvent } from './assets/ResourceRegisteredEvent';
import type { SaveAssetRegistryEvent } from './assets/SaveAssetRegistryEvent';
import type { ScanAssetsEvent } from './assets/ScanAssetsEvent';
import type { ScanR2StatusEvent } from './assets/ScanR2StatusEvent';
import type { SetCloudLastModifiedEvent } from './assets/SetCloudLastModifiedEvent';
import type { SetLastSyncFromCloudEvent } from './assets/SetLastSyncFromCloudEvent';
import type { SetLastSyncToCloudEvent } from './assets/SetLastSyncToCloudEvent';
import type { SyncAssetEvent } from './assets/SyncAssetEvent';
import type { SyncFromR2Event } from './assets/SyncFromR2Event';
import type { SyncToR2Event } from './assets/SyncToR2Event';
import type { UpdateMetaOnSaveEvent } from './assets/UpdateMetaOnSaveEvent';
import type { UploadAssetEvent } from './assets/UploadAssetEvent';
import type { UploadFilesEvent } from './assets/UploadFilesEvent';
import type { UploadImageEvent } from './assets/UploadImageEvent';
import type { ValidateAllMetaEvent } from './assets/ValidateAllMetaEvent';
import type { ValidateFolderTreesEvent } from './assets/ValidateFolderTreesEvent';
import type { RequestAdditionalUserInfoEvent } from './authentication/RequestAdditionalUserInfoEvent';
import type { RequestUserCredentialsEvent } from './authentication/RequestUserCredentialsEvent';
import type { UpdateUIInteractabilityEvent } from './authentication/UpdateUIInteractabilityEvent';
import type { OpenInEditorEvent } from './dev/OpenInEditorEvent';
import type { AuthenticationErrorUIEvent } from './game/AuthenticationErrorUIEvent';
import type { AuthenticationSignOutEvent } from './game/AuthenticationSignOutEvent';
import type { ClearGameRegistryCacheEvent } from './game/ClearGameRegistryCacheEvent';
import type { DecisionTakenEvent } from './game/DecisionTakenEvent';
import type { DetermineWinnerEvent } from './game/DetermineWinnerEvent';
import type { GetAllGameIdsEvent } from './game/GetAllGameIdsEvent';
import type { GetAssetTypeByGuidEvent } from './game/GetAssetTypeByGuidEvent';
import type { GetGameInfoEvent } from './game/GetGameInfoEvent';
import type { GetGameModeEvent } from './game/GetGameModeEvent';
import type { GetLocalPlayerEvent } from './game/GetLocalPlayerEvent';
import type { GetSelectedGamePageInfosEvent } from './game/GetSelectedGamePageInfosEvent';
import type { HideScreenEvent } from './game/HideScreenEvent';
import type { LayoutAssetUpdatedEvent } from './game/LayoutAssetUpdatedEvent';
import type { NewRoundStartedEvent } from './game/NewRoundStartedEvent';
import type { OfferContinuationEvent } from './game/OfferContinuationEvent';
import type { OfferNewGameEvent } from './game/OfferNewGameEvent';
import type { PlayerActionNewRoundEvent } from './game/PlayerActionNewRoundEvent';
import type { PlayerActionRaiseBetEvent } from './game/PlayerActionRaiseBetEvent';
import type { PlayerActionStartNewGameEvent } from './game/PlayerActionStartNewGameEvent';
import type { ComputerPlayerTurnEvent } from './game/playerDecision/ComputerPlayerTurnEvent';
import type { PlayerDecisionEvent } from './game/playerDecision/PlayerDecisionEvent';
import type { ProcessDecisionEvent } from './game/ProcessDecisionEvent';
import type { PurchaseCoinsEvent } from './game/PurchaseCoinsEvent';
import type { RegisterHumanPlayerEvent } from './game/RegisterHumanPlayerEvent';
import type { RegisterLocalPlayerEvent } from './game/RegisterLocalPlayerEvent';
import type { RegisterPlayerListEvent } from './game/RegisterPlayerListEvent';
import type { RequestActivePlayersEvent } from './game/RequestActivePlayersEvent';
import type { RequestAllPlayersDataEvent } from './game/RequestAllPlayersDataEvent';
import type { RequestComputerPlayersDataEvent } from './game/RequestComputerPlayersDataEvent';
import type { RequestFloorCardsDetailEvent } from './game/RequestFloorCardsDetailEvent';
import type { RequestHumanPlayersDataEvent } from './game/RequestHumanPlayersDataEvent';
import type { RequestLobbyPlayerDataEvent } from './game/RequestLobbyPlayerDataEvent';
import type { RequestPlayerDataFromCloudEvent } from './game/RequestPlayerDataFromCloudEvent';
import type { RequestPlayerHandDetailEvent } from './game/RequestPlayerHandDetailEvent';
import type { RequestRemainingCardsCountEvent } from './game/RequestRemainingCardsCountEvent';
import type { RequestScoreManagerDetailsEvent } from './game/RequestScoreManagerDetailsEvent';
import type { SavePlayerDataToCloudEvent } from './game/SavePlayerDataToCloudEvent';
import type { ScanAndPopulateEvent } from './game/ScanAndPopulateEvent';
import type { ShowAllFloorCardEvent } from './game/ShowAllFloorCardEvent';
import type { StartMainGameEvent } from './game/StartMainGameEvent';
import type { StartTurnManagerEvent } from './game/StartTurnManagerEvent';
import type { TimerStartEvent } from './game/TimerStartEvent';
import type { TimerStopEvent } from './game/TimerStopEvent';
import type { TurnCompletedEvent } from './game/TurnCompletedEvent';
import type { UIMessageEvent } from './game/UIMessageEvent';
import type { UnregisterPlayerEvent } from './game/UnregisterPlayerEvent';
import type { UpdateGameRegistryViewEvent } from './game/UpdateGameRegistryViewEvent';
import type { UpdateGameStateEvent } from './game/UpdateGameStateEvent';
import type { UpdateNetworkPlayerUIEvent } from './game/UpdateNetworkPlayerUIEvent';
import type { UpdatePlayerHandDisplayEvent } from './game/UpdatePlayerHandDisplayEvent';
import type { UpdateTurnStateEvent } from './game/UpdateTurnStateEvent';
import type { UpdateWildCardsEvent } from './game/UpdateWildCardsEvent';
import type { UpdateWildCardsHighlightEvent } from './game/UpdateWildCardsHighlightEvent';
import type { ValidateMaxPlayersEvent } from './game/ValidateMaxPlayersEvent';
import type { ImageBatchLoadedEvent } from './image/ImageBatchLoadedEvent';
import type { ImageBatchLoadRequestEvent } from './image/ImageBatchLoadRequestEvent';
import type { ImageLoadedEvent } from './image/ImageLoadedEvent';
import type { ImageLoadFailedEvent } from './image/ImageLoadFailedEvent';
import type { ImageLoadRequestEvent } from './image/ImageLoadRequestEvent';
import type { ImageUnsubscribeEvent } from './image/ImageUnsubscribeEvent';
import type { ArcadeInfoEvent } from './lobby/ArcadeInfoEvent';
import type { Button3DSimpleClickEvent } from './lobby/Button3DSimpleClickEvent';
import type { CreateLobbyEvent } from './lobby/CreateLobbyEvent';
import type { CreateProfileEvent } from './lobby/CreateProfileEvent';
import type { InfoSubTabStateChangedEvent } from './lobby/InfoSubTabStateChangedEvent';
import type { InputLobbyPasswordEvent } from './lobby/InputLobbyPasswordEvent';
import type { JoinedLobbyEvent } from './lobby/JoinedLobbyEvent';
import type { JoinLobbyEvent } from './lobby/JoinLobbyEvent';
import type { LobbyInfoEvent } from './lobby/LobbyInfoEvent';
import type { LobbyPlayerUpdateEvent } from './lobby/LobbyPlayerUpdateEvent';
import type { PlayerLeftLobbyEvent } from './lobby/PlayerLeftLobbyEvent';
import type { ProfileCreatedEvent } from './lobby/ProfileCreatedEvent';
import type { ShowArcadeSideEvent } from './lobby/ShowArcadeSideEvent';
import type { ShowScreenEvent } from './lobby/ShowScreenEvent';
import type { ShowSubTabEvent } from './lobby/ShowSubTabEvent';
import type { StartLobbyAsHostEvent } from './lobby/StartLobbyAsHostEvent';
import type { UpdateLobbyEvent } from './lobby/UpdateLobbyEvent';
import type { UpdateLobbyListEvent } from './lobby/UpdateLobbyListEvent';
import type { UpdateLobbyPlayerListEvent } from './lobby/UpdateLobbyPlayerListEvent';
import type { UpdatePlayerListEvent } from './lobby/UpdatePlayerListEvent';
import type { ClearLogsEvent } from './logs/ClearLogsEvent';
import type { GetLogStatsEvent } from './logs/GetLogStatsEvent';
import type { QueryLogsEvent } from './logs/QueryLogsEvent';
import type { SaveLogsEvent } from './logs/SaveLogsEvent';
import type { ModelAvailableEvent } from './model/ModelAvailableEvent';
import type { ModelGenerationCompleteEvent } from './model/ModelGenerationCompleteEvent';
import type { ModelGenerationStoppedEvent } from './model/ModelGenerationStoppedEvent';
import type { ModelGenerationUpdateEvent } from './model/ModelGenerationUpdateEvent';
import type { ModelLoadedEvent } from './model/ModelLoadedEvent';
import type { ModelLoadProgressEvent } from './model/ModelLoadProgressEvent';
import type { ModelSyncAvailableEvent } from './model/ModelSyncAvailableEvent';
import type { RequestModelGenerateEvent } from './model/RequestModelGenerateEvent';
import type { RequestModelListEvent } from './model/RequestModelListEvent';
import type { RequestModelLoadEvent } from './model/RequestModelLoadEvent';
import type { RequestModelStopEvent } from './model/RequestModelStopEvent';
import type { RequestProviderSwitchEvent } from './model/RequestProviderSwitchEvent';
import type { PlayerJoinedEvent } from './PlayerJoinedEvent';

declare module '@/events/EventTypes' {
  interface EventTypeMap {
    'Assets/BatchGetResources': BatchGetResourcesEvent;
    'Assets/BatchUpdateMetadata': BatchUpdateMetadataEvent;
    'Assets/CreateAssetTemplate': CreateAssetTemplateEvent;
    'Assets/DeleteAsset': DeleteAssetEvent;
    'Assets/EnsureMetaFile': EnsureMetaFileEvent;
    'Assets/FindAssetByTypeAndName': FindAssetByTypeAndNameEvent;
    'Assets/GenerateUniqueGuid': GenerateUniqueGuidEvent;
    'Assets/GetAllAssetTypes': GetAllAssetTypesEvent;
    'Assets/GetAssetConstructor': GetAssetConstructorEvent;
    'Assets/GetAssetRegistryGuid': GetAssetRegistryGuidEvent;
    'Assets/GetAssetRegistryResources': GetAssetRegistryResourcesEvent;
    'Assets/GetAssetsByGameId': GetAssetsByGameIdEvent;
    'Assets/GetAssetTypeInfo': GetAssetTypeInfoEvent;
    'Assets/GetAssetTypesByCategory': GetAssetTypesByCategoryEvent;
    'Assets/GetCloudLastModified': GetCloudLastModifiedEvent;
    'Assets/GetDiskGameModeEntries': GetDiskGameModeEntriesEvent;
    'Assets/GetGameModeEntries': GetGameModeEntriesEvent;
    'Assets/GetGameTemplate': GetGameTemplateEvent;
    'Assets/GetImagesByGameId': GetImagesByGameIdEvent;
    'Assets/GetMetadata': GetMetadataEvent;
    'Assets/GetResource': GetResourceEvent;
    'Assets/GetResourceByGuid': GetResourceByGuidEvent;
    'Assets/GetResourceByHash': GetResourceByHashEvent;
    'Assets/GetSyncMetadata': GetSyncMetadataEvent;
    'Assets/GetSyncStatus': GetSyncStatusEvent;
    'Assets/GetTreeFolderContent': GetTreeFolderContentEvent;
    'Assets/HasAssetType': HasAssetTypeEvent;
    'Assets/IsTypeOf': IsTypeOfEvent;
    'Assets/ProcessMetaFiles': ProcessMetaFilesEvent;
    'Assets/ReadMetaFile': ReadMetaFileEvent;
    'Assets/RegisterGuid': RegisterGuidEvent;
    'Assets/RegisterIResourceEntry': RegisterIResourceEntryEvent;
    'Assets/ReplaceAllResources': ReplaceAllResourcesEvent;
    'Assets/ResourceRegistered': ResourceRegisteredEvent;
    'Assets/SaveAssetRegistry': SaveAssetRegistryEvent;
    'Assets/ScanAssets': ScanAssetsEvent;
    'Assets/ScanR2Status': ScanR2StatusEvent;
    'Assets/SetCloudLastModified': SetCloudLastModifiedEvent;
    'Assets/SetLastSyncFromCloud': SetLastSyncFromCloudEvent;
    'Assets/SetLastSyncToCloud': SetLastSyncToCloudEvent;
    'Assets/SyncAsset': SyncAssetEvent;
    'Assets/SyncFromR2': SyncFromR2Event;
    'Assets/SyncToR2': SyncToR2Event;
    'Assets/UploadAsset': UploadAssetEvent;
    'Assets/UploadFiles': UploadFilesEvent;
    'Assets/UploadImage': UploadImageEvent;
    'Authentication/RequestAdditionalUserInfo': RequestAdditionalUserInfoEvent;
    'Authentication/RequestUserCredentials': RequestUserCredentialsEvent;
    'Authentication/UpdateUIInteractability': UpdateUIInteractabilityEvent;
    'Dev/OpenInEditor': OpenInEditorEvent;
    'Game/AuthenticationErrorUI': AuthenticationErrorUIEvent;
    'Game/AuthenticationSignOut': AuthenticationSignOutEvent;
    'Game/ClearGameRegistryCache': ClearGameRegistryCacheEvent;
    'Game/DecisionTaken': DecisionTakenEvent;
    'Game/DetermineWinner': DetermineWinnerEvent;
    'Game/GetAllGameIds': GetAllGameIdsEvent;
    'Game/GetAssetTypeByGuid': GetAssetTypeByGuidEvent;
    'Game/GetGameInfo': GetGameInfoEvent;
    'Game/GetGameMode': GetGameModeEvent;
    'Game/GetLocalPlayer': GetLocalPlayerEvent;
    'Game/GetSelectedGamePageInfos': GetSelectedGamePageInfosEvent;
    'Game/HideScreen': HideScreenEvent;
    'Game/LayoutAssetUpdated': LayoutAssetUpdatedEvent;
    'Game/NewRoundStarted': NewRoundStartedEvent;
    'Game/OfferContinuation': OfferContinuationEvent;
    'Game/OfferNewGame': OfferNewGameEvent;
    'Game/PlayerActionNewRound': PlayerActionNewRoundEvent;
    'Game/PlayerActionRaiseBet': PlayerActionRaiseBetEvent;
    'Game/PlayerActionStartNewGame': PlayerActionStartNewGameEvent;
    'Game/PlayerDecision': PlayerDecisionEvent;
    'Game/PlayerDecision/ComputerPlayerTurn': ComputerPlayerTurnEvent;
    'Game/ProcessDecision': ProcessDecisionEvent;
    'Game/PurchaseCoins': PurchaseCoinsEvent;
    'Game/RegisterHumanPlayer': RegisterHumanPlayerEvent;
    'Game/RegisterLocalPlayer': RegisterLocalPlayerEvent;
    'Game/RegisterPlayerList': RegisterPlayerListEvent;
    'Game/RequestActivePlayers': RequestActivePlayersEvent;
    'Game/RequestAllPlayersData': RequestAllPlayersDataEvent;
    'Game/RequestComputerPlayersData': RequestComputerPlayersDataEvent;
    'Game/RequestFloorCardsDetail': RequestFloorCardsDetailEvent;
    'Game/RequestHumanPlayersData': RequestHumanPlayersDataEvent;
    'Game/RequestLobbyPlayerData': RequestLobbyPlayerDataEvent;
    'Game/RequestPlayerDataFromCloud': RequestPlayerDataFromCloudEvent;
    'Game/RequestPlayerHandDetail': RequestPlayerHandDetailEvent;
    'Game/RequestRemainingCardsCount': RequestRemainingCardsCountEvent;
    'Game/RequestScoreManagerDetails': RequestScoreManagerDetailsEvent;
    'Game/SavePlayerDataToCloud': SavePlayerDataToCloudEvent;
    'Game/ScanAndPopulate': ScanAndPopulateEvent;
    'Game/ShowAllFloorCard': ShowAllFloorCardEvent;
    'Game/StartMainGame': StartMainGameEvent;
    'Game/StartTurnManager': StartTurnManagerEvent;
    'Game/TimerStart': TimerStartEvent;
    'Game/TimerStop': TimerStopEvent;
    'Game/TurnCompleted': TurnCompletedEvent;
    'Game/UIMessage': UIMessageEvent;
    'Game/UnregisterPlayer': UnregisterPlayerEvent;
    'Game/UpdateGameRegistryView': UpdateGameRegistryViewEvent;
    'Game/UpdateGameState': UpdateGameStateEvent;
    'Game/UpdateNetworkPlayerUI': UpdateNetworkPlayerUIEvent;
    'Game/UpdatePlayerHandDisplay': UpdatePlayerHandDisplayEvent;
    'Game/UpdateTurnState': UpdateTurnStateEvent;
    'Game/UpdateWildCards': UpdateWildCardsEvent;
    'Game/UpdateWildCardsHighlight': UpdateWildCardsHighlightEvent;
    'Game/ValidateMaxPlayers': ValidateMaxPlayersEvent;
    'Image/BatchLoaded': ImageBatchLoadedEvent;
    'Image/BatchLoadRequest': ImageBatchLoadRequestEvent;
    'Image/Loaded': ImageLoadedEvent;
    'Image/LoadFailed': ImageLoadFailedEvent;
    'Image/LoadRequest': ImageLoadRequestEvent;
    'Image/Unsubscribe': ImageUnsubscribeEvent;
    'Lobby/ArcadeInfo': ArcadeInfoEvent;
    'Lobby/Button3DClick': Button3DSimpleClickEvent;
    'Lobby/CreateLobby': CreateLobbyEvent;
    'Lobby/CreateProfile': CreateProfileEvent;
    'Lobby/Info': LobbyInfoEvent;
    'Lobby/InfoSubStateChanged': InfoSubTabStateChangedEvent;
    'Lobby/InputLobbyPassword': InputLobbyPasswordEvent;
    'Lobby/Joined': JoinedLobbyEvent;
    'Lobby/JoinLobby': JoinLobbyEvent;
    'Lobby/PlayerLeft': PlayerLeftLobbyEvent;
    'Lobby/PlayerUpdate': LobbyPlayerUpdateEvent;
    'Lobby/ProfileCreated': ProfileCreatedEvent;
    'Lobby/ShowArcadeSide': ShowArcadeSideEvent;
    'Lobby/ShowScreen': ShowScreenEvent;
    'Lobby/ShowSubTab': ShowSubTabEvent;
    'Lobby/StartAsHost': StartLobbyAsHostEvent;
    'Lobby/Update': UpdateLobbyEvent;
    'Lobby/UpdateLobbyList': UpdateLobbyListEvent;
    'Lobby/UpdateLobbyPlayerList': UpdateLobbyPlayerListEvent;
    'Lobby/UpdatePlayerList': UpdatePlayerListEvent;
    'Logs/ClearLogs': ClearLogsEvent;
    'Logs/GetLogStats': GetLogStatsEvent;
    'Logs/QueryLogs': QueryLogsEvent;
    'Logs/SaveLogs': SaveLogsEvent;
    'MetaFile/AutoFixOrphans': AutoFixOrphansEvent;
    'MetaFile/CheckMetaFileSync': CheckMetaFileSyncEvent;
    'MetaFile/ClearDirtyAssets': ClearDirtyAssetsEvent;
    'MetaFile/DetectMimeType': DetectMimeTypeEvent;
    'MetaFile/GetDirtyAssets': GetDirtyAssetsEvent;
    'MetaFile/MarkAssetClean': MarkAssetCleanEvent;
    'MetaFile/MarkAssetDirty': MarkAssetDirtyEvent;
    'MetaFile/ParseMetaJson5': ParseMetaJson5Event;
    'MetaFile/UpdateMetaOnSave': UpdateMetaOnSaveEvent;
    'MetaFile/ValidateAllMeta': ValidateAllMetaEvent;
    'MetaFile/ValidateFolderTrees': ValidateFolderTreesEvent;
    'Model/ModelAvailable': ModelAvailableEvent;
    'Model/ModelGenerationComplete': ModelGenerationCompleteEvent;
    'Model/ModelGenerationStopped': ModelGenerationStoppedEvent;
    'Model/ModelGenerationUpdate': ModelGenerationUpdateEvent;
    'Model/ModelLoaded': ModelLoadedEvent;
    'Model/ModelLoadProgress': ModelLoadProgressEvent;
    'Model/ModelSyncAvailable': ModelSyncAvailableEvent;
    'Model/RequestModelGenerate': RequestModelGenerateEvent;
    'Model/RequestModelList': RequestModelListEvent;
    'Model/RequestModelLoad': RequestModelLoadEvent;
    'Model/RequestModelStop': RequestModelStopEvent;
    'Model/RequestProviderSwitch': RequestProviderSwitchEvent;
    'PlayerJoinedEvent': PlayerJoinedEvent;
  }
}

export {};