// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

import { decodeImportPath, type AssetTypeMetadata } from '@ocentra/asset-domain/constants/assets';

const rawAssetTypeMap = {
  "AssetResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/AssetResourceEntry",
    "assetType": "AssetResourceEntry",
    "displayName": "Asset Resource Entry",
    "icon": "📄",
    "category": "Content",
    "commonType": "Assets"
  },
  "FileResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/FileResourceEntry",
    "assetType": "FileResourceEntry",
    "displayName": "File Resource Entry",
    "icon": "📁",
    "category": "Content",
    "commonType": "Assets"
  },
  "FolderResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/FolderResourceEntry",
    "assetType": "FolderResourceEntry",
    "displayName": "Folder Resource Entry",
    "icon": "📂",
    "category": "Content",
    "commonType": "Assets"
  },
  "ImageResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/ImageResourceEntry",
    "assetType": "ImageResourceEntry",
    "displayName": "Image Resource Entry",
    "icon": "🖼️",
    "category": "Content",
    "commonType": "Assets"
  },
  "ResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/ResourceEntry",
    "assetType": "ResourceEntry",
    "displayName": "Resource Entry",
    "icon": "📄",
    "category": "Content",
    "commonType": "Assets"
  },
  "SoundResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/SoundResourceEntry",
    "assetType": "SoundResourceEntry",
    "displayName": "Sound Resource Entry",
    "icon": "🔊",
    "category": "Content",
    "commonType": "Assets"
  },
  "VideoResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/VideoResourceEntry",
    "assetType": "VideoResourceEntry",
    "displayName": "Video Resource Entry",
    "icon": "🎬",
    "category": "Content",
    "commonType": "Assets"
  },
  "AIModelList": {
    "importPath": "@ocentra/game-asset-domain/ai/aiModelList/AIModelList",
    "assetType": "AIModelList",
    "displayName": "AI Model List",
    "icon": "🤖",
    "category": "AI",
    "commonType": "AI"
  },
  "ModelQuantSettings": {
    "importPath": "@ocentra/game-asset-domain/ai/ModelQuantSettings",
    "assetType": "ModelQuantSettings",
    "displayName": "Model Quant Settings",
    "icon": "⚙️",
    "category": "AI",
    "commonType": "AI"
  },
  "AssetRegistry": {
    "importPath": "@ocentra/game-asset-domain/assetRegistry/AssetRegistry",
    "assetType": "AssetRegistry",
    "displayName": "Asset Registry",
    "icon": "📋",
    "category": "Content",
    "commonType": "Assets"
  },
  "BaseAssetMetadata": {
    "importPath": "@ocentra/game-asset-domain/BaseAssetMetadata",
    "assetType": "BaseAssetMetadata",
    "displayName": "Base Asset Metadata",
    "commonType": "Assets"
  },
  "Card": {
    "importPath": "@ocentra/game-asset-domain/card/cardBase/Card",
    "assetType": "Card",
    "displayName": "Card",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Cards"
  },
  "CardSuitEntry": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardSuitEntry",
    "displayName": "Card Suit Entry",
    "commonType": "Assets"
  },
  "CardRankingEntry": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardRankingEntry",
    "displayName": "Card Ranking Entry",
    "commonType": "Assets"
  },
  "CardRankingExplicitEntry": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardRankingExplicitEntry",
    "displayName": "Card Ranking Explicit Entry",
    "commonType": "Assets"
  },
  "CardRanking": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardRanking",
    "displayName": "Card Ranking",
    "icon": "📊",
    "category": "Game",
    "commonType": "Assets"
  },
  "SupportedDeckTriple": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "SupportedDeckTriple",
    "displayName": "Supported Deck Triple",
    "icon": "ðŸƒ",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckCardMember": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "DeckCardMember",
    "displayName": "Deck Card Member",
    "icon": "🂠",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckPieceMember": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "DeckPieceMember",
    "displayName": "Deck Piece Member",
    "icon": "ðŸƒ",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckPresentation": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "DeckPresentation",
    "displayName": "Deck Presentation",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckRuntimePolicy": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "DeckRuntimePolicy",
    "displayName": "Deck Runtime Policy",
    "category": "Game",
    "commonType": "Decks"
  },
  "Deck": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "Deck",
    "displayName": "Deck",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Decks"
  },
  "ComingSoon": {
    "importPath": "@ocentra/game-asset-domain/content/comingSoon/ComingSoon",
    "assetType": "ComingSoon",
    "displayName": "Coming Soon",
    "icon": "🎮",
    "category": "UI",
    "commonType": "Assets"
  },
  "FeatureBanner": {
    "importPath": "@ocentra/game-asset-domain/content/featureBanner/FeatureBanner",
    "assetType": "FeatureBanner",
    "displayName": "Feature Banner",
    "icon": "📋",
    "category": "Content",
    "commonType": "Assets"
  },
  "ImageCarousel": {
    "importPath": "@ocentra/game-asset-domain/content/imageCarousel/ImageCarousel",
    "assetType": "ImageCarousel",
    "displayName": "Image Carousel",
    "icon": "🎞️",
    "category": "Content",
    "commonType": "Assets"
  },
  "ImageList": {
    "importPath": "@ocentra/game-asset-domain/content/imageList/ImageList",
    "assetType": "ImageList",
    "displayName": "Image List",
    "icon": "🖼️",
    "category": "Content",
    "commonType": "Assets"
  },
  "DeckRankingAxisEntry": {
    "importPath": "@ocentra/game-asset-domain/deck/DeckRanking",
    "assetType": "DeckRankingAxisEntry",
    "displayName": "Deck Ranking Axis Entry",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckRankingLayoutCell": {
    "importPath": "@ocentra/game-asset-domain/deck/DeckRanking",
    "assetType": "DeckRankingLayoutCell",
    "displayName": "Deck Ranking Layout Cell",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckRankingLayoutSection": {
    "importPath": "@ocentra/game-asset-domain/deck/DeckRanking",
    "assetType": "DeckRankingLayoutSection",
    "displayName": "Deck Ranking Layout Section",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckRanking": {
    "importPath": "@ocentra/game-asset-domain/deck/DeckRanking",
    "assetType": "DeckRanking",
    "displayName": "Deck Ranking",
    "icon": "ðŸ“Š",
    "category": "Game",
    "commonType": "Decks"
  },
  "DominoDeckTileMember": {
    "importPath": "@ocentra/game-asset-domain/domino/DominoDeck",
    "assetType": "DominoDeckTileMember",
    "displayName": "Domino Deck Tile Member",
    "category": "Game",
    "commonType": "Decks"
  },
  "DominoDeck": {
    "importPath": "@ocentra/game-asset-domain/domino/DominoDeck",
    "assetType": "DominoDeck",
    "displayName": "Domino Deck",
    "category": "Game",
    "commonType": "Decks"
  },
  "DominoRanking": {
    "importPath": "@ocentra/game-asset-domain/domino/DominoRanking",
    "assetType": "DominoRanking",
    "displayName": "Domino Ranking",
    "category": "Game",
    "commonType": "Assets"
  },
  "DominoTile": {
    "importPath": "@ocentra/game-asset-domain/domino/DominoTile",
    "assetType": "DominoTile",
    "displayName": "Domino Tile",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameInfo": {
    "importPath": "@ocentra/game-asset-domain/game/gameInfo/GameInfo",
    "assetType": "GameInfo",
    "displayName": "Game Info",
    "icon": "📄",
    "category": "Content",
    "commonType": "Assets"
  },
  "CardGameMechanics": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/CardGameMechanics",
    "assetType": "CardGameMechanics",
    "displayName": "Card Game Mechanics",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameMechanics": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanics",
    "assetType": "GameMechanics",
    "displayName": "Game Mechanics",
    "category": "Game",
    "commonType": "Assets"
  },
  "TurnBasedGameMechanics": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanics",
    "assetType": "TurnBasedGameMechanics",
    "displayName": "Turn Based Game Mechanics",
    "category": "Game",
    "commonType": "Assets"
  },
  "GamePlayerModel": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "GamePlayerModel",
    "displayName": "Game Player Model",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameSessionModel": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "GameSessionModel",
    "displayName": "Game Session Model",
    "category": "Game",
    "commonType": "Assets"
  },
  "CardGameDeckModel": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "CardGameDeckModel",
    "displayName": "Card Game Deck Model",
    "category": "Game",
    "commonType": "Decks"
  },
  "GameZoneModel": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "GameZoneModel",
    "displayName": "Game Zone Model",
    "category": "Game",
    "commonType": "Assets"
  },
  "GamePhaseFlowModel": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "GamePhaseFlowModel",
    "displayName": "Game Phase Flow Model",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameActionSet": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "GameActionSet",
    "displayName": "Game Action Set",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameStateEventModel": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "GameStateEventModel",
    "displayName": "Game State Event Model",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameValidationFixtures": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/GameMechanicsModel",
    "assetType": "GameValidationFixtures",
    "displayName": "Game Validation Fixtures",
    "category": "Game",
    "commonType": "Assets"
  },
  "CardGameRules": {
    "importPath": "@ocentra/game-asset-domain/game/gameRules/CardGameRules",
    "assetType": "CardGameRules",
    "displayName": "Card Game Rules",
    "icon": "🃏",
    "category": "Game",
    "commonType": "CardRules"
  },
  "GameRules": {
    "importPath": "@ocentra/game-asset-domain/game/gameRules/GameRules",
    "assetType": "GameRules",
    "displayName": "Game Rules",
    "icon": "📜",
    "category": "Game",
    "commonType": "CardRules"
  },
  "TrumpBonusValues": {
    "importPath": "@ocentra/game-asset-domain/game/gameRules/TrumpBonusValues",
    "assetType": "TrumpBonusValues",
    "displayName": "Trump Bonus Values",
    "commonType": "Assets"
  },
  "BaseBonusRule": {
    "importPath": "@ocentra/game-asset-domain/game/rules/BaseBonusRule",
    "assetType": "BaseBonusRule",
    "displayName": "Base Bonus Rule",
    "icon": "⭐",
    "category": "Game",
    "commonType": "CardRules"
  },
  "BaseRule": {
    "importPath": "@ocentra/game-asset-domain/game/rules/BaseRule",
    "assetType": "BaseRule",
    "displayName": "Base Rule",
    "icon": "📋",
    "category": "Game",
    "commonType": "CardRules"
  },
  "DifferentColorsSequence": {
    "importPath": "@ocentra/game-asset-domain/game/rules/DifferentColorsSequence",
    "assetType": "DifferentColorsSequence",
    "displayName": "Different Colors Sequence",
    "icon": "🎨",
    "category": "Game",
    "commonType": "Assets"
  },
  "FiveOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/FiveOfAKind",
    "assetType": "FiveOfAKind",
    "displayName": "Five Of A Kind",
    "icon": "⭐",
    "category": "Game",
    "commonType": "Assets"
  },
  "Flush": {
    "importPath": "@ocentra/game-asset-domain/game/rules/Flush",
    "assetType": "Flush",
    "displayName": "Flush",
    "icon": "💎",
    "category": "Game",
    "commonType": "Assets"
  },
  "FourOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/FourOfAKind",
    "assetType": "FourOfAKind",
    "displayName": "Four Of A Kind",
    "icon": "🎯",
    "category": "Game",
    "commonType": "Assets"
  },
  "FullHouse": {
    "importPath": "@ocentra/game-asset-domain/game/rules/FullHouse",
    "assetType": "FullHouse",
    "displayName": "Full House",
    "icon": "🏠",
    "category": "Game",
    "commonType": "Assets"
  },
  "HighCard": {
    "importPath": "@ocentra/game-asset-domain/game/rules/HighCard",
    "assetType": "HighCard",
    "displayName": "High Card",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Assets"
  },
  "MultipleFourOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/MultipleFourOfAKind",
    "assetType": "MultipleFourOfAKind",
    "displayName": "Multiple Four Of A Kind",
    "icon": "🎯🎯",
    "category": "Game",
    "commonType": "Assets"
  },
  "MultiplePairs": {
    "importPath": "@ocentra/game-asset-domain/game/rules/MultiplePairs",
    "assetType": "MultiplePairs",
    "displayName": "Multiple Pairs",
    "icon": "👥👥",
    "category": "Game",
    "commonType": "Assets"
  },
  "MultipleTriplets": {
    "importPath": "@ocentra/game-asset-domain/game/rules/MultipleTriplets",
    "assetType": "MultipleTriplets",
    "displayName": "Multiple Triplets",
    "icon": "🎲🎲",
    "category": "Game",
    "commonType": "Assets"
  },
  "PairRule": {
    "importPath": "@ocentra/game-asset-domain/game/rules/PairRule",
    "assetType": "PairRule",
    "displayName": "Pair Rule",
    "icon": "👥",
    "category": "Game",
    "commonType": "CardRules"
  },
  "RoyalFlush": {
    "importPath": "@ocentra/game-asset-domain/game/rules/RoyalFlush",
    "assetType": "RoyalFlush",
    "displayName": "Royal Flush",
    "icon": "👑",
    "category": "Game",
    "commonType": "Assets"
  },
  "SameColorsSequence": {
    "importPath": "@ocentra/game-asset-domain/game/rules/SameColorsSequence",
    "assetType": "SameColorsSequence",
    "displayName": "Same Colors Sequence",
    "icon": "🌈",
    "category": "Game",
    "commonType": "Assets"
  },
  "StraightFlush": {
    "importPath": "@ocentra/game-asset-domain/game/rules/StraightFlush",
    "assetType": "StraightFlush",
    "displayName": "Straight Flush",
    "icon": "🔥",
    "category": "Game",
    "commonType": "Assets"
  },
  "ThreeOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/ThreeOfAKind",
    "assetType": "ThreeOfAKind",
    "displayName": "Three Of A Kind",
    "icon": "🎲",
    "category": "Game",
    "commonType": "Assets"
  },
  "TrumpOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/TrumpOfAKind",
    "assetType": "TrumpOfAKind",
    "displayName": "Trump Of A Kind",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Assets"
  },
  "CardGameScoring": {
    "importPath": "@ocentra/game-asset-domain/game/scoring/CardGameScoring",
    "assetType": "CardGameScoring",
    "displayName": "Card Game Scoring",
    "icon": "🎯",
    "category": "Game",
    "commonType": "Scoring"
  },
  "Scoring": {
    "importPath": "@ocentra/game-asset-domain/game/scoring/Scoring",
    "assetType": "Scoring",
    "displayName": "Scoring",
    "icon": "🎯",
    "category": "Game",
    "commonType": "Scoring"
  },
  "Strategy": {
    "importPath": "@ocentra/game-asset-domain/game/strategy/Strategy",
    "assetType": "Strategy",
    "displayName": "Strategy",
    "icon": "💡",
    "category": "Game",
    "commonType": "Strategy"
  },
  "CardGameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/cardGameMode/CardGameMode",
    "assetType": "CardGameMode",
    "displayName": "Card Game Mode",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Assets"
  },
  "BettingGameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/core/BettingGameMode",
    "assetType": "BettingGameMode",
    "displayName": "Betting Game Mode",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/core/GameMode",
    "assetType": "GameMode",
    "displayName": "Game Mode",
    "category": "Game",
    "commonType": "Assets"
  },
  "TurnBasedGameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/core/TurnBasedGameMode",
    "assetType": "TurnBasedGameMode",
    "displayName": "Turn Based Game Mode",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameRulesContainer": {
    "importPath": "@ocentra/game-asset-domain/gameMode/types/GameRulesContainer",
    "assetType": "GameRulesContainer",
    "displayName": "Game Rules Container",
    "commonType": "CardRules"
  },
  "HanafudaCard": {
    "importPath": "@ocentra/game-asset-domain/hanafuda/HanafudaCard",
    "assetType": "HanafudaCard",
    "displayName": "Hanafuda Card",
    "category": "Game",
    "commonType": "Assets"
  },
  "HanafudaDeck": {
    "importPath": "@ocentra/game-asset-domain/hanafuda/HanafudaDeck",
    "assetType": "HanafudaDeck",
    "displayName": "Hanafuda Deck",
    "category": "Game",
    "commonType": "Decks"
  },
  "HanafudaRankingSlot": {
    "importPath": "@ocentra/game-asset-domain/hanafuda/HanafudaRanking",
    "assetType": "HanafudaRankingSlot",
    "displayName": "Hanafuda Ranking Slot",
    "category": "Game",
    "commonType": "Assets"
  },
  "HanafudaRankingMonth": {
    "importPath": "@ocentra/game-asset-domain/hanafuda/HanafudaRanking",
    "assetType": "HanafudaRankingMonth",
    "displayName": "Hanafuda Ranking Month",
    "category": "Game",
    "commonType": "Assets"
  },
  "HanafudaRanking": {
    "importPath": "@ocentra/game-asset-domain/hanafuda/HanafudaRanking",
    "assetType": "HanafudaRanking",
    "displayName": "Hanafuda Ranking",
    "category": "Game",
    "commonType": "Assets"
  },
  "MahjongDeckTileMember": {
    "importPath": "@ocentra/game-asset-domain/mahjong/MahjongDeck",
    "assetType": "MahjongDeckTileMember",
    "displayName": "Mahjong Deck Tile Member",
    "category": "Game",
    "commonType": "Decks"
  },
  "MahjongDeck": {
    "importPath": "@ocentra/game-asset-domain/mahjong/MahjongDeck",
    "assetType": "MahjongDeck",
    "displayName": "Mahjong Deck",
    "category": "Game",
    "commonType": "Decks"
  },
  "MahjongRankingExtraTile": {
    "importPath": "@ocentra/game-asset-domain/mahjong/MahjongRanking",
    "assetType": "MahjongRankingExtraTile",
    "displayName": "Mahjong Ranking Extra Tile",
    "category": "Game",
    "commonType": "Assets"
  },
  "MahjongRanking": {
    "importPath": "@ocentra/game-asset-domain/mahjong/MahjongRanking",
    "assetType": "MahjongRanking",
    "displayName": "Mahjong Ranking",
    "category": "Game",
    "commonType": "Assets"
  },
  "MahjongTile": {
    "importPath": "@ocentra/game-asset-domain/mahjong/MahjongTile",
    "assetType": "MahjongTile",
    "displayName": "Mahjong Tile",
    "category": "Game",
    "commonType": "Assets"
  },
  "PlayingCard": {
    "importPath": "@ocentra/game-asset-domain/playingCard/PlayingCard",
    "assetType": "PlayingCard",
    "displayName": "Playing Card",
    "category": "Game",
    "commonType": "Assets"
  },
  "PlayingCardDeck": {
    "importPath": "@ocentra/game-asset-domain/playingCard/PlayingCardDeck",
    "assetType": "PlayingCardDeck",
    "displayName": "Playing Card Deck",
    "category": "Game",
    "commonType": "Decks"
  },
  "PlayingCardRankingEntry": {
    "importPath": "@ocentra/game-asset-domain/playingCard/PlayingCardRanking",
    "assetType": "PlayingCardRankingEntry",
    "displayName": "Playing Card Ranking Entry",
    "category": "Game",
    "commonType": "Assets"
  },
  "PlayingCardRanking": {
    "importPath": "@ocentra/game-asset-domain/playingCard/PlayingCardRanking",
    "assetType": "PlayingCardRanking",
    "displayName": "Playing Card Ranking",
    "category": "Game",
    "commonType": "Assets"
  },
  "CardGameLayout": {
    "importPath": "@ocentra/game-asset-domain/ui/layout/CardGameLayout",
    "assetType": "CardGameLayout",
    "displayName": "Card Game Layout",
    "icon": "🎏",
    "category": "UI",
    "commonType": "Assets"
  },
  "Layout": {
    "importPath": "@ocentra/game-asset-domain/ui/layout/Layout",
    "assetType": "Layout",
    "displayName": "Layout",
    "icon": "📐",
    "category": "UI",
    "commonType": "Assets"
  },
  "PageLayout": {
    "importPath": "@ocentra/game-asset-domain/ui/pageLayout/PageLayout",
    "assetType": "PageLayout",
    "displayName": "Page Layout",
    "icon": "Page",
    "category": "UI",
    "commonType": "Assets"
  },
  "UIComponent": {
    "importPath": "@ocentra/game-asset-domain/ui/UIComponent",
    "assetType": "UIComponent",
    "displayName": "UI Component",
    "icon": "🎨",
    "category": "UI",
    "commonType": "Assets"
  }
} as const;

export const assetTypeMap: Record<string, AssetTypeMetadata> = Object.fromEntries(
  Object.entries(rawAssetTypeMap).map(([assetType, metadata]) => [
    assetType,
    {
      ...metadata,
      importPath: decodeImportPath(metadata.importPath),
    },
  ]),
);
