// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

export const fieldTypeMap: Record<string, Record<string, string>> = {
  "AssetResourceEntry": {
    "guid": "AssetGUIDType",
    "assetType": "AssetType",
    "inheritanceChain": "string[] | null",
    "variant": "string | null"
  },
  "FileResourceEntry": {
    "fileType": "String"
  },
  "ImageResourceEntry": {
    "hash": "ImageHash"
  },
  "ResourceEntry": {
    "path": "String",
    "displayName": "String",
    "gameId": "GameId | null",
    "category": "AssetCategory | null",
    "mimeType": "MimeType | null",
    "fileSize": "number | null",
    "createdAt": "Timestamp | null",
    "updatedAt": "Timestamp | null",
    "lastScanAt": "Timestamp | null",
    "checksum": "AssetChecksum | null"
  },
  "SoundResourceEntry": {
    "hash": "SoundHash"
  },
  "VideoResourceEntry": {
    "hash": "VideoHash"
  },
  "AIModelList": {
    "name": "String",
    "description": "String",
    "models": "Array",
    "defaultModelId": "String",
    "defaultQuantPath": "String"
  },
  "ModelQuantSettings": {
    "modelId": "String",
    "quantPath": "String",
    "displayName": "String",
    "description": "String",
    "settings": "InferenceSettings"
  },
  "BaseAssetMetadata": {
    "typeCategory": "AssetTypeCategory | null",
    "tags": "Array",
    "status": "AssetStatus | null",
    "createdAt": "String",
    "updatedAt": "String",
    "guid": "String"
  },
  "Card": {
    "suit": "Suit",
    "rank": "CardValue",
    "imageHash": "ImageHash",
    "cardId": "String",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "CardSuitEntry": {
    "SuitName": "String",
    "SuitSymbol": "String",
    "DisplayOrder": "Number",
    "CardName": "String",
    "Value": "Number",
    "CardSymbol": "String",
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "cardIdentities": "Array",
    "suits": "Array",
    "rankings": "Array"
  },
  "CardRankingEntry": {
    "CardName": "String",
    "Value": "Number",
    "CardSymbol": "String",
    "DisplayOrder": "Number",
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "cardIdentities": "Array",
    "suits": "Array",
    "rankings": "Array"
  },
  "CardRanking": {
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "cardIdentities": "Array",
    "suits": "Array",
    "rankings": "Array"
  },
  "Deck": {
    "name": "String",
    "cardTemplates": "Array",
    "backCardHash": "ImageHash",
    "imageSourceFolderPath": "String",
    "cardOutputPath": "String",
    "backCardSourceFolderPath": "String",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "ImageCarousel": {
    "slides": "Array",
    "autoplayIntervalMs": "Number",
    "lastImageDurationMs": "Number",
    "fastRotationDurationMs": "Number",
    "defaultRotationDurationMs": "Number",
    "fastRotationThreshold": "Number",
    "slideTransitionDelayMs": "Number"
  },
  "ImageList": {
    "images": "Array"
  },
  "GameInfo": {
    "synthesisManifest": "SynthesisManifest",
    "hero": "HeroSection",
    "elementType": "Object as unknown as new ()",
    "description": "String",
    "tags": "Array",
    "comingSoon": "Boolean",
    "minPlayers": "number | null",
    "maxPlayers": "number | null",
    "routePath": "String",
    "LLM": "String",
    "Player": "String",
    "tagline": "String",
    "tagline2": "String",
    "shortDescription": "String",
    "gameIconImage": "ImageHash",
    "gameCategory": "Category",
    "subcategory": "SubCategory",
    "playerMode": "PlayerMode",
    "difficulty": "Difficulty",
    "duration": "String",
    "origin": "String",
    "deck": "String",
    "alsoKnownAs": "Array",
    "playersDisplay": "String",
    "historyContent": "HistoryContent | null",
    "setupContent": "SetupContent | null",
    "variationsContent": "VariationsContent | null",
    "aiContent": "AIContent | null",
    "sourcesContent": "SourcesContent | null",
    "quality": "string | null",
    "completeness": "Record<string, boolean> | null"
  },
  "CardGameRules": {
    "bonusRuleGuids": "Array",
    "useTrump": "Boolean",
    "trumpBonusValues": "TrumpBonusValues"
  },
  "GameRules": {
    "LLM": "String",
    "Player": "String",
    "objective": "String",
    "gameplay": "String",
    "keyRules": "Array",
    "moveValidityConditions": "Record<string, string> | null",
    "exampleHands": "Array",
    "bonusRules": "String"
  },
  "TrumpBonusValues": {
    "cardInMiddleBonus": "Number",
    "fiveOfKindBonus": "Number",
    "flushBonus": "Number",
    "fourOfKindBonus": "Number",
    "threeOfKindBonus": "Number",
    "pairBonus": "Number",
    "trumpCardBonus": "Number",
    "wildCardBonus": "Number",
    "rankAdjacentBonus": "Number"
  },
  "DifferentColorsSequence": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FiveOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "Flush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FourOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FullHouse": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "HighCard": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultipleFourOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultiplePairs": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultipleTriplets": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "PairRule": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "RoyalFlush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "SameColorsSequence": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "StraightFlush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "ThreeOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "TrumpOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "CardGameScoring": {
    "scoringType": "ScoringType",
    "patternMultipliers": "Record<string, number> | null",
    "priorityOrder": "Array",
    "winCondition": "String",
    "cardValues": "Record<string, number>",
    "penalties": "String",
    "targetScore": "number | null",
    "scoringDirection": "ScoringDirection"
  },
  "Scoring": {
    "cardRankingAsset": "AssetReference | string | null",
    "scoringFormula": "String",
    "scoringRules": "Record<string, unknown> | null",
    "description": "String"
  },
  "Strategy": {
    "LLM": "String",
    "Player": "String",
    "basic": "String",
    "intermediate": "String",
    "advanced": "String",
    "tips": "Array",
    "aggressiveness": "Number",
    "riskTolerance": "Number",
    "bluffFrequency": "Number",
    "bluffSettings": "Record<string, string>"
  },
  "CardGameMode": {
    "baseBet": "Number",
    "initialNumberOfCards": "Number",
    "maxNumberOfCards": "Number",
    "minDecks": "Number",
    "maxDecks": "Number",
    "scoringAsset": "AssetResourceEntry<CardGameScoring>",
    "gameRulesAsset": "AssetResourceEntry<CardGameRules>",
    "strategyAsset": "AssetResourceEntry<Strategy>",
    "gameInfoAsset": "AssetResourceEntry<GameInfo>",
    "deckAsset": "AssetResourceEntry<Deck>",
    "layoutAsset": "AssetResourceEntry<CardGameLayout>",
    "carouselImagesAsset": "AssetResourceEntry<ImageCarousel>",
    "minPlayers": "Number",
    "maxPlayers": "Number",
    "minHumanPlayers": "Number",
    "maxHumanPlayers": "Number",
    "supportsAI": "Boolean",
    "aiCountsAsPlayer": "Boolean",
    "useTrump": "Boolean",
    "trumpBonusValues": "TrumpBonusValues"
  },
  "BettingGameMode": {
    "initialPlayerCoins": "Number"
  },
  "GameMode": {
    "releaseStatus": "GameModeStatus",
    "bannerImage": "ImageHash",
    "gameIcon": "ImageHash"
  },
  "TurnBasedGameMode": {
    "minRounds": "Number",
    "maxRounds": "number | null",
    "turnDuration": "Number"
  },
  "GameRulesContainer": {
    "LLM": "String",
    "Player": "String"
  },
  "AssetRegistry": {
    "resources": "Array",
    "lastSyncFromCloud": "Timestamp | null",
    "lastSyncToCloud": "Timestamp | null",
    "totalAssets": "Number",
    "lastGenerated": "Timestamp",
    "version": "Number",
    "lastScanTimestamp": "Timestamp | null",
    "dirtyAssets": "Array",
    "cloudLastModifiedCacheData": "Record<string, string>"
  },
  "CardGameLayout": {
    "defaultPlayerCount": "Number",
    "presets": "Record<string, LayoutPreset>",
    "gameplay": "Record<string, unknown>",
    "extensions": "Record<string, unknown>"
  },
  "Layout": {
    "layout": "LayoutStructure"
  },
  "UIComponent": {
    "component": "ComponentType",
    "styles": "ComponentStyles",
    "elementType": "Object as unknown as new ()"
  }
};
