// This file is auto-generated by scripts/generate-inspector-map.mjs
// Do not edit manually - it will be overwritten by tooling

export type ImportPath = string;

export const inspectorMap = {
  "Array": "@/lib/core/inspector/components/ArrayInspector",
  "AssetRegistry": "@/lib/assets/exportIndex/ExportIndexInspector",
  "Base": "@/lib/core/inspector/components/BaseInspector",
  "BaseBonusRule": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "Card": "@/lib/assets/card/cardBase/CardInspector",
  "CardGameLayout": "@/lib/assets/ui/layout/LayoutInspector",
  "CardGameMechanics": "@/lib/assets/game/gameMechanics/CardGameMechanicsInspector",
  "CardGameMode": "@/lib/assets/gameMode/cardGameMode/CardGameModeInspector",
  "CardGameRules": "@/lib/assets/game/gameRules/CardGameRulesInspector",
  "CardGameScoring": "@/lib/assets/game/scoring/CardGameScoringInspector",
  "CardRanking": "@/lib/assets/card/cardRanking/CardRankingInspector",
  "ComingSoon": "@/lib/assets/content/comingSoon/ComingSoonInspector",
  "Deck": "@/lib/assets/card/deck/DeckInspector",
  "DeckManager": "@/lib/assets/deck/DeckManagerInspector",
  "Dictionary": "@/lib/core/inspector/components/DictionaryInspector",
  "DifferentColorsSequence": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "ExportIndex": "@/lib/assets/exportIndex/ExportIndexInspector",
  "FeatureBanner": "@/lib/assets/content/featureBanner/FeatureBannerInspector",
  "FiveOfAKind": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "Flush": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "FourOfAKind": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "FullHouse": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "GameInfo": "@/lib/assets/game/gameInfo/GameInfoInspector",
  "GameRegistry": "@/lib/assets/gameRegistry/GameRegistryInspector",
  "GameRules": "@/lib/assets/game/gameRules/GameRulesInspector",
  "Generic": "@/lib/core/inspector/components/GenericInspector",
  "HighCard": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "ImageCarousel": "@/lib/assets/content/imageCarousel/ImageCarouselInspector",
  "ImageList": "@/lib/assets/content/imageList/ImageListInspector",
  "Layout": "@/lib/assets/ui/layout/LayoutInspector",
  "MultipleFourOfAKind": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "MultiplePairs": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "MultipleTriplets": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "PairRule": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "RoyalFlush": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "SameColorsSequence": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "Scoring": "@/lib/assets/game/scoring/ScoringInspector",
  "StraightFlush": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "Strategy": "@/lib/assets/game/strategy/StrategyInspector",
  "ThreeOfAKind": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "TrumpOfAKind": "@/lib/assets/game/rules/BaseBonusRuleInspector",
  "UIComponent": "@/lib/assets/ui/UIComponentInspector"
} as const;

export type InspectorTypeName = keyof typeof inspectorMap;

export type InspectorMap = Record<InspectorTypeName, ImportPath>;
