/**
 * Log Module Registry (Auto-Generated)
 *
 * This file is auto-generated by infra/cloudflare/scripts/generate-log-modules.ts
 * Do not edit manually - it will be overwritten on build
 *
 * Default Behavior:
 *   - Dev/Test: All modules enabled automatically (see everything)
 *   - Production: Only Errors/Warnings (safe by default)
 *   - Production debugging: Use X-Debug-Modules header per-request
 *
 * @example
 * // Dev/Test: Just run - all logs visible automatically
 * npm test
 *
 * // Production debugging: Enable specific modules per-request
 * fetch(url, { headers: { 'X-Debug-Modules': 'Badges,Credits' } })
 */

/**
 * All available log modules - automatically discovered from codebase
 */
export const LogModule = {
  // Utilities
  Badges: 'Badges',

} as const;

export type LogModuleType = (typeof LogModule)[keyof typeof LogModule];
