export type DeckType = string
export type SuitSet = string
export type RankSet = string

export type DeckTriple = readonly [
  deckType: DeckType,
  suitSet: SuitSet,
  rankSet: RankSet,
]

export const ALLOWED_TRIPLES: readonly DeckTriple[] = [
  ['Standard 52', 'French', 'Standard_52'],
  ['Standard 52 + Joker(s)', 'French', 'Standard_52'],
  ['Standard 48', 'French', 'Pinochle_48'],
  ['Standard 48', 'French', 'Stripped_48'],
  ['Standard 48', 'Spanish', 'Stripped_48'],
  ['Standard 40', 'French', 'Stripped_40'],
  ['Standard 40', 'Italian', 'Stripped_40'],
  ['Standard 40', 'Spanish', 'Stripped_40'],
  ['Standard 40', 'Portuguese', 'Stripped_40'],
  ['Standard 36', 'French', 'Stripped_36'],
  ['Standard 36', 'German', 'Stripped_36'],
  ['Standard 36', 'Italian', 'Stripped_36'],
  ['Standard 32', 'French', 'Stripped_32'],
  ['Standard 32', 'German', 'Stripped_32'],
  ['Standard 32 + Joker(s)', 'French', 'Stripped_32'],
  ['Standard 32 + Joker(s)', 'German', 'Stripped_32'],
  ['Standard 24', 'French', 'Stripped_24'],
  ['Standard 24', 'German', 'Stripped_24'],
  ['Standard 44', 'French', 'Stripped_44'],
  ['Double 52', 'French', 'Standard_52'],
  ['Double 52 + 4 Jokers', 'French', 'Standard_52'],
  ['Double 32', 'French', 'Stripped_32'],
  ['Double 32', 'German', 'Stripped_32'],
  ['Double 24', 'French', 'Stripped_24'],
  ['Double 24', 'German', 'Stripped_24'],
  ['Quad 36', 'French', 'Stripped_36'],
  ['Quad 40', 'French', 'Stripped_40'],
  ['Oct 40', 'French', 'Stripped_40'],
  ['Tarot 78', 'French_tarock', 'Tarot_78'],
  ['Tarot 78', 'Tarot_de_Marseille', 'Tarot_78'],
  ['Tarot 78', 'Swiss_1JJ', 'Tarot_78'],
  ['Tarot 78', 'Tarocco_Piemontese', 'Tarot_78'],
  ['Tarot 62', 'Swiss_1JJ', 'Tarot_62'],
  ['Tarot 62', 'Tarocco_Piemontese', 'Tarot_62'],
  ['Minchiate 97', 'Minchiate', 'Minchiate_97'],
  ['Tarot 54', 'Industrie_und_Glueck', 'Tarot_54'],
  ['Tarot 54', 'Cego', 'Tarot_54'],
  ['Tarot 40', 'Industrie_und_Glueck', 'Tarot_40'],
  ['Tarot 66', 'French_tarock', 'Tarot_66'],
  ['Tarot 66', 'Tarot_de_Marseille', 'Tarot_66'],
  ['Tarot 42', 'Industrie_und_Glueck', 'Tarot_42'],
  ['Cego 38', 'Cego', 'Cego_38'],
  ['Tarocco Bolognese 62', 'Italian', 'Tarocco_Bolognese_62'],
  ['Tarocco Siciliano 63', 'Italian', 'Tarocco_Sicilian_63'],
  ['Tarocco Siciliano 64', 'Italian', 'Tarocco_Sicilian_64'],
  ['500 deck 63', 'French', 'FiveHundred_63'],
  ['Double-6 Dominoes', 'Dominoes', 'Domino_double6'],
  ['Double-6 Dominoes x2', 'Dominoes', 'Domino_double6'],
  ['Double-6 Dominoes x4', 'Dominoes', 'Domino_double6'],
  ['Double-6 Dominoes', 'Khorol', 'Domino_double6'],
  ['Double-6 Dominoes', 'E_awase', 'Domino_double6'],
  ['Double-8 Dominoes', 'Dominoes', 'Domino_double8'],
  ['Double-8 Dominoes', 'Khorol', 'Domino_double8'],
  ['Double-8 Dominoes', 'E_awase', 'Domino_double8'],
  ['Double-9 Dominoes', 'Dominoes', 'Domino_double9'],
  ['Double-9 Dominoes', 'Khorol', 'Domino_double9'],
  ['Double-9 Dominoes', 'E_awase', 'Domino_double9'],
  ['Double-12 Dominoes', 'Dominoes', 'Domino_double12'],
  ['Double-12 Dominoes', 'Khorol', 'Domino_double12'],
  ['Double-12 Dominoes', 'E_awase', 'Domino_double12'],
  ['Double-15 Dominoes', 'Dominoes', 'Domino_double15'],
  ['Double-6 + Double-12 Dominoes', 'Dominoes', 'Domino_double6'],
  ['Double-6 + Double-12 Dominoes', 'Dominoes', 'Domino_double6_plus_double12'],
  ['Double-9 + Double-12 Dominoes', 'Dominoes', 'Domino_double9'],
  ['Double-9 + Double-12 Dominoes', 'Dominoes', 'Domino_double9_plus_double12'],
  ['Chinese domino 32', 'Chinese_domino', 'Chinese_domino'],
  ['Chinese domino 84', 'Chinese_domino', 'Chinese_domino'],
  ['Hanafuda 48', 'Hanafuda', 'Hanafuda'],
  ['Hanafuda 48', 'Hanafuda_snow', 'Hanafuda'],
  ['Hanafuda 52', 'Hanafuda', 'Hanafuda'],
  ['Kabufuda 40', 'Kabufuda', 'Kabufuda'],
  ['Mahjong 136', 'Mahjong', 'Mahjong_136'],
  ['Mahjong 144', 'Mahjong', 'Mahjong'],
  ['Mahjong 148', 'Mahjong', 'Mahjong_148'],
  ['Mahjong 152', 'Mahjong', 'Mahjong_152'],
  ['Mahjong 160', 'Mahjong', 'Mahjong_160'],
  ['Khorol 60', 'Khorol', 'Khorol'],
  ['Daaluu 64', 'Daaluu', 'Daaluu'],
  ['Money-suited 39', 'Money-suited', 'Money-suited'],
  ['Money-suited 38', 'Money-suited', 'Money-suited'],
  ['Ganjifa', 'Ganjifa', 'Ganjifa'],
  ['Whot 54', 'Whot', 'Whot'],
  ['Okey 106', 'Okey', 'Okey'],
  ['Unsun Karuta 75', 'Unsun_karuta', 'Unsun_karuta'],
  ['Komatsufuda 48', 'Komatsufuda', 'Komatsufuda'],
  ['Uta-garuta 200', 'Uta_garuta', 'Uta_garuta'],
  ['Iroha Karuta 96', 'Iroha_karuta', 'Iroha_karuta'],
  ['Ceki 60', 'Ceki', 'Ceki'],
  ['To_tom 120', 'To_tom', 'To_tom'],
  ['Bai_choi 33', 'Bai_choi', 'Bai_choi'],
  ['Tehonbiki 48', 'Tehonbiki', 'Tehonbiki'],
  ['Khanhoo 30', 'Khanhoo', 'Khanhoo'],
  ['Madiao 40', 'Madiao', 'Madiao'],
  ['Stripped 35', 'French', 'Stripped_35'],
  ['Standard 30', 'French', 'Stripped_30'],
  ['Standard 28', 'French', 'Stripped_28'],
  ['Standard 26', 'French', 'Stripped_26'],
  ['Standard 16', 'French', 'Stripped_16'],
  ['Treikort 27', 'French', 'Treikort_27'],
  ['Tiddlywink', 'Tiddlywink_colors', 'Tiddlywink_pieces'],
  ['Standard 44', 'French', 'Stripped_44'],
  ['Quad 52 + 8 Jokers', 'French', 'Standard_52'],
  ['Triple 52 + 6 Jokers', 'French', 'Standard_52'],
  ['Xiangqi 32', 'Xiangqi_red_black', 'Xiangqi_pieces'],
  ['Four Color 112', 'Four_color', 'Four_color_pieces'],
  ['Gnav 42', 'Gnav', 'Gnav_ranks'],
  ['Goita 32', 'Goita', 'Goita_pieces'],
  ['Rook 56', 'Rook_colors', 'Rook_1_14'],
  ['Hols der Geier 75', 'Hols_der_Geier_colors', 'Hols_der_Geier_1_15'],
  ['Numbered 104', 'Numbered_104', 'Numbered_1_104'],
]

const TRIPLE_SET = new Set(
  ALLOWED_TRIPLES.map(([d, s, r]) => `${d}\0${s}\0${r}`)
)

export function isValidDeckTriple(
  deckType: string,
  suitSet: string,
  rankSet: string
): boolean {
  return TRIPLE_SET.has(`${deckType}\0${suitSet}\0${rankSet}`)
}
