export const DECK_TYPE_VALUES = [
  'Standard 52',
  'Standard 52 + Joker(s)',
  'Standard 48',
  'Standard 40',
  'Standard 36',
  'Standard 32',
  'Standard 32 + Joker(s)',
  'Standard 44',
  'Standard 24',
  'Double 52',
  'Double 52 + 4 Jokers',
  'Double 32',
  'Double 24',
  'Quad 36',
  'Quad 40',
  'Oct 40',
  'Quad 52 + 8 Jokers',
  'Triple 52 + 6 Jokers',
  'Gnav 42',
  'Goita 32',
  'Rook 56',
  'Xiangqi 32',
  'Four Color 112',
  'Tarot 78',
  'Tarot 62',
  'Minchiate 97',
  'Tarot 54',
  'Tarot 40',
  'Tarot 66',
  'Tarot 42',
  'Cego 38',
  'Tarocco Bolognese 62',
  'Tarocco Siciliano 64',
  '500 deck 63',
  'Double-6 Dominoes',
  'Double-6 Dominoes x2',
  'Double-6 Dominoes x4',
  'Double-8 Dominoes',
  'Double-9 Dominoes',
  'Double-12 Dominoes',
  'Double-15 Dominoes',
  'Double-6 + Double-12 Dominoes',
  'Double-9 + Double-12 Dominoes',
  'Chinese domino 32',
  'Chinese domino 84',
  'Hanafuda 48',
  'Hanafuda 52',
  'Kabufuda 40',
  'Mahjong 136',
  'Mahjong 144',
  'Mahjong 148',
  'Mahjong 152',
  'Mahjong 160',
  'Khorol 60',
  'Daaluu 64',
  'Money-suited 39',
  'Money-suited 38',
  'Ganjifa',
  'Whot 54',
  'Okey 106',
  'Unsun Karuta 75',
  'Komatsufuda 48',
  'Uta-garuta 200',
  'Iroha Karuta 96',
  'Ceki 60',
  'To_tom 120',
  'Bai_choi 33',
  'Madiao 40',
  'Khanhoo 30',
  'Tehonbiki 48',
  'Stripped 35',
  'Standard 30',
  'Standard 28',
  'Standard 26',
  'Standard 16',
  'Treikort 27',
  'Tiddlywink',
  'Hols der Geier 75',
  'Numbered 104',
] as const

export const DOMINO_DECK_TYPE_VALUES = [
  'Double-6 Dominoes',
  'Double-6 Dominoes x2',
  'Double-6 Dominoes x4',
  'Double-8 Dominoes',
  'Double-9 Dominoes',
  'Double-12 Dominoes',
  'Double-15 Dominoes',
  'Double-6 + Double-12 Dominoes',
  'Double-9 + Double-12 Dominoes',
  'Chinese domino 32',
  'Chinese domino 84',
  'Khorol 60',
  'Daaluu 64',
] as const

export const DOMINO_DECK_TYPE_SET = new Set<string>(DOMINO_DECK_TYPE_VALUES)

export const TILE_DECK_TYPE_VALUES = [
  ...DOMINO_DECK_TYPE_VALUES,
  'Hanafuda 48',
  'Hanafuda 52',
  'Kabufuda 40',
  'Mahjong 136',
  'Mahjong 144',
  'Mahjong 148',
  'Mahjong 152',
  'Mahjong 160',
  'Daaluu 64',
  'Okey 106',
  'Ceki 60',
  'To_tom 120',
  'Bai_choi 33',
  'Madiao 40',
  'Khanhoo 30',
  'Tehonbiki 48',
] as const

export const TILE_DECK_TYPE_SET = new Set<string>(TILE_DECK_TYPE_VALUES)

export type DeckType = (typeof DECK_TYPE_VALUES)[number]
