import Banner1v1 from './images/banners/1v1.png';
import BannerAIBenchmarking from './images/banners/AI Benchmarking.png';
import BannerEverythigOnChain from './images/banners/EverythigOnChain.png';
import BannerFairplayGareenteed from './images/banners/FairplayGareenteed.png';
import BannerGlobalLeaderboard from './images/banners/GlobalLeaderboard.png';
import BannerIntelligentAI from './images/banners/IntelligentAI.png';
import BannerPlayAnywhere from './images/banners/PlayAnywhere.png';
import BannerPlayYourWay from './images/banners/PlayYourWay.png';
import BannerProvablyFair from './images/banners/ProvablyFair.png';
import BannerRewardingEconomy from './images/banners/RewardingEconomy.png';
import BannerSolanaPowered from './images/banners/SolanaPowered.png';
import BannerTrackYourProgress from './images/banners/TrackYourProgress.png';
import BannerTrueMultiplayer from './images/banners/TrueMultiplayer.png';
import BannerWalletFreedom from './images/banners/WalletFreedom.png';

export const banner1v1ImageUrl = Banner1v1;
export const bannerAIBenchmarkingImageUrl = BannerAIBenchmarking;
export const bannerEverythingOnChainImageUrl = BannerEverythigOnChain;
export const bannerFairplayGuaranteedImageUrl = BannerFairplayGareenteed;
export const bannerGlobalLeaderboardImageUrl = BannerGlobalLeaderboard;
export const bannerIntelligentAIImageUrl = BannerIntelligentAI;
export const bannerPlayAnywhereImageUrl = BannerPlayAnywhere;
export const bannerPlayYourWayImageUrl = BannerPlayYourWay;
export const bannerProvablyFairImageUrl = BannerProvablyFair;
export const bannerRewardingEconomyImageUrl = BannerRewardingEconomy;
export const bannerSolanaPoweredImageUrl = BannerSolanaPowered;
export const bannerTrackYourProgressImageUrl = BannerTrackYourProgress;
export const bannerTrueMultiplayerImageUrl = BannerTrueMultiplayer;
export const bannerWalletFreedomImageUrl = BannerWalletFreedom;
