import CardGameBg from './images/cardgame/commons/CardBg.png';
import CardGameMlogo from './images/cardgame/commons/Mlogo.png';
import CardGameBackCard from './images/cardgame/commons/BackCard.png';
import CardClubFilled from './images/cardgame/fullcard/256slightfill/CardClubFilled.png';
import CardClubHollow from './images/cardgame/fullcard/256slightfill/CardClubHollow.png';
import CardDiamondFilled from './images/cardgame/fullcard/256slightfill/CardDiamondFilled.png';
import CardDiamondHollow from './images/cardgame/fullcard/256slightfill/CardDiamondHollow.png';
import CardHeartFilled from './images/cardgame/fullcard/256slightfill/CardHeartFilled.png';
import CardHeartHollow from './images/cardgame/fullcard/256slightfill/CardHeartHollow.png';
import CardSpadeFilled from './images/cardgame/fullcard/256slightfill/CardSpadeFilled.png';
import CardSpadeHollow from './images/cardgame/fullcard/256slightfill/CardSpadeHollow.png';
import ClubWithCirclesFilled from './images/cardgame/with-circles/256/ClubWithCirclesFilled.png';
import ClubWithCirclesHollow from './images/cardgame/with-circles/256/ClubWithCirclesHollow.png';
import DiamondWithCirclesFilled from './images/cardgame/with-circles/256/DiamondWithCirclesFilled.png';
import DiamondWithCirclesHollow from './images/cardgame/with-circles/256/DiamondWithCirclesHollow.png';
import HeartWithCirclesFilled from './images/cardgame/with-circles/256/HeartWithCirclesFilled.png';
import HeartWithCirclesHollow from './images/cardgame/with-circles/256/HeartWithCirclesHollow.png';
import SpadeWithCirclesFilled from './images/cardgame/with-circles/256/SpadeWithCirclesFilled.png';
import SpadeWithCirclesHollow from './images/cardgame/with-circles/256/SpadeWithCirclesHollow.png';

export const cardGameBgImageUrl = CardGameBg;
export const cardGameMlogoImageUrl = CardGameMlogo;
export const cardGameBackCardImageUrl = CardGameBackCard;
export const cardGameClubFilledImageUrl = CardClubFilled;
export const cardGameClubHollowImageUrl = CardClubHollow;
export const cardGameDiamondFilledImageUrl = CardDiamondFilled;
export const cardGameDiamondHollowImageUrl = CardDiamondHollow;
export const cardGameHeartFilledImageUrl = CardHeartFilled;
export const cardGameHeartHollowImageUrl = CardHeartHollow;
export const cardGameSpadeFilledImageUrl = CardSpadeFilled;
export const cardGameSpadeHollowImageUrl = CardSpadeHollow;
export const cardGameClubWithCirclesFilledImageUrl = ClubWithCirclesFilled;
export const cardGameClubWithCirclesHollowImageUrl = ClubWithCirclesHollow;
export const cardGameDiamondWithCirclesFilledImageUrl = DiamondWithCirclesFilled;
export const cardGameDiamondWithCirclesHollowImageUrl = DiamondWithCirclesHollow;
export const cardGameHeartWithCirclesFilledImageUrl = HeartWithCirclesFilled;
export const cardGameHeartWithCirclesHollowImageUrl = HeartWithCirclesHollow;
export const cardGameSpadeWithCirclesFilledImageUrl = SpadeWithCirclesFilled;
export const cardGameSpadeWithCirclesHollowImageUrl = SpadeWithCirclesHollow;
