// Auto-generated LOD texture imports
// This file is automatically generated by scripts/generateLODTextures.js

import SpadeWithCirclesFilledOriginal from '@/assets/BgCards/with circles/SpadeWithCirclesFilled.png';
import SpadeWithCirclesFilledHalf from '@/assets/BgCards/with circles/LOD/SpadeWithCirclesFilled_half.png';
import SpadeWithCirclesFilledQuarter from '@/assets/BgCards/with circles/LOD/SpadeWithCirclesFilled_quarter.png';
import SpadeWithCirclesFilledEighth from '@/assets/BgCards/with circles/LOD/SpadeWithCirclesFilled_eighth.png';
import SpadeWithCirclesHollowOriginal from '@/assets/BgCards/with circles/SpadeWithCirclesHollow.png';
import SpadeWithCirclesHollowHalf from '@/assets/BgCards/with circles/LOD/SpadeWithCirclesHollow_half.png';
import SpadeWithCirclesHollowQuarter from '@/assets/BgCards/with circles/LOD/SpadeWithCirclesHollow_quarter.png';
import SpadeWithCirclesHollowEighth from '@/assets/BgCards/with circles/LOD/SpadeWithCirclesHollow_eighth.png';
import HeartWithCirclesFilledOriginal from '@/assets/BgCards/with circles/HeartWithCirclesFilled.png';
import HeartWithCirclesFilledHalf from '@/assets/BgCards/with circles/LOD/HeartWithCirclesFilled_half.png';
import HeartWithCirclesFilledQuarter from '@/assets/BgCards/with circles/LOD/HeartWithCirclesFilled_quarter.png';
import HeartWithCirclesFilledEighth from '@/assets/BgCards/with circles/LOD/HeartWithCirclesFilled_eighth.png';
import HeartWithCirclesHollowOriginal from '@/assets/BgCards/with circles/HeartWithCirclesHollow.png';
import HeartWithCirclesHollowHalf from '@/assets/BgCards/with circles/LOD/HeartWithCirclesHollow_half.png';
import HeartWithCirclesHollowQuarter from '@/assets/BgCards/with circles/LOD/HeartWithCirclesHollow_quarter.png';
import HeartWithCirclesHollowEighth from '@/assets/BgCards/with circles/LOD/HeartWithCirclesHollow_eighth.png';
import DiamondWithCirclesFilledOriginal from '@/assets/BgCards/with circles/DiamondWithCirclesFilled.png';
import DiamondWithCirclesFilledHalf from '@/assets/BgCards/with circles/LOD/DiamondWithCirclesFilled_half.png';
import DiamondWithCirclesFilledQuarter from '@/assets/BgCards/with circles/LOD/DiamondWithCirclesFilled_quarter.png';
import DiamondWithCirclesFilledEighth from '@/assets/BgCards/with circles/LOD/DiamondWithCirclesFilled_eighth.png';
import DiamondWithCirclesHollowOriginal from '@/assets/BgCards/with circles/DiamondWithCirclesHollow.png';
import DiamondWithCirclesHollowHalf from '@/assets/BgCards/with circles/LOD/DiamondWithCirclesHollow_half.png';
import DiamondWithCirclesHollowQuarter from '@/assets/BgCards/with circles/LOD/DiamondWithCirclesHollow_quarter.png';
import DiamondWithCirclesHollowEighth from '@/assets/BgCards/with circles/LOD/DiamondWithCirclesHollow_eighth.png';
import ClubWithCirclesFilledOriginal from '@/assets/BgCards/with circles/ClubWithCirclesFilled.png';
import ClubWithCirclesFilledHalf from '@/assets/BgCards/with circles/LOD/ClubWithCirclesFilled_half.png';
import ClubWithCirclesFilledQuarter from '@/assets/BgCards/with circles/LOD/ClubWithCirclesFilled_quarter.png';
import ClubWithCirclesFilledEighth from '@/assets/BgCards/with circles/LOD/ClubWithCirclesFilled_eighth.png';
import ClubWithCirclesHollowOriginal from '@/assets/BgCards/with circles/ClubWithCirclesHollow.png';
import ClubWithCirclesHollowHalf from '@/assets/BgCards/with circles/LOD/ClubWithCirclesHollow_half.png';
import ClubWithCirclesHollowQuarter from '@/assets/BgCards/with circles/LOD/ClubWithCirclesHollow_quarter.png';
import ClubWithCirclesHollowEighth from '@/assets/BgCards/with circles/LOD/ClubWithCirclesHollow_eighth.png';

// Export LOD textures organized by card type
export const LOD_CARD_ASSETS = {
  WithCircles: {
    Spade: {
      filled: {
        original: SpadeWithCirclesFilledOriginal,
        half: SpadeWithCirclesFilledHalf,
        quarter: SpadeWithCirclesFilledQuarter,
        eighth: SpadeWithCirclesFilledEighth
      },
      hollow: {
        original: SpadeWithCirclesHollowOriginal,
        half: SpadeWithCirclesHollowHalf,
        quarter: SpadeWithCirclesHollowQuarter,
        eighth: SpadeWithCirclesHollowEighth
      },
    },
    Heart: {
      filled: {
        original: HeartWithCirclesFilledOriginal,
        half: HeartWithCirclesFilledHalf,
        quarter: HeartWithCirclesFilledQuarter,
        eighth: HeartWithCirclesFilledEighth
      },
      hollow: {
        original: HeartWithCirclesHollowOriginal,
        half: HeartWithCirclesHollowHalf,
        quarter: HeartWithCirclesHollowQuarter,
        eighth: HeartWithCirclesHollowEighth
      },
    },
    Diamond: {
      filled: {
        original: DiamondWithCirclesFilledOriginal,
        half: DiamondWithCirclesFilledHalf,
        quarter: DiamondWithCirclesFilledQuarter,
        eighth: DiamondWithCirclesFilledEighth
      },
      hollow: {
        original: DiamondWithCirclesHollowOriginal,
        half: DiamondWithCirclesHollowHalf,
        quarter: DiamondWithCirclesHollowQuarter,
        eighth: DiamondWithCirclesHollowEighth
      },
    },
    Club: {
      filled: {
        original: ClubWithCirclesFilledOriginal,
        half: ClubWithCirclesFilledHalf,
        quarter: ClubWithCirclesFilledQuarter,
        eighth: ClubWithCirclesFilledEighth
      },
      hollow: {
        original: ClubWithCirclesHollowOriginal,
        half: ClubWithCirclesHollowHalf,
        quarter: ClubWithCirclesHollowQuarter,
        eighth: ClubWithCirclesHollowEighth
      },
    },
  }
};