export interface GamesCatalogSvgLayoutControls {
  outerInset: number;
  topBarInsetX: number;
  topBarTopInset: number;
  topBarHeight: number;
  toolbarButtonHeight: number;
  searchWidth: number;
  statsBoxWidth: number;
  defaultSidebarWidth: number;
  minSidebarWidth: number;
  maxSidebarWidth: number;
  sidebarHeaderHeight: number;
  playerModeRowHeight: number;
  categoryRowHeight: number;
  subcategoryRowHeight: number;
  gamesAreaPadding: number;
  cardGap: number;
  cardTopClearance: number;
  minCardWidthPx: number;
  maxCardWidthPx: number;
  maxGridColumns: number;
  cardHeight: number;
  cardPadding: number;
  cardImageHeight: number;
  cardRadius: number;
  cardTitleFont: number;
  cardDescriptionFont: number;
  cardMetaPillHeight: number;
  cardMetaGap: number;
  detailPanelWidth: number;
  detailPanelHeight: number;
  topBarFillOpacity: number;
  topBarStrokeWidth: number;
  topBarBackdropBlur: number;
  controlFillOpacity: number;
  controlStrokeWidth: number;
  controlGlowBlur: number;
  controlGlowOpacity: number;
  sidebarFillOpacity: number;
  sidebarStrokeWidth: number;
  sidebarHeaderFillOpacity: number;
  sidebarRowFillOpacity: number;
  sidebarRowActiveFillOpacity: number;
  sidebarBackdropBlur: number;
  gamesAreaFillOpacity: number;
  gamesAreaStrokeWidth: number;
  gamesAreaBackdropBlur: number;
  cardFillOpacity: number;
  cardStrokeWidth: number;
  cardRingStrokeWidth: number;
  cardRingOpacity: number;
  cardGlowBlur: number;
  cardGlowOpacity: number;
  cardBackdropBlur: number;
  cardImageOverlayOpacity: number;
  cardImageCurveOpacity: number;
  cardCategoryBadgeOpacity: number;
  cardMetaFillOpacity: number;
  cardTopClampHeight: number;
  cardTopClampFillOpacity: number;
  cardTopClampStrokeWidth: number;
  detailOverlayOpacity: number;
  detailPanelFillOpacity: number;
  detailPanelStrokeWidth: number;
  detailHeaderFillOpacity: number;
  detailCardFillOpacity: number;
  detailBackdropBlur: number;
  debugBoundsStrokeWidth: number;
  debugBoundsFillOpacity: number;
  topBarFillColor: string;
  topBarStrokeColor: string;
  controlFillColor: string;
  controlStrokeColor: string;
  controlGlowColor: string;
  activeControlStartColor: string;
  activeControlEndColor: string;
  sidebarFillColor: string;
  sidebarStrokeColor: string;
  sidebarHeaderFillColor: string;
  sidebarDividerColor: string;
  sidebarRowFillColor: string;
  sidebarRowActiveFillColor: string;
  gamesAreaFillColor: string;
  gamesAreaStrokeColor: string;
  cardOuterFillColor: string;
  cardFillColor: string;
  cardStrokeColor: string;
  cardRingColor: string;
  cardGlowColor: string;
  cardEdgeStartColor: string;
  cardEdgeMiddleColor: string;
  cardEdgeEndColor: string;
  cardTextColor: string;
  cardDescriptionColor: string;
  cardImageOverlayColor: string;
  cardCategoryBadgeFillColor: string;
  cardCategoryBadgeStrokeColor: string;
  cardMetaFillColor: string;
  cardMetaStrokeColor: string;
  cardTopClampStrokeColor: string;
  detailOverlayColor: string;
  detailPanelFillColor: string;
  detailPanelStrokeColor: string;
  detailHeaderFillColor: string;
  detailCardFillColor: string;
  detailCardStrokeColor: string;
  debugPageBoundsColor: string;
  debugHeaderBoundsColor: string;
  debugSidebarBoundsColor: string;
  debugGamesBoundsColor: string;
  debugCardBoundsColor: string;
  showToolbar: boolean;
  showSearch: boolean;
  showViewButtons: boolean;
  showQualityFilter: boolean;
  showSortFilter: boolean;
  showStats: boolean;
  showSidebar: boolean;
  showPlayerModes: boolean;
  showCategoryList: boolean;
  showCardImages: boolean;
  showCardCategoryBadge: boolean;
  showCardStatusBadge: boolean;
  showCardMeta: boolean;
  showCardTopClamp: boolean;
  enableDetailOverlay: boolean;
  showDetailReadiness: boolean;
  showDetailActions: boolean;
  showDebugBounds: boolean;
  showPageBounds: boolean;
  showHeaderBounds: boolean;
  showSidebarBounds: boolean;
  showGamesAreaBounds: boolean;
  showCardBounds: boolean;
  showDetailBounds: boolean;
}

export const DEFAULT_GAMES_CATALOG_SVG_LAYOUT_CONTROLS: GamesCatalogSvgLayoutControls = {
  outerInset: 18,
  topBarInsetX: 28,
  topBarTopInset: 16,
  topBarHeight: 74,
  toolbarButtonHeight: 38,
  searchWidth: 320,
  statsBoxWidth: 96,
  defaultSidebarWidth: 292,
  minSidebarWidth: 240,
  maxSidebarWidth: 680,
  sidebarHeaderHeight: 52,
  playerModeRowHeight: 56,
  categoryRowHeight: 50,
  subcategoryRowHeight: 30,
  gamesAreaPadding: 20,
  cardGap: 44,
  cardTopClearance: 28,
  minCardWidthPx: 250,
  maxCardWidthPx: 340,
  maxGridColumns: 4,
  cardHeight: 590,
  cardPadding: 14,
  cardImageHeight: 226,
  cardRadius: 18,
  cardTitleFont: 18,
  cardDescriptionFont: 13.5,
  cardMetaPillHeight: 30,
  cardMetaGap: 10,
  detailPanelWidth: 1320,
  detailPanelHeight: 790,
  topBarFillOpacity: 0.56,
  topBarStrokeWidth: 1.15,
  topBarBackdropBlur: 10,
  controlFillOpacity: 1,
  controlStrokeWidth: 1.1,
  controlGlowBlur: 4,
  controlGlowOpacity: 0.56,
  sidebarFillOpacity: 0.68,
  sidebarStrokeWidth: 1.2,
  sidebarHeaderFillOpacity: 0.82,
  sidebarRowFillOpacity: 1,
  sidebarRowActiveFillOpacity: 1,
  sidebarBackdropBlur: 8,
  gamesAreaFillOpacity: 0.22,
  gamesAreaStrokeWidth: 1.2,
  gamesAreaBackdropBlur: 6,
  cardFillOpacity: 0.9,
  cardStrokeWidth: 1.25,
  cardRingStrokeWidth: 1.1,
  cardRingOpacity: 0.28,
  cardGlowBlur: 3,
  cardGlowOpacity: 0.38,
  cardBackdropBlur: 5,
  cardImageOverlayOpacity: 0.32,
  cardImageCurveOpacity: 0.68,
  cardCategoryBadgeOpacity: 0.72,
  cardMetaFillOpacity: 1,
  cardTopClampHeight: 11,
  cardTopClampFillOpacity: 0.42,
  cardTopClampStrokeWidth: 2.2,
  detailOverlayOpacity: 0.58,
  detailPanelFillOpacity: 0.72,
  detailPanelStrokeWidth: 1.7,
  detailHeaderFillOpacity: 0.76,
  detailCardFillOpacity: 0.9,
  detailBackdropBlur: 8,
  debugBoundsStrokeWidth: 2,
  debugBoundsFillOpacity: 0.08,
  topBarFillColor: '#071b34',
  topBarStrokeColor: '#1ea7ff',
  controlFillColor: '#071026',
  controlStrokeColor: '#55749e',
  controlGlowColor: '#00e7ff',
  activeControlStartColor: '#2b79ff',
  activeControlEndColor: '#633bff',
  sidebarFillColor: '#061a31',
  sidebarStrokeColor: '#1ea7ff',
  sidebarHeaderFillColor: '#081b35',
  sidebarDividerColor: '#6fa8df',
  sidebarRowFillColor: '#061124',
  sidebarRowActiveFillColor: '#2b79ff',
  gamesAreaFillColor: '#061a31',
  gamesAreaStrokeColor: '#1ea7ff',
  cardOuterFillColor: '#071122',
  cardFillColor: '#071426',
  cardStrokeColor: '#23ffd1',
  cardRingColor: '#23ffd1',
  cardGlowColor: '#00ffc6',
  cardEdgeStartColor: '#19ffd1',
  cardEdgeMiddleColor: '#2d8dff',
  cardEdgeEndColor: '#805cff',
  cardTextColor: '#ffffff',
  cardDescriptionColor: '#bdd0e7',
  cardImageOverlayColor: '#020711',
  cardCategoryBadgeFillColor: '#071026',
  cardCategoryBadgeStrokeColor: '#2a3954',
  cardMetaFillColor: '#071026',
  cardMetaStrokeColor: '#55749e',
  cardTopClampStrokeColor: '#aeefff',
  detailOverlayColor: '#000000',
  detailPanelFillColor: '#061a31',
  detailPanelStrokeColor: '#23ffd1',
  detailHeaderFillColor: '#071b34',
  detailCardFillColor: '#071426',
  detailCardStrokeColor: '#345b89',
  debugPageBoundsColor: '#22c55e',
  debugHeaderBoundsColor: '#84cc16',
  debugSidebarBoundsColor: '#facc15',
  debugGamesBoundsColor: '#ef4444',
  debugCardBoundsColor: '#38bdf8',
  showToolbar: true,
  showSearch: true,
  showViewButtons: true,
  showQualityFilter: true,
  showSortFilter: true,
  showStats: true,
  showSidebar: true,
  showPlayerModes: true,
  showCategoryList: true,
  showCardImages: true,
  showCardCategoryBadge: true,
  showCardStatusBadge: true,
  showCardMeta: true,
  showCardTopClamp: true,
  enableDetailOverlay: true,
  showDetailReadiness: true,
  showDetailActions: true,
  showDebugBounds: false,
  showPageBounds: true,
  showHeaderBounds: true,
  showSidebarBounds: true,
  showGamesAreaBounds: true,
  showCardBounds: false,
  showDetailBounds: true,
};
