import type { Product } from './products';

export const DEV_SEED_PRODUCTS: Product[] = [
  {
    productType: 'AC_CREDITS',
    productId: 'ac-100',
    stripePriceId: 'price_placeholder_ac_100',
    displayName: '100 Arena Credits',
    description: 'Starter refill for AI review, cosmetics, and event access.',
    shopTab: 'Treasury',
    badge: 'Starter',
    benefits: ['AI analysis fuel', 'Vault purchases', 'Event-ready balance'],
    entitlementKind: 'credits',
    availability: 'live',
    acAmount: 100,
    unitPriceCents: 99,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'AC_CREDITS',
    productId: 'ac-500',
    stripePriceId: 'price_placeholder_ac_500',
    displayName: '500 Arena Credits',
    description: 'Core balance pack for regular AI and table economy use.',
    shopTab: 'Treasury',
    badge: 'Popular',
    benefits: ['AI coach allowance', 'Table cosmetics', 'Ticket reserve'],
    entitlementKind: 'credits',
    availability: 'live',
    acAmount: 500,
    unitPriceCents: 499,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'AC_CREDITS',
    productId: 'ac-1200',
    stripePriceId: 'price_placeholder_ac_1200',
    displayName: '1200 Arena Credits',
    description: 'Best value refill for ranked play, AI reviews, and vault drops.',
    shopTab: 'Treasury',
    badge: 'Best Value',
    benefits: ['Replay review buffer', 'Season cosmetics', 'Creator market ready'],
    entitlementKind: 'credits',
    availability: 'live',
    acAmount: 1200,
    unitPriceCents: 999,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'AC_CREDITS',
    productId: 'ac-3500',
    stripePriceId: 'price_placeholder_ac_3500',
    displayName: '3500 Arena Credits',
    description: 'Season supply for power users, hosts, and tournament regulars.',
    shopTab: 'Treasury',
    badge: 'Season Supply',
    benefits: ['Private room reserve', 'Premium AI usage', 'Event and vault balance'],
    entitlementKind: 'credits',
    availability: 'live',
    acAmount: 3500,
    unitPriceCents: 2499,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'SUBSCRIPTION',
    productId: 'sub-arena-pass',
    stripePriceId: 'price_placeholder_sub_arena',
    displayName: 'Arena Pass',
    description: 'Monthly premium lane for regular Ocentra players.',
    shopTab: 'Elite',
    badge: 'Monthly',
    benefits: ['Monthly AI allowance', 'Saved async games', 'Premium table themes'],
    entitlementKind: 'pass',
    availability: 'preview',
    subscriptionTier: 'pro',
    unitPriceCents: 999,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'SUBSCRIPTION',
    productId: 'sub-champions-pass',
    stripePriceId: 'price_placeholder_sub_champion',
    displayName: "Champion's Pass",
    description: 'Competitive pass for hosts, tournament players, and AI-heavy review.',
    shopTab: 'Elite',
    badge: 'Competitive',
    benefits: ['Expanded AI review', 'Private rooms', 'Tournament ticket allowance'],
    entitlementKind: 'pass',
    availability: 'preview',
    subscriptionTier: 'champion',
    unitPriceCents: 1999,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'SUBSCRIPTION',
    productId: 'sub-founder',
    stripePriceId: 'price_placeholder_sub_founder',
    displayName: 'Founder Lifetime',
    description: 'Permanent founder identity and early platform benefits.',
    shopTab: 'Elite',
    badge: 'Limited',
    benefits: ['Founder badge', 'Lifetime profile identity', 'Early feature access'],
    entitlementKind: 'pass',
    availability: 'preview',
    subscriptionTier: 'founder',
    unitPriceCents: 14900,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'MARKETPLACE',
    productId: 'vault-card-back-neon',
    stripePriceId: 'price_placeholder_vault_neon',
    displayName: 'Neon Cyber Deck',
    description: 'Animated-feel cyber card-back identity for competitive tables.',
    shopTab: 'Vault',
    badge: 'Limited',
    benefits: ['Card back cosmetic', 'Profile vault item', 'Equippable identity'],
    entitlementKind: 'cosmetic',
    availability: 'preview',
    acPrice: 200,
    priceLabel: '200 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'MARKETPLACE',
    productId: 'vault-card-back-royal',
    stripePriceId: 'price_placeholder_vault_royal',
    displayName: 'Royal Velvet Backs',
    description: 'Classic premium card-back set for formal tables.',
    shopTab: 'Vault',
    badge: 'Classic',
    benefits: ['Card back cosmetic', 'Vault collection', 'Equippable table identity'],
    entitlementKind: 'cosmetic',
    availability: 'preview',
    acPrice: 150,
    priceLabel: '150 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'MARKETPLACE',
    productId: 'vault-table-classic',
    stripePriceId: 'price_placeholder_vault_table',
    displayName: 'Classic Felt Table',
    description: 'Clean table theme for Claim, trick-taking, and social rooms.',
    shopTab: 'Vault',
    badge: 'Table Theme',
    benefits: ['Table theme', 'Room identity', 'Equippable surface'],
    entitlementKind: 'cosmetic',
    availability: 'preview',
    acPrice: 100,
    priceLabel: '100 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'MARKETPLACE',
    productId: 'access-private-tables',
    stripePriceId: 'price_placeholder_access_private_tables',
    displayName: 'Private Table Hosting',
    description: 'Host invite-only tables with guest links and room controls.',
    shopTab: 'Play Access',
    badge: 'Host',
    benefits: ['Private tables', 'Guest invites', 'Room controls'],
    entitlementKind: 'play_access',
    availability: 'preview',
    acPrice: 300,
    priceLabel: '300 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'MARKETPLACE',
    productId: 'access-club-rooms',
    stripePriceId: 'price_placeholder_access_club_rooms',
    displayName: 'Club Room Kit',
    description: 'Persistent room kit for clubs, friend groups, and league nights.',
    shopTab: 'Play Access',
    badge: 'Club',
    benefits: ['Club rooms', 'Persistent table identity', 'League night setup'],
    entitlementKind: 'play_access',
    availability: 'preview',
    acPrice: 600,
    priceLabel: '600 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'TOURNAMENT_ENTRY',
    productId: 'ticket-claim-weekly',
    stripePriceId: 'price_placeholder_ticket_claim_weekly',
    displayName: 'Weekly Claim Ticket',
    description: 'Entry token for structured Claim weekly events.',
    shopTab: 'Events',
    badge: 'Weekly',
    benefits: ['Claim event entry', 'Season ladder eligible', 'Structured competitive play'],
    entitlementKind: 'event_ticket',
    availability: 'coming_soon',
    acPrice: 250,
    priceLabel: '250 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'TOURNAMENT_ENTRY',
    productId: 'season-ladder-pass',
    stripePriceId: 'price_placeholder_season_ladder',
    displayName: 'Season Ladder Pass',
    description: 'Season reward track and premium competitive queue access.',
    shopTab: 'Events',
    badge: 'Season',
    benefits: ['Reward track', 'Premium queue', 'Season cosmetics'],
    entitlementKind: 'event_ticket',
    availability: 'coming_soon',
    acPrice: 900,
    priceLabel: '900 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'MARKETPLACE',
    productId: 'creator-table-pack-claim-night',
    stripePriceId: 'price_placeholder_creator_claim_night',
    displayName: 'Claim Night Creator Pack',
    description: 'Curated creator table art, badges, and card-back bundle.',
    shopTab: 'Creator Market',
    badge: 'Creator',
    benefits: ['Creator table theme', 'Card-back bundle', 'Profile badge'],
    entitlementKind: 'creator_good',
    availability: 'preview',
    acPrice: 450,
    priceLabel: '450 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
  {
    productType: 'MARKETPLACE',
    productId: 'publisher-pack-classic-cards',
    stripePriceId: 'price_placeholder_publisher_classic_cards',
    displayName: 'Classic Cards Publisher Pack',
    description: 'Publisher-grade cosmetic pack for classic card-game rooms.',
    shopTab: 'Creator Market',
    badge: 'Publisher',
    benefits: ['Publisher skin pack', 'Room art', 'Vault cosmetics'],
    entitlementKind: 'creator_good',
    availability: 'preview',
    acPrice: 700,
    priceLabel: '700 AC',
    unitPriceCents: 0,
    currency: 'usd',
    active: true,
  },
];
