import type { CardGameMechanicsData } from '@/schemas/asset/card-game-mechanics-data.schema';
import type { MechanicsSpec } from '@ocentra/game-domain/engine/mechanics/MechanicsSpec';
import { decodeMechanicsSpec } from '@ocentra/game-domain/schema/mechanics';

export function toMechanicsSpec(data: CardGameMechanicsData): MechanicsSpec {
  return decodeMechanicsSpec({
    gameId: data.gameId,
    mechanicsId: data.mechanicsId,
    mechanicsVersion: data.mechanicsVersion,
    familyKernel: data.familyKernel,
    familyVariant: data.familyVariant,
    kernelVersion: data.kernelVersion,
    inheritsFrom: data.inheritsFrom ?? null,
    enabledModules: data.enabledModules,
    assetRefs: data.assetRefs,
    playerConfig: {
      playerMode: data.playerConfig.playerMode,
      minPlayers: data.playerConfig.minPlayers,
      maxPlayers: data.playerConfig.maxPlayers,
      optimalPlayers: data.playerConfig.optimalPlayers ?? null,
      dealerRotates: data.playerConfig.dealerRotates,
    },
    phases: data.phases.map((phase) => ({
      id: phase.id,
      label: phase.label,
      actor: phase.actor,
      legalActions: phase.legalActions,
      nextPhase: phase.nextPhase,
      isMandatory: phase.isMandatory,
      loopIndex: phase.loopIndex,
      totalLoops: phase.totalLoops,
      conditionalNext: phase.conditionalNext,
      cardVisibilityChanges: phase.cardVisibilityChanges,
      notes: phase.notes,
    })),
    actions: data.actions ?? {},
    customActions: data.customActions,
    zones: data.zones,
    turnPolicy: data.turnPolicy,
    endConditions: data.endConditions,
    cardVisibility: data.cardVisibility,
    drawConfig: data.drawConfig ?? null,
    discardConfig: data.discardConfig ?? null,
    deckType: data.deckType,
    suitSet: data.suitSet,
    rankSet: data.rankSet,
    initialHandSize: data.initialHandSize,
    trumpConfig: data.trumpConfig ?? null,
    meldConfig: data.meldConfig ?? null,
    trickConfig: data.trickConfig ?? null,
    declarationMechanism: data.declarationMechanism ?? null,
    handRanks: data.handRanks ?? null,
    buyCosts: data.buyCosts ?? null,
    marketConfig: data.marketConfig ?? null,
    specialCards: data.specialCards ?? null,
    shedding: data.shedding ?? null,
    fishingConfig: data.fishingConfig ?? null,
    patienceConfig: data.patienceConfig ?? null,
    bankingConfig: data.bankingConfig ?? null,
    roundConfig: data.roundConfig ?? null,
    constants: data.constants,
    familyConfig: data.familyConfig ?? null,
    finalHandSize: data.finalHandSize,
    deckCount: data.deckCount,
    implementationHints: data.implementationHints,
    playerModel: data.playerModel,
    sessionModel: data.sessionModel,
    deckModel: data.deckModel,
    zoneModel: data.zoneModel,
    setupModel: data.setupModel,
    turnModel: data.turnModel,
    actionModel: data.actionModel,
    ruleModel: data.ruleModel,
    scoringModel: data.scoringModel,
    strategyHooks: data.strategyHooks,
    stateModel: data.stateModel,
    eventModel: data.eventModel,
    validationSuites: data.validationSuites,
    runtimeIntegration: data.runtimeIntegration,
    examples: data.examples,
    progression: data.progression,
    roles: data.roles,
    determinismNotes: data.determinismNotes,
  });
}
