import type { CardGameMechanicsData } from '@/schemas/asset/card-game-mechanics-data.schema';
import type { MechanicsSpec } from '@ocentra/game-domain/engine/mechanics/MechanicsSpec';

export function toMechanicsSpec(data: CardGameMechanicsData): MechanicsSpec {
  return {
    familyKernel: data.familyKernel,
    kernelVersion: data.kernelVersion,
    playerConfig: {
      playerMode: data.playerConfig.playerMode,
      minPlayers: data.playerConfig.minPlayers,
      maxPlayers: data.playerConfig.maxPlayers,
      optimalPlayers: data.playerConfig.optimalPlayers ?? null,
      dealerRotates: data.playerConfig.dealerRotates,
    },
    phases: data.phases.map((phase) => ({
      id: phase.id,
      label: phase.label,
      actor: phase.actor,
      legalActions: phase.legalActions,
      nextPhase: phase.nextPhase,
      isMandatory: phase.isMandatory,
      loopIndex: phase.loopIndex,
      totalLoops: phase.totalLoops,
      conditionalNext: phase.conditionalNext,
      cardVisibilityChanges: phase.cardVisibilityChanges,
      notes: phase.notes,
    })),
    actions: data.actions ?? {},
    customActions: data.customActions,
    zones: data.zones,
    turnPolicy: data.turnPolicy,
    endConditions: data.endConditions,
    cardVisibility: data.cardVisibility,
    drawConfig: data.drawConfig ?? null,
    discardConfig: data.discardConfig ?? null,
    deckType: data.deckType,
    suitSet: data.suitSet,
    rankSet: data.rankSet,
    initialHandSize: data.initialHandSize,
    trumpConfig: data.trumpConfig ?? null,
    meldConfig: data.meldConfig ?? null,
    trickConfig: data.trickConfig ?? null,
    declarationMechanism: data.declarationMechanism ?? null,
    handRanks: data.handRanks ?? null,
    buyCosts: data.buyCosts ?? null,
    marketConfig: data.marketConfig ?? null,
    specialCards: data.specialCards ?? null,
    shedding: data.shedding ?? null,
    fishingConfig: data.fishingConfig ?? null,
    patienceConfig: data.patienceConfig ?? null,
    bankingConfig: data.bankingConfig ?? null,
    roundConfig: data.roundConfig ?? null,
    constants: data.constants,
    finalHandSize: data.finalHandSize,
    deckCount: data.deckCount,
    implementationHints: data.implementationHints,
    progression: data.progression,
    roles: data.roles,
    determinismNotes: data.determinismNotes,
  };
}
