// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

import type { AssetTypeMetadata } from '@ocentra/asset-domain/constants/assets';

export const assetTypeMap: Record<string, AssetTypeMetadata> = {
  "AssetResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/AssetResourceEntry",
    "assetType": "AssetResourceEntry",
    "displayName": "Asset Resource Entry",
    "icon": "📄",
    "category": "Content",
    "commonType": "Assets"
  },
  "FileResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/FileResourceEntry",
    "assetType": "FileResourceEntry",
    "displayName": "File Resource Entry",
    "icon": "📁",
    "category": "Content",
    "commonType": "Assets"
  },
  "FolderResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/FolderResourceEntry",
    "assetType": "FolderResourceEntry",
    "displayName": "Folder Resource Entry",
    "icon": "📂",
    "category": "Content",
    "commonType": "Assets"
  },
  "ImageResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/ImageResourceEntry",
    "assetType": "ImageResourceEntry",
    "displayName": "Image Resource Entry",
    "icon": "🖼️",
    "category": "Content",
    "commonType": "Assets"
  },
  "ResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/ResourceEntry",
    "assetType": "ResourceEntry",
    "displayName": "Resource Entry",
    "icon": "📄",
    "category": "Content",
    "commonType": "Assets"
  },
  "SoundResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/SoundResourceEntry",
    "assetType": "SoundResourceEntry",
    "displayName": "Sound Resource Entry",
    "icon": "🔊",
    "category": "Content",
    "commonType": "Assets"
  },
  "VideoResourceEntry": {
    "importPath": "@ocentra/asset-domain/resourceEntry/VideoResourceEntry",
    "assetType": "VideoResourceEntry",
    "displayName": "Video Resource Entry",
    "icon": "🎬",
    "category": "Content",
    "commonType": "Assets"
  },
  "AIModelList": {
    "importPath": "@ocentra/game-asset-domain/ai/aiModelList/AIModelList",
    "assetType": "AIModelList",
    "displayName": "AI Model List",
    "icon": "🤖",
    "category": "AI",
    "commonType": "AI"
  },
  "ModelQuantSettings": {
    "importPath": "@ocentra/game-asset-domain/ai/ModelQuantSettings",
    "assetType": "ModelQuantSettings",
    "displayName": "Model Quant Settings",
    "icon": "⚙️",
    "category": "AI",
    "commonType": "AI"
  },
  "BaseAssetMetadata": {
    "importPath": "@ocentra/game-asset-domain/BaseAssetMetadata",
    "assetType": "BaseAssetMetadata",
    "displayName": "Base Asset Metadata",
    "commonType": "Assets"
  },
  "Card": {
    "importPath": "@ocentra/game-asset-domain/card/cardBase/Card",
    "assetType": "Card",
    "displayName": "Card",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Cards"
  },
  "CardSuitEntry": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardSuitEntry",
    "displayName": "Card Suit Entry",
    "commonType": "Assets"
  },
  "CardRankingEntry": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardRankingEntry",
    "displayName": "Card Ranking Entry",
    "commonType": "Assets"
  },
  "CardRankingExplicitEntry": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardRankingExplicitEntry",
    "displayName": "Card Ranking Explicit Entry",
    "commonType": "Assets"
  },
  "CardRanking": {
    "importPath": "@ocentra/game-asset-domain/card/cardRanking/CardRanking",
    "assetType": "CardRanking",
    "displayName": "Card Ranking",
    "icon": "📊",
    "category": "Game",
    "commonType": "Assets"
  },
  "SupportedDeckTriple": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "SupportedDeckTriple",
    "displayName": "Supported Deck Triple",
    "icon": "ðŸƒ",
    "category": "Game",
    "commonType": "Decks"
  },
  "DeckCardMember": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "DeckCardMember",
    "displayName": "Deck Card Member",
    "icon": "🂠",
    "category": "Game",
    "commonType": "Decks"
  },
  "Deck": {
    "importPath": "@ocentra/game-asset-domain/card/deck/Deck",
    "assetType": "Deck",
    "displayName": "Deck",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Decks"
  },
  "ComingSoon": {
    "importPath": "@ocentra/game-asset-domain/content/comingSoon/ComingSoon",
    "assetType": "ComingSoon",
    "displayName": "Coming Soon",
    "icon": "🎮",
    "category": "UI",
    "commonType": "Assets"
  },
  "FeatureBanner": {
    "importPath": "@ocentra/game-asset-domain/content/featureBanner/FeatureBanner",
    "assetType": "FeatureBanner",
    "displayName": "Feature Banner",
    "icon": "📋",
    "category": "Content",
    "commonType": "Assets"
  },
  "ImageCarousel": {
    "importPath": "@ocentra/game-asset-domain/content/imageCarousel/ImageCarousel",
    "assetType": "ImageCarousel",
    "displayName": "Image Carousel",
    "icon": "🎞️",
    "category": "Content",
    "commonType": "Assets"
  },
  "ImageList": {
    "importPath": "@ocentra/game-asset-domain/content/imageList/ImageList",
    "assetType": "ImageList",
    "displayName": "Image List",
    "icon": "🖼️",
    "category": "Content",
    "commonType": "Assets"
  },
  "CardGameMechanics": {
    "importPath": "@ocentra/game-asset-domain/game/gameMechanics/CardGameMechanics",
    "assetType": "CardGameMechanics",
    "displayName": "Card Game Mechanics",
    "category": "Game",
    "commonType": "Assets"
  },
  "CardGameRules": {
    "importPath": "@ocentra/game-asset-domain/game/gameRules/CardGameRules",
    "assetType": "CardGameRules",
    "displayName": "Card Game Rules",
    "icon": "🃏",
    "category": "Game",
    "commonType": "CardRules"
  },
  "GameRules": {
    "importPath": "@ocentra/game-asset-domain/game/gameRules/GameRules",
    "assetType": "GameRules",
    "displayName": "Game Rules",
    "icon": "📜",
    "category": "Game",
    "commonType": "CardRules"
  },
  "TrumpBonusValues": {
    "importPath": "@ocentra/game-asset-domain/game/gameRules/TrumpBonusValues",
    "assetType": "TrumpBonusValues",
    "displayName": "Trump Bonus Values",
    "commonType": "Assets"
  },
  "BaseBonusRule": {
    "importPath": "@ocentra/game-asset-domain/game/rules/BaseBonusRule",
    "assetType": "BaseBonusRule",
    "displayName": "Base Bonus Rule",
    "icon": "⭐",
    "category": "Game",
    "commonType": "CardRules"
  },
  "BaseRule": {
    "importPath": "@ocentra/game-asset-domain/game/rules/BaseRule",
    "assetType": "BaseRule",
    "displayName": "Base Rule",
    "icon": "📋",
    "category": "Game",
    "commonType": "CardRules"
  },
  "DifferentColorsSequence": {
    "importPath": "@ocentra/game-asset-domain/game/rules/DifferentColorsSequence",
    "assetType": "DifferentColorsSequence",
    "displayName": "Different Colors Sequence",
    "icon": "🎨",
    "category": "Game",
    "commonType": "Assets"
  },
  "FiveOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/FiveOfAKind",
    "assetType": "FiveOfAKind",
    "displayName": "Five Of A Kind",
    "icon": "⭐",
    "category": "Game",
    "commonType": "Assets"
  },
  "Flush": {
    "importPath": "@ocentra/game-asset-domain/game/rules/Flush",
    "assetType": "Flush",
    "displayName": "Flush",
    "icon": "💎",
    "category": "Game",
    "commonType": "Assets"
  },
  "FourOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/FourOfAKind",
    "assetType": "FourOfAKind",
    "displayName": "Four Of A Kind",
    "icon": "🎯",
    "category": "Game",
    "commonType": "Assets"
  },
  "FullHouse": {
    "importPath": "@ocentra/game-asset-domain/game/rules/FullHouse",
    "assetType": "FullHouse",
    "displayName": "Full House",
    "icon": "🏠",
    "category": "Game",
    "commonType": "Assets"
  },
  "HighCard": {
    "importPath": "@ocentra/game-asset-domain/game/rules/HighCard",
    "assetType": "HighCard",
    "displayName": "High Card",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Assets"
  },
  "MultipleFourOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/MultipleFourOfAKind",
    "assetType": "MultipleFourOfAKind",
    "displayName": "Multiple Four Of A Kind",
    "icon": "🎯🎯",
    "category": "Game",
    "commonType": "Assets"
  },
  "MultiplePairs": {
    "importPath": "@ocentra/game-asset-domain/game/rules/MultiplePairs",
    "assetType": "MultiplePairs",
    "displayName": "Multiple Pairs",
    "icon": "👥👥",
    "category": "Game",
    "commonType": "Assets"
  },
  "MultipleTriplets": {
    "importPath": "@ocentra/game-asset-domain/game/rules/MultipleTriplets",
    "assetType": "MultipleTriplets",
    "displayName": "Multiple Triplets",
    "icon": "🎲🎲",
    "category": "Game",
    "commonType": "Assets"
  },
  "PairRule": {
    "importPath": "@ocentra/game-asset-domain/game/rules/PairRule",
    "assetType": "PairRule",
    "displayName": "Pair Rule",
    "icon": "👥",
    "category": "Game",
    "commonType": "CardRules"
  },
  "RoyalFlush": {
    "importPath": "@ocentra/game-asset-domain/game/rules/RoyalFlush",
    "assetType": "RoyalFlush",
    "displayName": "Royal Flush",
    "icon": "👑",
    "category": "Game",
    "commonType": "Assets"
  },
  "SameColorsSequence": {
    "importPath": "@ocentra/game-asset-domain/game/rules/SameColorsSequence",
    "assetType": "SameColorsSequence",
    "displayName": "Same Colors Sequence",
    "icon": "🌈",
    "category": "Game",
    "commonType": "Assets"
  },
  "StraightFlush": {
    "importPath": "@ocentra/game-asset-domain/game/rules/StraightFlush",
    "assetType": "StraightFlush",
    "displayName": "Straight Flush",
    "icon": "🔥",
    "category": "Game",
    "commonType": "Assets"
  },
  "ThreeOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/ThreeOfAKind",
    "assetType": "ThreeOfAKind",
    "displayName": "Three Of A Kind",
    "icon": "🎲",
    "category": "Game",
    "commonType": "Assets"
  },
  "TrumpOfAKind": {
    "importPath": "@ocentra/game-asset-domain/game/rules/TrumpOfAKind",
    "assetType": "TrumpOfAKind",
    "displayName": "Trump Of A Kind",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Assets"
  },
  "CardGameScoring": {
    "importPath": "@ocentra/game-asset-domain/game/scoring/CardGameScoring",
    "assetType": "CardGameScoring",
    "displayName": "Card Game Scoring",
    "icon": "🎯",
    "category": "Game",
    "commonType": "Scoring"
  },
  "Scoring": {
    "importPath": "@ocentra/game-asset-domain/game/scoring/Scoring",
    "assetType": "Scoring",
    "displayName": "Scoring",
    "icon": "🎯",
    "category": "Game",
    "commonType": "Scoring"
  },
  "Strategy": {
    "importPath": "@ocentra/game-asset-domain/game/strategy/Strategy",
    "assetType": "Strategy",
    "displayName": "Strategy",
    "icon": "💡",
    "category": "Game",
    "commonType": "Strategy"
  },
  "CardGameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/cardGameMode/CardGameMode",
    "assetType": "CardGameMode",
    "displayName": "Card Game Mode",
    "icon": "🃏",
    "category": "Game",
    "commonType": "Assets"
  },
  "BettingGameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/core/BettingGameMode",
    "assetType": "BettingGameMode",
    "displayName": "Betting Game Mode",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/core/GameMode",
    "assetType": "GameMode",
    "displayName": "Game Mode",
    "category": "Game",
    "commonType": "Assets"
  },
  "TurnBasedGameMode": {
    "importPath": "@ocentra/game-asset-domain/gameMode/core/TurnBasedGameMode",
    "assetType": "TurnBasedGameMode",
    "displayName": "Turn Based Game Mode",
    "category": "Game",
    "commonType": "Assets"
  },
  "GameRulesContainer": {
    "importPath": "@ocentra/game-asset-domain/gameMode/types/GameRulesContainer",
    "assetType": "GameRulesContainer",
    "displayName": "Game Rules Container",
    "commonType": "CardRules"
  },
  "CardGameLayout": {
    "importPath": "@ocentra/game-asset-domain/ui/layout/CardGameLayout",
    "assetType": "CardGameLayout",
    "displayName": "Card Game Layout",
    "icon": "🎏",
    "category": "UI",
    "commonType": "Assets"
  },
  "Layout": {
    "importPath": "@ocentra/game-asset-domain/ui/layout/Layout",
    "assetType": "Layout",
    "displayName": "Layout",
    "icon": "📐",
    "category": "UI",
    "commonType": "Assets"
  },
  "UIComponent": {
    "importPath": "@ocentra/game-asset-domain/ui/UIComponent",
    "assetType": "UIComponent",
    "displayName": "UI Component",
    "icon": "🎨",
    "category": "UI",
    "commonType": "Assets"
  }
};
