// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

export const fieldTypeMap: Record<string, Record<string, string>> = {
  "AssetResourceEntry": {
    "guid": "AssetGUIDType",
    "assetType": "AssetType",
    "inheritanceChain": "string[] | null",
    "variant": "string | null"
  },
  "FileResourceEntry": {
    "fileType": "String"
  },
  "ImageResourceEntry": {
    "hash": "ImageHash"
  },
  "ResourceEntry": {
    "path": "String",
    "displayName": "String",
    "gameId": "GameId | null",
    "category": "AssetCategory | null",
    "mimeType": "MimeType | null",
    "fileSize": "number | null",
    "createdAt": "Timestamp | null",
    "updatedAt": "Timestamp | null",
    "lastScanAt": "Timestamp | null",
    "checksum": "AssetChecksum | null"
  },
  "SoundResourceEntry": {
    "hash": "SoundHash"
  },
  "VideoResourceEntry": {
    "hash": "VideoHash"
  },
  "AIModelList": {
    "name": "String",
    "description": "String",
    "models": "Array",
    "defaultModelId": "String",
    "defaultQuantPath": "String"
  },
  "ModelQuantSettings": {
    "modelId": "String",
    "quantPath": "String",
    "displayName": "String",
    "description": "String",
    "settings": "InferenceSettings"
  },
  "BaseAssetMetadata": {
    "typeCategory": "AssetTypeCategory | null",
    "tags": "Array",
    "status": "AssetStatus | null",
    "createdAt": "String",
    "updatedAt": "String",
    "guid": "String"
  },
  "Card": {
    "cardIdentity": "CardIdentity",
    "imageHash": "ImageHash",
    "cardId": "String",
    "rankingAsset": "AssetResourceEntry<DeckRanking>",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "CardSuitEntry": {
    "SuitName": "String",
    "SuitSymbol": "String",
    "SuitColor": "SuitColor",
    "DisplayOrder": "Number"
  },
  "CardRankingEntry": {
    "CardName": "String",
    "Value": "Number",
    "CardSymbol": "String",
    "DisplayOrder": "Number"
  },
  "CardRankingExplicitEntry": {
    "id": "String",
    "copies": "Number",
    "suit": "string | null",
    "rank": "string | number | null",
    "label": "string | null",
    "order": "number | null",
    "points": "number | null",
    "kind": "string | null"
  },
  "CardRanking": {
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "deckFamily": "DeckFamily",
    "cardEntries": "Array",
    "familyPayload": "Array",
    "cardIdentities": "Array"
  },
  "SupportedDeckTriple": {
    "deckType": "String",
    "suitSet": "String",
    "rankSet": "String"
  },
  "DeckCardMember": {
    "cardTemplate": "AssetResourceEntry<Card>",
    "copies": "Number"
  },
  "DeckPieceMember": {
    "pieceTemplate": "AssetResourceEntry<ScriptableObject>",
    "copies": "Number",
    "logicalId": "String",
    "role": "String",
    "tags": "Array"
  },
  "DeckPresentation": {
    "backImageHash": "ImageHash",
    "previewLayoutHint": "String",
    "defaultOrientation": "'portrait' | 'landscape' | 'square'",
    "defaultShape": "String"
  },
  "DeckRuntimePolicy": {
    "shufflePolicy": "String",
    "drawDirection": "String",
    "multiplicity": "Number",
    "visibilityDefaults": "Record<string, unknown>"
  },
  "Deck": {
    "name": "String",
    "deckFamily": "String",
    "pieceKind": "String",
    "supportedTriples": "Array",
    "composition": "Array",
    "rankingAsset": "AssetResourceEntry<DeckRanking>",
    "presentation": "DeckPresentationRecord",
    "runtimePolicy": "DeckRuntimePolicyRecord",
    "cardTemplates": "Array",
    "cardComposition": "Array",
    "backCardHash": "ImageHash",
    "imageSourceFolderPath": "String",
    "cardOutputPath": "String",
    "backCardSourceFolderPath": "String",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "ImageCarousel": {
    "slides": "Array",
    "autoplayIntervalMs": "Number",
    "lastImageDurationMs": "Number",
    "fastRotationDurationMs": "Number",
    "defaultRotationDurationMs": "Number",
    "fastRotationThreshold": "Number",
    "slideTransitionDelayMs": "Number",
    "playbackMode": "BannerPlaybackModeValue",
    "transitionType": "BannerTransitionTypeValue",
    "transitionDurationMs": "Number",
    "logoImageHash": "ImageHash",
    "logoAlt": "String",
    "logoStartMs": "Number",
    "logoDurationMs": "Number",
    "logoScaleFrom": "Number",
    "logoScaleTo": "Number",
    "logoOpacityFrom": "Number",
    "logoOpacityTo": "Number",
    "logoVisibleFromIndex": "Number",
    "logoVisibleToIndex": "Number",
    "titleText": "String",
    "titleTextColor": "String",
    "titleTextStartMs": "Number",
    "titleTextDurationMs": "Number",
    "titleTextScaleFrom": "Number",
    "titleTextScaleTo": "Number",
    "titleTextOpacityFrom": "Number",
    "titleTextOpacityTo": "Number",
    "titleTextVisibleFromIndex": "Number",
    "titleTextVisibleToIndex": "Number",
    "overlayTintColor": "String",
    "overlayTintOpacity": "Number",
    "vignetteOpacity": "Number",
    "fadeToBlackOpacity": "Number"
  },
  "ImageList": {
    "images": "Array"
  },
  "DeckRankingAxisEntry": {
    "key": "String",
    "label": "String",
    "symbol": "String",
    "icon": "String",
    "imageHash": "String",
    "imagePath": "String",
    "color": "String",
    "order": "Number"
  },
  "DeckRankingLayoutCell": {
    "pieceId": "String",
    "rowKey": "String",
    "columnKey": "String"
  },
  "DeckRankingLayoutSection": {
    "id": "String",
    "title": "String",
    "kind": "'matrix' | 'grid'",
    "rows": "Array",
    "columns": "Array",
    "pieceIds": "Array",
    "cells": "Array"
  },
  "DeckRanking": {
    "rankingFamily": "DeckRankingFamily",
    "expectedPieceCount": "Number",
    "layout": "Array",
    "order": "Array",
    "scoringHints": "Record<string, unknown>",
    "legacyPayload": "Record<string, unknown>"
  },
  "DominoDeckTileMember": {
    "tileTemplate": "AssetResourceEntry<DominoTile>",
    "copies": "Number",
    "logicalTileId": "String"
  },
  "DominoDeck": {
    "name": "String",
    "supportedTriples": "Array",
    "tileTemplates": "Array",
    "tileComposition": "Array",
    "dominoRankingAsset": "AssetResourceEntry<DominoRanking>"
  },
  "DominoRanking": {
    "maxPip": "Number",
    "expectedTileCount": "Number",
    "tileIds": "Array"
  },
  "DominoTile": {
    "pieceKind": "PieceKind",
    "leftPips": "Number",
    "rightPips": "Number",
    "tileId": "String",
    "imageHash": "ImageHash",
    "imagePath": "String"
  },
  "CardGameMechanics": {
    "cardVisibility": "Record<string, unknown>",
    "drawConfig": "Record<string, unknown> | null",
    "discardConfig": "Record<string, unknown> | null",
    "deckType": "String",
    "suitSet": "String",
    "rankSet": "String",
    "initialHandSize": "Number",
    "trumpConfig": "Record<string, unknown> | null",
    "meldConfig": "Record<string, unknown> | null",
    "trickConfig": "Record<string, unknown> | null",
    "declarationMechanism": "Record<string, unknown> | null",
    "handRanks": "Record<string, unknown> | null",
    "buyCosts": "Record<string, unknown> | null",
    "marketConfig": "Record<string, unknown> | null",
    "specialCards": "Record<string, unknown> | null",
    "shedding": "Record<string, unknown> | null",
    "fishingConfig": "Record<string, unknown> | null",
    "patienceConfig": "Record<string, unknown> | null",
    "deckModel": "Record<string, unknown>",
    "deckCount": "Number"
  },
  "GameMechanics": {
    "gameId": "String",
    "mechanicsId": "String",
    "mechanicsVersion": "String",
    "familyKernel": "String",
    "familyVariant": "String",
    "kernelVersion": "String",
    "inheritsFrom": "string | null",
    "enabledModules": "Array",
    "assetRefs": "Record<string, MechanicsAssetReference>",
    "modelRefs": "Record<string, MechanicsAssetReference>",
    "constants": "Record<string, unknown>",
    "familyConfig": "Record<string, unknown> | null",
    "implementationHints": "MechanicsImplementationHints",
    "ruleModel": "Record<string, unknown>",
    "scoringModel": "Record<string, unknown>",
    "strategyHooks": "Record<string, unknown>",
    "stateModel": "Record<string, unknown>",
    "eventModel": "Record<string, unknown>",
    "validationSuites": "Array",
    "runtimeIntegration": "MechanicsRuntimeIntegration",
    "examples": "Array",
    "roles": "Array",
    "determinismNotes": "String"
  },
  "TurnBasedGameMechanics": {
    "playerConfig": "MechanicsPlayerConfig",
    "phases": "Array",
    "actions": "Record<string, MechanicsAction>",
    "customActions": "Array",
    "zones": "Array",
    "turnPolicy": "MechanicsTurnPolicy",
    "endConditions": "Array",
    "bankingConfig": "Record<string, unknown> | null",
    "roundConfig": "Record<string, unknown> | null",
    "finalHandSize": "Number",
    "playerModel": "Record<string, unknown>",
    "sessionModel": "Record<string, unknown>",
    "zoneModel": "Record<string, unknown>",
    "setupModel": "Record<string, unknown>",
    "turnModel": "Record<string, unknown>",
    "actionModel": "Record<string, unknown>",
    "progression": "Array"
  },
  "GamePlayerModel": {
    "playerConfig": "MechanicsPlayerConfig",
    "playerModel": "Record<string, unknown>"
  },
  "GameSessionModel": {
    "sessionModel": "Record<string, unknown>",
    "bankingConfig": "Record<string, unknown> | null",
    "roundConfig": "Record<string, unknown> | null",
    "endConditions": "Array"
  },
  "CardGameDeckModel": {
    "deckType": "String",
    "suitSet": "String",
    "rankSet": "String",
    "deckCount": "Number",
    "initialHandSize": "Number",
    "drawConfig": "Record<string, unknown>",
    "discardConfig": "Record<string, unknown>",
    "deckModel": "Record<string, unknown>",
    "handRanks": "Record<string, unknown>",
    "specialCards": "Record<string, unknown>"
  },
  "GameZoneModel": {
    "zones": "Array",
    "zoneModel": "Record<string, unknown>",
    "cardVisibility": "Record<string, unknown>"
  },
  "GamePhaseFlowModel": {
    "phases": "Array",
    "turnPolicy": "MechanicsTurnPolicy",
    "setupModel": "Record<string, unknown>",
    "turnModel": "Record<string, unknown>",
    "runtimeIntegration": "Record<string, unknown>",
    "progression": "Array"
  },
  "GameActionSet": {
    "actionModel": "Record<string, unknown>",
    "actions": "Record<string, MechanicsAction>",
    "customActions": "Array"
  },
  "GameStateEventModel": {
    "stateModel": "Record<string, unknown>",
    "eventModel": "Record<string, unknown>"
  },
  "GameValidationFixtures": {
    "validationSuites": "Array"
  },
  "CardGameRules": {
    "bonusRuleGuids": "Array",
    "useTrump": "Boolean",
    "trumpBonusValues": "TrumpBonusValues"
  },
  "GameRules": {
    "LLM": "String",
    "Player": "String",
    "objective": "String",
    "gameplay": "String",
    "keyRules": "Array",
    "moveValidityConditions": "Record<string, string> | null",
    "exampleHands": "Array",
    "bonusRules": "String"
  },
  "TrumpBonusValues": {
    "cardInMiddleBonus": "Number",
    "fiveOfKindBonus": "Number",
    "flushBonus": "Number",
    "fourOfKindBonus": "Number",
    "threeOfKindBonus": "Number",
    "pairBonus": "Number",
    "trumpCardBonus": "Number",
    "wildCardBonus": "Number",
    "rankAdjacentBonus": "Number"
  },
  "DifferentColorsSequence": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FiveOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "Flush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FourOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FullHouse": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "HighCard": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultipleFourOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultiplePairs": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultipleTriplets": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "PairRule": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "RoyalFlush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "SameColorsSequence": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "StraightFlush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "ThreeOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "TrumpOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "CardGameScoring": {
    "scoringType": "ScoringType",
    "patternMultipliers": "Record<string, number> | null",
    "priorityOrder": "Array",
    "winCondition": "String",
    "cardValues": "Record<string, number>",
    "penalties": "String",
    "targetScore": "number | null",
    "scoringDirection": "ScoringDirection"
  },
  "Scoring": {
    "rankingAsset": "AssetReference | string | null",
    "cardRankingAsset": "AssetReference | string | null",
    "scoringFormula": "String",
    "scoringRules": "Record<string, unknown> | null",
    "description": "String"
  },
  "Strategy": {
    "LLM": "String",
    "Player": "String",
    "basic": "String",
    "intermediate": "String",
    "advanced": "String",
    "tips": "Array",
    "aggressiveness": "Number",
    "riskTolerance": "Number",
    "bluffFrequency": "Number",
    "bluffSettings": "Record<string, string>"
  },
  "CardGameMode": {
    "baseBet": "Number",
    "initialNumberOfCards": "Number",
    "maxNumberOfCards": "Number",
    "minDecks": "Number",
    "maxDecks": "Number",
    "scoringAsset": "AssetResourceEntry<CardGameScoring>",
    "gameRulesAsset": "AssetResourceEntry<CardGameRules>",
    "strategyAsset": "AssetResourceEntry<Strategy>",
    "gameInfoAsset": "AssetResourceEntry<GameInfo>",
    "deckAsset": "AssetResourceEntry<Deck>",
    "rankingAsset": "AssetResourceEntry<DeckRanking>",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>",
    "layoutAsset": "AssetResourceEntry<CardGameLayout>",
    "selectedGameLayoutAsset": "AssetResourceEntry<PageLayout>",
    "lobbyLayoutAsset": "AssetResourceEntry<PageLayout>",
    "carouselImagesAsset": "AssetResourceEntry<ImageCarousel>",
    "mechanicsAsset": "AssetResourceEntry<CardGameMechanics>",
    "minPlayers": "Number",
    "maxPlayers": "Number",
    "minHumanPlayers": "Number",
    "maxHumanPlayers": "Number",
    "supportsAI": "Boolean",
    "aiCountsAsPlayer": "Boolean",
    "useTrump": "Boolean",
    "trumpBonusValues": "TrumpBonusValues"
  },
  "BettingGameMode": {
    "initialPlayerCoins": "Number"
  },
  "GameMode": {
    "releaseStatus": "GameModeStatus",
    "bannerImage": "ImageHash",
    "gameIcon": "ImageHash"
  },
  "TurnBasedGameMode": {
    "minRounds": "Number",
    "maxRounds": "number | null",
    "turnDuration": "Number"
  },
  "GameRulesContainer": {
    "LLM": "String",
    "Player": "String"
  },
  "HanafudaCard": {
    "pieceKind": "PieceKind",
    "month": "Number",
    "slot": "Number",
    "group": "HanafudaGroup",
    "points": "Number",
    "cardId": "String",
    "imageHash": "ImageHash"
  },
  "HanafudaDeck": {
    "name": "String",
    "supportedTriples": "Array",
    "cardTemplates": "Array",
    "hanafudaRankingAsset": "AssetResourceEntry<HanafudaRanking>"
  },
  "HanafudaRankingSlot": {
    "slot": "Number",
    "cardId": "String"
  },
  "HanafudaRankingMonth": {
    "month": "Number",
    "slots": "Array"
  },
  "HanafudaRanking": {
    "expectedCardCount": "Number",
    "months": "Array"
  },
  "MahjongDeckTileMember": {
    "tile": "AssetResourceEntry<MahjongTile>",
    "count": "Number"
  },
  "MahjongDeck": {
    "name": "String",
    "supportedTriples": "Array",
    "tiles": "Array",
    "mahjongRankingAsset": "AssetResourceEntry<MahjongRanking>"
  },
  "MahjongRankingExtraTile": {
    "tileId": "String",
    "count": "Number"
  },
  "MahjongRanking": {
    "includeBonusTiles": "Boolean",
    "expectedTileCount": "Number",
    "extraTiles": "Array"
  },
  "MahjongTile": {
    "pieceKind": "PieceKind",
    "tileKind": "MahjongTileKind",
    "tileId": "String",
    "imageHash": "ImageHash",
    "imagePath": "String",
    "suit": "MahjongSuit",
    "rank": "Number",
    "wind": "MahjongWind",
    "dragon": "MahjongDragon",
    "bonusIndex": "Number"
  },
  "PlayingCard": {
    "pieceKind": "PieceKind",
    "cardId": "String",
    "imageHash": "ImageHash",
    "playingCardRankingAsset": "AssetResourceEntry<PlayingCardRanking>"
  },
  "PlayingCardDeck": {
    "name": "String",
    "supportedTriples": "Array",
    "cardTemplates": "Array",
    "playingCardRankingAsset": "AssetResourceEntry<PlayingCardRanking>"
  },
  "PlayingCardRankingEntry": {
    "cardId": "String"
  },
  "PlayingCardRanking": {
    "expectedCardCount": "Number",
    "cards": "Array"
  },
  "CardGameLayout": {
    "defaultPlayerCount": "Number",
    "presets": "Record<string, LayoutPreset>",
    "playerUiDefaults": "CardGameLayoutDocument['playerUiDefaults']",
    "hud": "CardGameLayoutDocument['hud']",
    "scoreboard": "CardGameLayoutDocument['scoreboard']",
    "cardStrip": "CardGameLayoutDocument['cardStrip']",
    "deckTray": "CardGameLayoutDocument['deckTray']",
    "cardFan": "CardGameLayoutDocument['cardFan']",
    "cardVisuals": "CardGameLayoutDocument['cardVisuals']",
    "cardFrame": "CardGameLayoutDocument['cardFrame']",
    "renderToggles": "CardGameLayoutDocument['renderToggles']",
    "tablePresentation": "CardGameLayoutDocument['tablePresentation']",
    "tableAttachments": "CardGameLayoutDocument['tableAttachments']",
    "views": "Record<string, LayoutPreset>",
    "stageLayout": "CardGameLayoutDocument['stageLayout']",
    "zones": "CardGameLayoutDocument['zones']",
    "gameplay": "Record<string, unknown>",
    "extensions": "Record<string, unknown>"
  },
  "Layout": {
    "layout": "LayoutStructure"
  },
  "PageLayout": {
    "pageId": "String",
    "routePath": "String",
    "title": "String",
    "kind": "PageLayoutKind",
    "slices": "Array",
    "layout": "LayoutStructure",
    "pageControls": "PageLayoutDocument['pageControls']",
    "layoutControls": "SelectedGameLayoutControls",
    "lobbyControls": "Record<string, unknown>",
    "authControls": "Record<string, unknown>",
    "shopControls": "Record<string, unknown>",
    "shopContent": "PartialShopPageContentData",
    "contentPlan": "SelectedGameContentPlan",
    "preview": "PageLayoutDocument['preview']"
  },
  "UIComponent": {
    "component": "ComponentType",
    "styles": "ComponentStyles",
    "elementType": "Object as unknown as new ()"
  }
};
