// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

export const fieldTypeMap: Record<string, Record<string, string>> = {
  "AssetResourceEntry": {
    "guid": "AssetGUIDType",
    "assetType": "AssetType",
    "inheritanceChain": "string[] | null",
    "variant": "string | null"
  },
  "FileResourceEntry": {
    "fileType": "String"
  },
  "ImageResourceEntry": {
    "hash": "ImageHash"
  },
  "ResourceEntry": {
    "path": "String",
    "displayName": "String",
    "gameId": "GameId | null",
    "category": "AssetCategory | null",
    "mimeType": "MimeType | null",
    "fileSize": "number | null",
    "createdAt": "Timestamp | null",
    "updatedAt": "Timestamp | null",
    "lastScanAt": "Timestamp | null",
    "checksum": "AssetChecksum | null"
  },
  "SoundResourceEntry": {
    "hash": "SoundHash"
  },
  "VideoResourceEntry": {
    "hash": "VideoHash"
  },
  "AIModelList": {
    "name": "String",
    "description": "String",
    "models": "Array",
    "defaultModelId": "String",
    "defaultQuantPath": "String"
  },
  "ModelQuantSettings": {
    "modelId": "String",
    "quantPath": "String",
    "displayName": "String",
    "description": "String",
    "settings": "InferenceSettings"
  },
  "BaseAssetMetadata": {
    "typeCategory": "AssetTypeCategory | null",
    "tags": "Array",
    "status": "AssetStatus | null",
    "createdAt": "String",
    "updatedAt": "String",
    "guid": "String"
  },
  "Card": {
    "cardIdentity": "CardIdentity",
    "imageHash": "ImageHash",
    "cardId": "String",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "CardSuitEntry": {
    "SuitName": "String",
    "SuitSymbol": "String",
    "SuitColor": "SuitColor",
    "DisplayOrder": "Number",
    "CardName": "String",
    "Value": "Number",
    "CardSymbol": "String",
    "id": "String",
    "copies": "Number",
    "suit": "string | null",
    "rank": "string | number | null",
    "label": "string | null",
    "order": "number | null",
    "points": "number | null",
    "kind": "string | null",
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "deckFamily": "DeckFamily",
    "cardEntries": "Array",
    "familyPayload": "Array",
    "cardIdentities": "Array"
  },
  "CardRankingEntry": {
    "CardName": "String",
    "Value": "Number",
    "CardSymbol": "String",
    "DisplayOrder": "Number",
    "id": "String",
    "copies": "Number",
    "suit": "string | null",
    "rank": "string | number | null",
    "label": "string | null",
    "order": "number | null",
    "points": "number | null",
    "kind": "string | null",
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "deckFamily": "DeckFamily",
    "cardEntries": "Array",
    "familyPayload": "Array",
    "cardIdentities": "Array"
  },
  "CardRankingExplicitEntry": {
    "id": "String",
    "copies": "Number",
    "suit": "string | null",
    "rank": "string | number | null",
    "label": "string | null",
    "order": "number | null",
    "points": "number | null",
    "kind": "string | null",
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "deckFamily": "DeckFamily",
    "cardEntries": "Array",
    "familyPayload": "Array",
    "cardIdentities": "Array"
  },
  "CardRanking": {
    "deckType": "DeckType",
    "expectedCardCount": "Number",
    "includesJokers": "Boolean",
    "backCardCount": "Number",
    "deckFamily": "DeckFamily",
    "cardEntries": "Array",
    "familyPayload": "Array",
    "cardIdentities": "Array"
  },
  "SupportedDeckTriple": {
    "deckType": "String",
    "suitSet": "String",
    "rankSet": "String",
    "cardTemplate": "AssetResourceEntry<Card>",
    "copies": "Number",
    "name": "String",
    "supportedTriples": "Array",
    "cardTemplates": "Array",
    "cardComposition": "Array",
    "backCardHash": "ImageHash",
    "imageSourceFolderPath": "String",
    "cardOutputPath": "String",
    "backCardSourceFolderPath": "String",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "DeckCardMember": {
    "cardTemplate": "AssetResourceEntry<Card>",
    "copies": "Number",
    "name": "String",
    "supportedTriples": "Array",
    "cardTemplates": "Array",
    "cardComposition": "Array",
    "backCardHash": "ImageHash",
    "imageSourceFolderPath": "String",
    "cardOutputPath": "String",
    "backCardSourceFolderPath": "String",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "Deck": {
    "name": "String",
    "supportedTriples": "Array",
    "cardTemplates": "Array",
    "cardComposition": "Array",
    "backCardHash": "ImageHash",
    "imageSourceFolderPath": "String",
    "cardOutputPath": "String",
    "backCardSourceFolderPath": "String",
    "cardRankingAsset": "AssetResourceEntry<CardRanking>"
  },
  "ImageCarousel": {
    "slides": "Array",
    "autoplayIntervalMs": "Number",
    "lastImageDurationMs": "Number",
    "fastRotationDurationMs": "Number",
    "defaultRotationDurationMs": "Number",
    "fastRotationThreshold": "Number",
    "slideTransitionDelayMs": "Number"
  },
  "ImageList": {
    "images": "Array"
  },
  "CardGameMechanics": {
    "familyKernel": "String",
    "kernelVersion": "String",
    "playerConfig": "MechanicsPlayerConfig",
    "phases": "Array",
    "actions": "Record<string, MechanicsAction>",
    "customActions": "Array",
    "zones": "Array",
    "turnPolicy": "MechanicsTurnPolicy",
    "endConditions": "Array",
    "cardVisibility": "Record<string, unknown>",
    "drawConfig": "Record<string, unknown> | null",
    "discardConfig": "Record<string, unknown> | null",
    "deckType": "String",
    "suitSet": "String",
    "rankSet": "String",
    "initialHandSize": "Number",
    "trumpConfig": "Record<string, unknown> | null",
    "meldConfig": "Record<string, unknown> | null",
    "trickConfig": "Record<string, unknown> | null",
    "declarationMechanism": "Record<string, unknown> | null",
    "handRanks": "Record<string, unknown> | null",
    "buyCosts": "Record<string, unknown> | null",
    "marketConfig": "Record<string, unknown> | null",
    "specialCards": "Record<string, unknown> | null",
    "shedding": "Record<string, unknown> | null",
    "fishingConfig": "Record<string, unknown> | null",
    "patienceConfig": "Record<string, unknown> | null",
    "bankingConfig": "Record<string, unknown> | null",
    "roundConfig": "Record<string, unknown> | null",
    "constants": "Record<string, unknown>",
    "finalHandSize": "Number",
    "deckCount": "Number",
    "implementationHints": "MechanicsImplementationHints",
    "progression": "Array",
    "roles": "Array",
    "determinismNotes": "String"
  },
  "CardGameRules": {
    "bonusRuleGuids": "Array",
    "useTrump": "Boolean",
    "trumpBonusValues": "TrumpBonusValues"
  },
  "GameRules": {
    "LLM": "String",
    "Player": "String",
    "objective": "String",
    "gameplay": "String",
    "keyRules": "Array",
    "moveValidityConditions": "Record<string, string> | null",
    "exampleHands": "Array",
    "bonusRules": "String"
  },
  "TrumpBonusValues": {
    "cardInMiddleBonus": "Number",
    "fiveOfKindBonus": "Number",
    "flushBonus": "Number",
    "fourOfKindBonus": "Number",
    "threeOfKindBonus": "Number",
    "pairBonus": "Number",
    "trumpCardBonus": "Number",
    "wildCardBonus": "Number",
    "rankAdjacentBonus": "Number"
  },
  "DifferentColorsSequence": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FiveOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "Flush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FourOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "FullHouse": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "HighCard": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultipleFourOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultiplePairs": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "MultipleTriplets": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "PairRule": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "RoyalFlush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "SameColorsSequence": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "StraightFlush": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "ThreeOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "TrumpOfAKind": {
    "minNumberOfCard": "Number",
    "bonusValue": "Number",
    "patternType": "String",
    "ruleName": "String",
    "priority": "Number"
  },
  "CardGameScoring": {
    "scoringType": "ScoringType",
    "patternMultipliers": "Record<string, number> | null",
    "priorityOrder": "Array",
    "winCondition": "String",
    "cardValues": "Record<string, number>",
    "penalties": "String",
    "targetScore": "number | null",
    "scoringDirection": "ScoringDirection"
  },
  "Scoring": {
    "cardRankingAsset": "AssetReference | string | null",
    "scoringFormula": "String",
    "scoringRules": "Record<string, unknown> | null",
    "description": "String"
  },
  "Strategy": {
    "LLM": "String",
    "Player": "String",
    "basic": "String",
    "intermediate": "String",
    "advanced": "String",
    "tips": "Array",
    "aggressiveness": "Number",
    "riskTolerance": "Number",
    "bluffFrequency": "Number",
    "bluffSettings": "Record<string, string>"
  },
  "CardGameMode": {
    "baseBet": "Number",
    "initialNumberOfCards": "Number",
    "maxNumberOfCards": "Number",
    "minDecks": "Number",
    "maxDecks": "Number",
    "scoringAsset": "AssetResourceEntry<CardGameScoring>",
    "gameRulesAsset": "AssetResourceEntry<CardGameRules>",
    "strategyAsset": "AssetResourceEntry<Strategy>",
    "gameInfoAsset": "AssetResourceEntry<GameInfo>",
    "deckAsset": "AssetResourceEntry<Deck>",
    "layoutAsset": "AssetResourceEntry<CardGameLayout>",
    "carouselImagesAsset": "AssetResourceEntry<ImageCarousel>",
    "mechanicsAsset": "AssetResourceEntry<CardGameMechanics>",
    "minPlayers": "Number",
    "maxPlayers": "Number",
    "minHumanPlayers": "Number",
    "maxHumanPlayers": "Number",
    "supportsAI": "Boolean",
    "aiCountsAsPlayer": "Boolean",
    "useTrump": "Boolean",
    "trumpBonusValues": "TrumpBonusValues"
  },
  "BettingGameMode": {
    "initialPlayerCoins": "Number"
  },
  "GameMode": {
    "releaseStatus": "GameModeStatus",
    "bannerImage": "ImageHash",
    "gameIcon": "ImageHash"
  },
  "TurnBasedGameMode": {
    "minRounds": "Number",
    "maxRounds": "number | null",
    "turnDuration": "Number"
  },
  "GameRulesContainer": {
    "LLM": "String",
    "Player": "String"
  },
  "CardGameLayout": {
    "defaultPlayerCount": "Number",
    "presets": "Record<string, LayoutPreset>",
    "gameplay": "Record<string, unknown>",
    "extensions": "Record<string, unknown>"
  },
  "Layout": {
    "layout": "LayoutStructure"
  },
  "UIComponent": {
    "component": "ComponentType",
    "styles": "ComponentStyles",
    "elementType": "Object as unknown as new ()"
  }
};
