// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

export type ImportPath = string;

export const inspectorMap = {} as const;

export type InspectorTypeName = keyof typeof inspectorMap;

export type InspectorMap = Record<InspectorTypeName, ImportPath>;
