// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

export const requiredFieldsMap: Record<string, Record<string, string>> = {
  "AssetResourceEntry": {
    "guid": "Asset GUID is required for AssetResourceEntry",
    "assetType": "Asset Type is required for AssetResourceEntry"
  },
  "Card": {
    "cardIdentity": "Card Identity is required",
    "imageHash": "Image Hash is required for card to function properly",
    "cardId": "Card ID is required for card to function properly",
    "cardRankingAsset": "Card Ranking Asset is required for card to function properly"
  },
  "CardSuitEntry": {
    "deckType": "Deck Type is required for card ranking metadata",
    "expectedCardCount": "Expected Card Count is required for card ranking metadata",
    "includesJokers": "Includes Jokers flag is required for card ranking metadata",
    "backCardCount": "Back Card Count is required for card ranking metadata"
  },
  "CardRankingEntry": {
    "deckType": "Deck Type is required for card ranking metadata",
    "expectedCardCount": "Expected Card Count is required for card ranking metadata",
    "includesJokers": "Includes Jokers flag is required for card ranking metadata",
    "backCardCount": "Back Card Count is required for card ranking metadata"
  },
  "CardRankingExplicitEntry": {
    "deckType": "Deck Type is required for card ranking metadata",
    "expectedCardCount": "Expected Card Count is required for card ranking metadata",
    "includesJokers": "Includes Jokers flag is required for card ranking metadata",
    "backCardCount": "Back Card Count is required for card ranking metadata"
  },
  "CardRanking": {
    "deckType": "Deck Type is required for card ranking metadata",
    "expectedCardCount": "Expected Card Count is required for card ranking metadata",
    "includesJokers": "Includes Jokers flag is required for card ranking metadata",
    "backCardCount": "Back Card Count is required for card ranking metadata"
  },
  "SupportedDeckTriple": {
    "supportedTriples": "Supported triples are required for deck to function properly",
    "cardTemplates": "Card Templates are required for deck to function properly",
    "backCardHash": "Back Card Hash is required for deck to function properly",
    "imageSourceFolderPath": "Image Source Folder Path is required for deck to function properly",
    "cardOutputPath": "Card Output Path is required for deck to function properly",
    "backCardSourceFolderPath": "Back Card Source Folder Path is required for deck to function properly",
    "cardRankingAsset": "Card Ranking Asset is required for deck to function properly"
  },
  "DeckCardMember": {
    "supportedTriples": "Supported triples are required for deck to function properly",
    "cardTemplates": "Card Templates are required for deck to function properly",
    "backCardHash": "Back Card Hash is required for deck to function properly",
    "imageSourceFolderPath": "Image Source Folder Path is required for deck to function properly",
    "cardOutputPath": "Card Output Path is required for deck to function properly",
    "backCardSourceFolderPath": "Back Card Source Folder Path is required for deck to function properly",
    "cardRankingAsset": "Card Ranking Asset is required for deck to function properly"
  },
  "Deck": {
    "supportedTriples": "Supported triples are required for deck to function properly",
    "cardTemplates": "Card Templates are required for deck to function properly",
    "backCardHash": "Back Card Hash is required for deck to function properly",
    "imageSourceFolderPath": "Image Source Folder Path is required for deck to function properly",
    "cardOutputPath": "Card Output Path is required for deck to function properly",
    "backCardSourceFolderPath": "Back Card Source Folder Path is required for deck to function properly",
    "cardRankingAsset": "Card Ranking Asset is required for deck to function properly"
  },
  "Scoring": {
    "cardRankingAsset": "Card Ranking Asset is required for scoring to function"
  },
  "CardGameMode": {
    "scoringAsset": "Scoring Asset is required for game mode to function",
    "gameRulesAsset": "Game Rules Asset is required for game mode to function",
    "strategyAsset": "Strategy Asset is required for game mode to function",
    "gameInfoAsset": "Game Info Asset is required for game mode to function",
    "deckAsset": "Deck Asset is required for card game mode to function",
    "layoutAsset": "Layout Asset is required for game mode to function",
    "carouselImagesAsset": "Carousel Images Asset is required for game mode to function",
    "mechanicsAsset": "Mechanics Asset is required for game mode to function"
  }
};
