// This file is auto-generated by scripts/generate-registry-maps.ts
// Do not edit manually - it will be overwritten on build

export const requiredFieldsMap: Record<string, Record<string, string>> = {
  "AssetResourceEntry": {
    "guid": "Asset GUID is required for AssetResourceEntry",
    "assetType": "Asset Type is required for AssetResourceEntry"
  },
  "Card": {
    "cardIdentity": "Card Identity is required",
    "imageHash": "Image Hash is required for card to function properly",
    "cardId": "Card ID is required for card to function properly",
    "rankingAsset": "Card Ranking Asset is required for card to function properly"
  },
  "CardRanking": {
    "deckType": "Deck Type is required for card ranking metadata",
    "expectedCardCount": "Expected Card Count is required for card ranking metadata",
    "includesJokers": "Includes Jokers flag is required for card ranking metadata",
    "backCardCount": "Back Card Count is required for card ranking metadata"
  },
  "Deck": {
    "supportedTriples": "Supported triples are required for deck to function properly",
    "rankingAsset": "Ranking asset is required for deck ordering and preview",
    "cardTemplates": "Card Templates are required for deck to function properly",
    "backCardHash": "Back Card Hash is required for deck to function properly",
    "imageSourceFolderPath": "Image Source Folder Path is required for deck to function properly",
    "cardOutputPath": "Card Output Path is required for deck to function properly",
    "backCardSourceFolderPath": "Back Card Source Folder Path is required for deck to function properly",
    "cardRankingAsset": "Card Ranking Asset is required for deck to function properly"
  },
  "DominoDeckTileMember": {
    "tileTemplate": "Tile template is required",
    "copies": "Copies are required"
  },
  "DominoDeck": {
    "name": "Deck name is required",
    "supportedTriples": "Supported triples are required",
    "dominoRankingAsset": "Domino ranking asset is required"
  },
  "DominoRanking": {
    "expectedTileCount": "Expected tile count is required"
  },
  "DominoTile": {
    "pieceKind": "Piece kind is required",
    "tileId": "Tile ID is required",
    "imageHash": "Image Hash is required"
  },
  "Scoring": {
    "rankingAsset": "Card Ranking Asset is required for scoring to function"
  },
  "CardGameMode": {
    "scoringAsset": "Scoring Asset is required for game mode to function",
    "gameRulesAsset": "Game Rules Asset is required for game mode to function",
    "strategyAsset": "Strategy Asset is required for game mode to function",
    "gameInfoAsset": "Game Info Asset is required for game mode to function",
    "deckAsset": "Deck Asset is required for card game mode to function",
    "layoutAsset": "Layout Asset is required for game mode to function",
    "selectedGameLayoutAsset": "Selected Game Layout Asset is required for game page authoring",
    "lobbyLayoutAsset": "Lobby Layout Asset is required for game lobby authoring",
    "carouselImagesAsset": "Carousel Images Asset is required for game mode to function",
    "mechanicsAsset": "Mechanics Asset is required for game mode to function"
  },
  "HanafudaCard": {
    "pieceKind": "Piece kind is required",
    "month": "Month is required",
    "slot": "Slot is required",
    "group": "Group is required",
    "points": "Points are required",
    "cardId": "Card ID is required",
    "imageHash": "Image Hash is required"
  },
  "HanafudaDeck": {
    "name": "Deck name is required",
    "supportedTriples": "Supported triples are required",
    "cardTemplates": "Card templates are required",
    "hanafudaRankingAsset": "Hanafuda ranking asset is required"
  },
  "HanafudaRankingSlot": {
    "slot": "Slot is required",
    "cardId": "Card ID is required"
  },
  "HanafudaRankingMonth": {
    "month": "Month is required",
    "slots": "Slots are required"
  },
  "HanafudaRanking": {
    "expectedCardCount": "Expected card count is required",
    "months": "Months are required"
  },
  "MahjongDeckTileMember": {
    "tile": "Tile is required",
    "count": "Count is required"
  },
  "MahjongDeck": {
    "name": "Deck name is required",
    "supportedTriples": "Supported triples are required",
    "tiles": "Tiles are required",
    "mahjongRankingAsset": "Mahjong ranking asset is required"
  },
  "MahjongRankingExtraTile": {
    "tileId": "Tile ID is required",
    "count": "Count is required"
  },
  "MahjongRanking": {
    "includeBonusTiles": "Include bonus tiles flag is required",
    "expectedTileCount": "Expected tile count is required"
  },
  "MahjongTile": {
    "pieceKind": "Piece kind is required",
    "tileKind": "Tile kind is required",
    "tileId": "Tile ID is required",
    "imageHash": "Image Hash is required"
  },
  "PlayingCard": {
    "pieceKind": "Piece kind is required",
    "cardId": "Card ID is required",
    "imageHash": "Image Hash is required",
    "playingCardRankingAsset": "Playing card ranking asset is required"
  },
  "PlayingCardDeck": {
    "name": "Deck name is required",
    "supportedTriples": "Supported triples are required",
    "cardTemplates": "Card templates are required",
    "playingCardRankingAsset": "Playing card ranking asset is required"
  },
  "PlayingCardRankingEntry": {
    "cardId": "Card ID is required"
  },
  "PlayingCardRanking": {
    "expectedCardCount": "Expected card count is required",
    "cards": "Cards are required"
  }
};
