import { defaultAvatarImageUrl } from '@ocentra/app-assets/avatars';
import {
  bannerAIBenchmarkingImageUrl,
  bannerGlobalLeaderboardImageUrl,
  bannerIntelligentAIImageUrl,
  bannerPlayAnywhereImageUrl,
  bannerPlayYourWayImageUrl,
  bannerProvablyFairImageUrl,
  bannerRewardingEconomyImageUrl,
  bannerTrackYourProgressImageUrl,
  bannerTrueMultiplayerImageUrl,
  bannerWalletFreedomImageUrl,
} from '@ocentra/app-assets/banners';
import {
  PartialPlayerHubPageContentDataSchema,
  PlayerHubPageContentDataSchema,
  type PartialPlayerHubPageContentData,
  type PlayerHubCard,
  type PlayerHubIcon,
  type PlayerHubPageContentData,
  type PlayerHubRightDetailId,
  type PlayerHubSection,
  type PlayerHubSectionId,
  type PlayerHubTone,
} from '@ocentra/game-asset-domain/schemas/player-hub-page-content-schema';
import {
  ShopPageContentDataSchema,
  type ShopIcon,
  type ShopPageContentData,
  type ShopPageTab,
  type ShopPreviewRow,
  type ShopQuest,
  type ShopRightTab,
  type ShopRightTabId,
  type ShopSection,
  type ShopSideItem,
  type ShopStaticItem,
  type ShopTone,
  type ShopVaultShowcaseGroup,
} from '@ocentra/game-asset-domain/schemas/shop-page-content-schema';

export type {
  PartialPlayerHubPageContentData,
  PlayerHubCard,
  PlayerHubIcon,
  PlayerHubPageContentData,
  PlayerHubRightDetailId,
  PlayerHubSection,
  PlayerHubSectionId,
  PlayerHubTone,
};

export const PLAYER_HUB_EMPTY_VALUE = 'No data';

const playerHubProfileImageUrl = defaultAvatarImageUrl;
const playerHubSettingsImageUrl = bannerWalletFreedomImageUrl;
const playerHubAiImageUrl = bannerIntelligentAIImageUrl;
const playerHubAiReviewImageUrl = bannerAIBenchmarkingImageUrl;
const playerHubBalancesImageUrl = bannerRewardingEconomyImageUrl;
const playerHubMatchesImageUrl = bannerTrueMultiplayerImageUrl;
const playerHubRoomHandoffImageUrl = bannerPlayYourWayImageUrl;
const playerHubLearningImageUrl = bannerTrackYourProgressImageUrl;
const playerHubCompetitionImageUrl = bannerGlobalLeaderboardImageUrl;
const playerHubProgramsImageUrl = bannerProvablyFairImageUrl;
const playerHubInventoryImageUrl = bannerPlayAnywhereImageUrl;
const playerHubRewardsImageUrl = bannerRewardingEconomyImageUrl;

const overviewCards: PlayerHubCard[] = [
  {
    id: 'profile-identity',
    title: 'Profile & Identity',
    subtitle: 'Display name, avatar, account status, privacy, and profile-safe values are managed inside Player Hub.',
    tone: 'cyan',
    icon: 'lock',
    imageUrl: playerHubProfileImageUrl,
    targetDetail: 'account',
    badge: 'Profile',
    cta: 'Details',
    bullets: ['Profile data stays private.', 'Unsafe account IDs are not shown as names.', 'No profile copy is generated by the UI.'],
  },
  {
    id: 'settings-privacy',
    title: 'Settings & Privacy',
    subtitle: 'Account-level privacy and identity controls are summarized here. Device, provider, and runtime settings open in Settings.',
    tone: 'gold',
    icon: 'shield',
    imageUrl: playerHubSettingsImageUrl,
    targetDetail: 'settings',
    badge: 'Account',
    cta: 'Manage',
    bullets: ['Player Hub keeps the account summary.', 'Dedicated Settings owns runtime controls.', 'Editor-authored copy and controls.'],
  },
  {
    id: 'ai-runtime-setup',
    title: 'AI Runtime Setup',
    subtitle: 'Saved AI runtime state is summarized here. Provider, local server, browser model, and inference controls open in Settings.',
    tone: 'green',
    icon: 'shield',
    imageUrl: playerHubAiImageUrl,
    targetDetail: 'ai',
    badge: 'AI',
    cta: 'Configure',
    bullets: ['Cloud keys use account worker storage.', 'Local server endpoints stay device-local.', 'Browser models use the AI model catalog.'],
  },
  {
    id: 'balances-ownership',
    title: 'Balances & Ownership',
    subtitle: 'GP, AC, owned items, rewards, tickets, passes, and account history appear only when real services return them.',
    tone: 'violet',
    icon: 'coins',
    imageUrl: playerHubBalancesImageUrl,
    targetDetail: 'balances',
    badge: 'Owned',
    cta: 'Review',
    bullets: ['Real account inventory only.', 'Purchases stay outside Player Hub.', 'Competition passes stay account-owned.'],
  },
];

const matchCards: PlayerHubCard[] = [
  {
    id: 'match-history-empty',
    title: 'No completed matches yet',
    subtitle: 'Finished public or private room records will appear here after real match history is connected.',
    tone: 'cyan',
    icon: 'cards',
    imageUrl: playerHubMatchesImageUrl,
    targetDetail: 'recent',
    badge: 'No records',
    cta: 'History',
    bullets: ['Match history uses completed games.', 'No fake match rows are shown.', 'Room creation stays outside this page.'],
  },
  {
    id: 'match-handoff',
    title: 'Room Handoff',
    subtitle: 'Player Hub summarizes account match activity. Live public room discovery belongs to the game lobby.',
    tone: 'green',
    icon: 'link',
    imageUrl: playerHubRoomHandoffImageUrl,
    targetDetail: 'recent',
    badge: 'Handoff',
    cta: 'View',
    bullets: ['Game-specific handoff.', 'Room status is not duplicated here.', 'Completed matches return here.'],
  },
];

const learningCards: PlayerHubCard[] = [
  {
    id: 'learning-not-active',
    title: 'Learning paths are not active yet',
    subtitle: 'Lessons, AI review, mistake tracking, and recommended drills will appear after learning programs are enabled.',
    tone: 'violet',
    icon: 'shield',
    imageUrl: playerHubLearningImageUrl,
    targetDetail: 'learning',
    badge: 'Planned',
    cta: 'View',
    bullets: ['Lesson ownership will be account-based.', 'AI review will use completed games.', 'Skill tracking will remain private.'],
  },
  {
    id: 'ai-skill-review',
    title: 'AI Skill Review',
    subtitle: 'No skill score is fabricated. Recommendations appear only after the learning service returns real account data.',
    tone: 'cyan',
    icon: 'shield',
    imageUrl: playerHubAiReviewImageUrl,
    targetDetail: 'learning',
    badge: 'Pending',
    cta: 'Later',
    bullets: ['No mock score.', 'No invented recommendations.', 'No generated lesson progress.'],
  },
];

const aiCards: PlayerHubCard[] = [
  {
    id: 'ai-setup-controls',
    title: 'AI Setup',
    subtitle: 'Review saved AI setup from Player Hub. Edit provider keys, local servers, browser models, and inference defaults in Settings.',
    tone: 'green',
    icon: 'shield',
    imageUrl: playerHubAiImageUrl,
    targetDetail: 'ai',
    badge: 'Configure',
    cta: 'Setup',
    bullets: ['Cloud keys save through the account worker.', 'Local endpoints remain device-local.', 'Browser models use the AI model catalog.'],
  },
  {
    id: 'ai-runtime-sources',
    title: 'Runtime Sources',
    subtitle: 'Ollama, LM Studio, vLLM, LocalAI, KoboldCpp, native app, and browser-local model choices are surfaced here when saved.',
    tone: 'cyan',
    icon: 'link',
    imageUrl: playerHubAiReviewImageUrl,
    targetDetail: 'ai',
    badge: 'Models',
    cta: 'Manage',
    bullets: ['No keys are generated by UI copy.', 'Provider state comes from saved contracts.', 'Inference settings stay explicit.'],
  },
];

const competitionCards: PlayerHubCard[] = [
  {
    id: 'competition-no-pass',
    title: 'No event tickets or tournament passes yet',
    subtitle: 'Official entries, check-in windows, tournament passes, and past competition records appear after real ownership exists.',
    tone: 'gold',
    icon: 'trophy',
    imageUrl: playerHubCompetitionImageUrl,
    targetDetail: 'competition',
    badge: 'No passes',
    cta: 'Competition',
    bullets: ['Competition page owns official schedules.', 'Shop can sell tickets and passes.', 'Player Hub shows owned entries only.'],
  },
  {
    id: 'official-programs',
    title: 'Official Programs',
    subtitle: 'Open events and tournaments are published on Competition. Player Hub summarizes owned participation.',
    tone: 'orange',
    icon: 'crown',
    imageUrl: playerHubProgramsImageUrl,
    targetDetail: 'competition',
    badge: 'Schedule',
    cta: 'Open',
    bullets: ['Fixed-date programs.', 'Ticket/pass ownership.', 'Check-in handoff when available.'],
  },
];

const inventoryCards: PlayerHubCard[] = [
  {
    id: 'inventory-empty',
    title: 'No owned items yet',
    subtitle: 'Decks, cosmetics, badges, tickets, and passes appear here after they are earned, granted, or purchased.',
    tone: 'orange',
    icon: 'chest',
    imageUrl: playerHubInventoryImageUrl,
    targetDetail: 'balances',
    badge: 'Empty',
    cta: 'View Inventory',
    bullets: ['Inventory uses entitlement data.', 'No placeholder items.', 'Images and card copy are authored in this asset.'],
  },
];

const rewardCards: PlayerHubCard[] = [
  {
    id: 'reward-history-empty',
    title: 'No reward history yet',
    subtitle: 'Daily rewards, badges, achievements, and competition prizes appear here when real grants exist.',
    tone: 'green',
    icon: 'coins',
    imageUrl: playerHubRewardsImageUrl,
    targetDetail: 'recent',
    badge: 'Rewards',
    cta: 'View',
    bullets: ['Reward state comes from account services.', 'No fake claims.', 'Earned prizes stay tied to the player.'],
  },
];

function cloneCard(card: PlayerHubCard): PlayerHubCard {
  return {
    ...card,
    bullets: card.bullets ? [...card.bullets] : undefined,
  };
}

export const DEFAULT_PLAYER_HUB_PAGE_CONTENT: PlayerHubPageContentData = {
  headerMetrics: [
    { key: 'gp', label: 'GP', fallbackValue: PLAYER_HUB_EMPTY_VALUE },
    { key: 'ac', label: 'AC', fallbackValue: PLAYER_HUB_EMPTY_VALUE },
    { key: 'ownedItems', label: 'Owned', fallbackValue: PLAYER_HUB_EMPTY_VALUE },
    { key: 'gamesPlayed', label: 'Played', fallbackValue: PLAYER_HUB_EMPTY_VALUE },
  ],
  navigation: [
    { id: 'overview', title: 'Overview', subtitle: 'Profile and account snapshot', icon: 'crown', tone: 'cyan', imageUrl: playerHubProfileImageUrl },
    { id: 'matches', title: 'Matches', subtitle: 'History and room handoff', icon: 'cards', tone: 'cyan', imageUrl: playerHubMatchesImageUrl },
    { id: 'learning', title: 'Learning', subtitle: 'Lessons and AI review', icon: 'shield', tone: 'violet', imageUrl: playerHubLearningImageUrl },
    { id: 'ai', title: 'AI Setup', subtitle: 'Models and runtime', icon: 'shield', tone: 'green', imageUrl: playerHubAiImageUrl },
    { id: 'competition', title: 'Competition', subtitle: 'Tickets and passes', icon: 'trophy', tone: 'gold', imageUrl: playerHubCompetitionImageUrl },
    { id: 'inventory', title: 'Inventory', subtitle: 'Owned account items', icon: 'chest', tone: 'orange', imageUrl: playerHubInventoryImageUrl },
    { id: 'rewards', title: 'Rewards', subtitle: 'Daily and earned grants', icon: 'coins', tone: 'green', imageUrl: playerHubRewardsImageUrl },
    { id: 'account', title: 'Account', subtitle: 'Profile and preferences', icon: 'lock', tone: 'cyan', imageUrl: playerHubProfileImageUrl },
  ],
  sections: {
    overview: {
      title: 'PLAYER OVERVIEW',
      subtitle: 'Profile, balances, account status, rewards, and ownership.',
      footerTitle: 'Hub areas:',
      footerItems: ['Profile', 'Privacy', 'AI summary', 'Balances', 'Ownership'],
      summaryCards: overviewCards.map(cloneCard),
      detailCards: [],
    },
    matches: {
      title: 'MATCHES',
      subtitle: 'Finished games appear here after match history is connected.',
      footerTitle: 'Match surfaces:',
      footerItems: ['Completed games', 'Private rooms', 'Public rooms', 'Room handoff'],
      summaryCards: matchCards.map(cloneCard),
      detailCards: [],
    },
    learning: {
      title: 'LEARNING',
      subtitle: 'Lessons and AI review appear only when enabled for the signed-in player.',
      footerTitle: 'Learning modules:',
      footerItems: ['Lessons', 'AI review', 'Mistake tracking', 'Drills', 'Skill trends'],
      summaryCards: learningCards.map(cloneCard),
      detailCards: [],
    },
    ai: {
      title: 'AI SETUP',
      subtitle: 'Provider keys, local servers, browser models, and inference settings for the signed-in player.',
      footerTitle: 'AI settings:',
      footerItems: ['Cloud keys', 'Local endpoints', 'Browser models', 'Inference', 'Device runtime'],
      summaryCards: aiCards.map(cloneCard),
      detailCards: [],
    },
    competition: {
      title: 'COMPETITION',
      subtitle: 'Owned tickets, passes, and official competition records.',
      footerTitle: 'Competition state:',
      footerItems: ['Tickets', 'Passes', 'Check-in', 'Past events', 'Tournament records'],
      summaryCards: competitionCards.map(cloneCard),
      detailCards: [],
    },
    inventory: {
      title: 'INVENTORY',
      subtitle: 'Owned items and rewards from real account entitlements.',
      footerTitle: 'Inventory states:',
      footerItems: ['Owned', 'Equipped', 'Tickets', 'Passes', 'Cosmetics'],
      summaryCards: inventoryCards.map(cloneCard),
      detailCards: [],
    },
    rewards: {
      title: 'REWARD HISTORY',
      subtitle: 'Daily rewards, badges, achievements, and competition prizes appear here when they are earned.',
      footerTitle: 'Reward state:',
      footerItems: ['Daily rewards', 'Badges', 'Achievements', 'Competition prizes'],
      summaryCards: rewardCards.map(cloneCard),
      detailCards: [],
    },
    account: {
      title: 'ACCOUNT SETTINGS',
      subtitle: 'Profile-safe account controls, privacy summary, and settings handoff.',
      footerTitle: 'Account areas:',
      footerItems: ['Identity', 'Privacy', 'Settings link', 'AI summary'],
      summaryCards: overviewCards.slice(0, 3).map(cloneCard),
      detailCards: [],
    },
  },
  inventoryGroups: [
    {
      key: 'owned',
      title: 'Owned Items',
      subtitle: 'Inventory from the player account.',
      tone: 'orange',
      icon: 'chest',
      badge: 'Owned',
      heroImageUrl: playerHubInventoryImageUrl,
      items: inventoryCards.map(cloneCard),
    },
    {
      key: 'rewards',
      title: 'Reward History',
      subtitle: 'Rewards appear after real grants exist.',
      tone: 'green',
      icon: 'coins',
      badge: 'Rewards',
      heroImageUrl: playerHubRewardsImageUrl,
      items: rewardCards.map(cloneCard),
    },
  ],
  previews: [
    { title: 'PLAYER OVERVIEW', sectionId: 'overview', subtitle: 'Profile, AI summary, balances, and account status', items: overviewCards.map(card => card.title), accent: '#54e2ff', imageUrls: overviewCards.map(card => card.imageUrl) },
    { title: 'MATCH HISTORY', sectionId: 'matches', subtitle: 'Real completed games appear here', items: matchCards.map(card => card.title), accent: '#20e39d', imageUrls: matchCards.map(card => card.imageUrl) },
    { title: 'LEARNING', sectionId: 'learning', subtitle: 'Lessons and AI review when enabled', items: learningCards.map(card => card.title), accent: '#bd76ff', imageUrls: learningCards.map(card => card.imageUrl) },
    { title: 'AI SETUP', sectionId: 'ai', subtitle: 'Cloud, local, browser, and inference status', items: aiCards.map(card => card.title), accent: '#20e39d', imageUrls: aiCards.map(card => card.imageUrl) },
    { title: 'COMPETITION', sectionId: 'competition', subtitle: 'Tickets, passes, and official records', items: competitionCards.map(card => card.title), accent: '#ffd36a', imageUrls: competitionCards.map(card => card.imageUrl) },
    { title: 'INVENTORY', sectionId: 'inventory', subtitle: 'Owned items and rewards', items: inventoryCards.map(card => card.title), accent: '#de4fe8', imageUrls: inventoryCards.map(card => card.imageUrl) },
    { title: 'REWARD HISTORY', sectionId: 'rewards', subtitle: 'Daily rewards, badges, achievements, and competition prizes', items: rewardCards.map(card => card.title), accent: '#20e39d', imageUrls: rewardCards.map(card => card.imageUrl) },
    { title: 'ACCOUNT', sectionId: 'account', subtitle: 'Profile, privacy, and settings handoff', items: overviewCards.slice(0, 3).map(card => card.title), accent: '#54e2ff', imageUrls: overviewCards.slice(0, 3).map(card => card.imageUrl) },
  ],
  rewardActions: [
    {
      key: 'player-hub-rewards',
      group: 'Rewards',
      title: rewardCards[0].title,
      reward: PLAYER_HUB_EMPTY_VALUE,
      cadence: 'Account',
      tone: 'green',
      icon: 'coins',
      action: 'View Rewards',
      imageUrl: playerHubRewardsImageUrl,
      description: rewardCards[0].subtitle,
      details: rewardCards[0].bullets ? [...rewardCards[0].bullets] : [],
    },
  ],
  rightTabs: [
    { id: 'account', title: 'PROFILE', accent: '#54e2ff' },
    { id: 'settings', title: 'SETTINGS', accent: '#ffd36a' },
    { id: 'ai', title: 'AI SETUP', accent: '#20e39d' },
    { id: 'balances', title: 'BALANCES', accent: '#ffd36a' },
    { id: 'recent', title: 'RECENT', accent: '#20e39d' },
  ],
  rightRows: {
    balances: [['GP', PLAYER_HUB_EMPTY_VALUE], ['AC', PLAYER_HUB_EMPTY_VALUE], ['Owned items', PLAYER_HUB_EMPTY_VALUE], ['Catalog items', PLAYER_HUB_EMPTY_VALUE], ['Status', PLAYER_HUB_EMPTY_VALUE]],
    competition: [['Tickets / passes', PLAYER_HUB_EMPTY_VALUE, 'Open Competition'], ['Check-in', PLAYER_HUB_EMPTY_VALUE, 'View'], ['Programs', PLAYER_HUB_EMPTY_VALUE, 'Open']],
    recent: [['Matches', PLAYER_HUB_EMPTY_VALUE], ['Rewards', PLAYER_HUB_EMPTY_VALUE], ['Services', PLAYER_HUB_EMPTY_VALUE]],
  },
  rightDetails: {
    account: [
      { label: 'Profile', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Signed-in profile name appears when it is safe to display.' },
      { label: 'Account ID', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Private account identifier.' },
      { label: 'Display name', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Editable player-facing name belongs in Player Hub account controls.' },
      { label: 'Theme', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Loaded from the account settings service when available.' },
      { label: 'Notifications', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Notification preference summary from account settings.' },
      { label: 'AI setup', value: PLAYER_HUB_EMPTY_VALUE, detail: 'AI runtime state is summarized here and edited in Settings.' },
      { label: 'Privacy', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Private player data stays owner-only unless a future public profile is explicitly built.' },
    ],
    settings: [
      { label: 'Theme', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Editable account theme preference.' },
      { label: 'Notifications', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Editable notification preference.' },
      { label: 'Sound', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Editable sound preference.' },
      { label: 'Language', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Editable language code.' },
      { label: 'Region', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Editable preferred server region.' },
    ],
    ai: [
      { label: 'Cloud API keys', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Encrypted provider keys are saved through the account worker when authenticated.' },
      { label: 'Local servers', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Ollama, LM Studio, vLLM, LocalAI, KoboldCpp, and native endpoint settings are saved per device.' },
      { label: 'Browser models', value: PLAYER_HUB_EMPTY_VALUE, detail: 'HuggingFace browser-local models can be added, refreshed, and selected from the AI model catalog.' },
      { label: 'Inference', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Generation parameters are saved for the selected browser model and quantization.' },
    ],
    balances: [
      { label: 'Game Points', value: PLAYER_HUB_EMPTY_VALUE, detail: 'GP balance from account data.' },
      { label: 'Arena Credits', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Spendable AC balance for Shop and entries.' },
      { label: 'Owned items', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Real inventory item count.' },
      { label: 'Catalog items', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Catalog browsing and checkout remain outside Player Hub.' },
      { label: 'Status', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Account status appears only when profile services return it.' },
    ],
    learning: [
      { label: 'Learning', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Learning progress appears after the service is enabled.' },
      { label: 'AI review', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Review uses completed game data.' },
    ],
    competition: [
      { label: 'Tickets / passes', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Competition ownership appears after checkout or grant.' },
      { label: 'Tournament passes', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Passes appear only after real ownership.' },
    ],
    recent: [
      { label: 'Matches', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Completed matches appear after history is connected.' },
      { label: 'Rewards', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Reward state appears after account services return it.' },
      { label: 'Services', value: PLAYER_HUB_EMPTY_VALUE, detail: 'Warnings appear only when an account service fails.' },
    ],
  },
  uiCopy: {
    header: {
      title: 'Player Hub',
      subtitle: 'Private account hub for profile, matches, learning, inventory, rewards, and competition ownership.',
      badges: [
        { title: 'Private', sub: 'Account', icon: 'lock', tone: 'green' },
        { title: 'Profile', sub: 'Linked', icon: 'link', tone: 'cyan' },
        { title: 'Progress', sub: 'Tracked', icon: 'shield', tone: 'violet' },
      ],
      balanceTitle: 'Arena Credits',
      balanceUnit: 'AC',
      balanceSub: 'Player balance',
    },
    rightPanel: {
      balancesTitle: 'BALANCES',
      learningTitle: 'LEARNING',
      competitionTitle: 'COMPETITION',
      recentTitle: 'RECENT',
      accountTitle: 'ACCOUNT',
      learningName: 'Learning pending',
      manageLearning: 'Learning',
      viewAccount: 'Account',
      profileName: PLAYER_HUB_EMPTY_VALUE,
      profileLevel: PLAYER_HUB_EMPTY_VALUE,
      emailUnavailable: PLAYER_HUB_EMPTY_VALUE,
      guestProfile: PLAYER_HUB_EMPTY_VALUE,
      initialsUnavailable: '?',
      ratingUnavailable: PLAYER_HUB_EMPTY_VALUE,
      gamesUnavailable: PLAYER_HUB_EMPTY_VALUE,
      winRateUnavailable: PLAYER_HUB_EMPTY_VALUE,
      levelPrefix: '',
      gamesSuffix: 'games',
      winRateSuffix: 'win',
      moreLabel: 'More',
      openLearning: 'Open Learning',
    },
    actions: {
      comingSoon: 'Pending',
      open: 'Open',
      view: 'View',
      details: 'Details',
      working: 'Working',
      backToHub: 'Back To Hub',
      backToPrefix: 'Back To',
      openGroup: 'Open',
      claim: 'Claim',
    },
    status: {
      loadingHub: 'Loading player hub...',
      retry: 'Retry',
      unknownValue: PLAYER_HUB_EMPTY_VALUE,
    },
    detailView: {
      accountTitle: 'PLAYER ACCOUNT',
      accountSubtitle: 'Player Hub manages profile-safe account data and summarizes settings that are edited on the Settings page.',
      accountCta: 'Back To Hub',
      accountBullets: ['Player Hub is the account summary surface.', 'Dedicated Settings owns device and runtime controls.', 'No fake account fields are generated by the UI.'],
      learningTitle: 'PLAYER LEARNING',
      learningSubtitle: 'Lessons and AI review appear only when enabled for the signed-in player.',
      learningCta: 'Back To Learning',
      learningTiers: [
        { key: 'lessons', title: 'Lessons', value: PLAYER_HUB_EMPTY_VALUE, tone: 'cyan' },
        { key: 'review', title: 'AI Review', value: PLAYER_HUB_EMPTY_VALUE, tone: 'violet' },
        { key: 'drills', title: 'Drills', value: PLAYER_HUB_EMPTY_VALUE, tone: 'gold' },
      ],
      learningRows: [
        { label: 'Status', values: [PLAYER_HUB_EMPTY_VALUE, PLAYER_HUB_EMPTY_VALUE, PLAYER_HUB_EMPTY_VALUE] },
        { label: 'Source', values: ['Lessons', 'Completed games', 'Skill model'] },
      ],
    },
    itemPreview: {
      title: 'Item Preview',
      backToInventory: 'Back To Inventory',
      itemType: 'Account item',
      itemOptionsSuffix: 'options',
      noItemData: 'No item preview available.',
      missingImage: 'Missing image',
      priceUnavailable: 'No price',
      previousImage: 'Previous',
      nextImage: 'Next',
      closeDetail: 'Close',
      expand: 'Expand',
    },
    rewards: {
      title: 'REWARD HISTORY',
      subtitle: 'Daily rewards, badges, achievements, and competition prizes appear here when they are earned.',
      backLabel: 'Back To Hub',
      closeLabel: 'Close',
      detailLabel: 'Details',
      helper: 'Reward proof appears after a real grant.',
      fields: ['Reward', 'Status', 'Source'],
      chips: ['Account', 'Reward', 'Private'],
      status: PLAYER_HUB_EMPTY_VALUE,
      open: 'Open',
      copy: 'Copy',
      start: 'Start',
      check: 'Check',
    },
    footer: [
      { title: 'Player Hub', sub: 'Profile and account data', icon: 'lock', tone: 'green' },
      { title: 'Match History', sub: 'Completed games return here', icon: 'cards', tone: 'cyan' },
      { title: 'Catalog Handoff', sub: 'Purchases stay outside the hub', icon: 'link', tone: 'green' },
      { title: 'Competition', sub: 'Tickets and passes when owned', icon: 'trophy', tone: 'gold' },
    ],
  },
};

type JsonRecord = Record<string, unknown>;

const sectionToShopTab: Record<Exclude<PlayerHubSectionId, 'rewards' | 'account' | 'ai'>, ShopPageTab> = {
  overview: 'Treasury',
  matches: 'Play Access',
  learning: 'Elite',
  competition: 'Events',
  inventory: 'Vault',
};

const rightDetailToShopTab: Record<PlayerHubRightDetailId, ShopRightTabId> = {
  account: 'account',
  settings: 'settings',
  ai: 'ai',
  balances: 'wallet',
  learning: 'pass',
  competition: 'events',
  recent: 'recent',
};

function asRecord(value: unknown): JsonRecord {
  return value && typeof value === 'object' && !Array.isArray(value) ? value as JsonRecord : {};
}

function cloneDefaultContent(): PlayerHubPageContentData {
  return JSON.parse(JSON.stringify(DEFAULT_PLAYER_HUB_PAGE_CONTENT)) as PlayerHubPageContentData;
}

const STALE_PLAYER_HUB_COPY = new Map<string, string>([
  ['N/A', PLAYER_HUB_EMPTY_VALUE],
  ['NA', PLAYER_HUB_EMPTY_VALUE],
  ['Email N/A', 'Email unavailable'],
  ['Your private player profile, settings, progress, matches, inventory, rewards, and account controls.', 'Your private player profile, progress, matches, inventory, rewards, and account controls.'],
  ['Profile preferences, notification settings, wallet status, AI settings, API settings, local runtime choices, and privacy controls belong inside Player Hub.', 'Profile-safe account controls stay in Player Hub. Device, provider, API, local runtime, and privacy settings open in Settings.'],
  ['Cloud keys, local endpoints, browser models, and inference defaults are managed from Player Hub.', 'Saved AI runtime status is summarized here. Provider, local endpoint, browser model, and inference defaults open in Settings.'],
  ['No separate settings-page handoff.', 'Dedicated Settings owns runtime controls.'],
  ['Profile and settings should not split across duplicate pages.', 'Dedicated Settings owns device and runtime controls.'],
  ['Profile, settings, balances, account status, rewards, and ownership.', 'Profile, balances, account status, rewards, and ownership.'],
  ['Notification preferences, theme, security state, API settings, local AI settings, and privacy controls belong here.', 'Account-level privacy and identity controls are summarized here. Device, provider, and runtime settings open in Settings.'],
  ['Cloud API keys, local server endpoints, browser models, inference settings, and per-device AI runtime choices are managed here.', 'Saved AI runtime state is summarized here. Provider, local server, browser model, and inference controls open in Settings.'],
  ['Configure cloud provider keys, local AI servers, browser models, and inference defaults from Player Hub.', 'Review saved AI setup from Player Hub. Edit provider keys, local servers, browser models, and inference defaults in Settings.'],
  ['Ollama, LM Studio, vLLM, LocalAI, KoboldCpp, native app, and browser-local model choices belong here.', 'Ollama, LM Studio, vLLM, LocalAI, KoboldCpp, native app, and browser-local model choices are surfaced here when saved.'],
  ['Profile, privacy, notifications, AI settings, API settings, and local runtime controls.', 'Profile-safe account controls, privacy summary, and settings handoff.'],
  ['Provider keys, local servers, browser models, and inference settings for the signed-in player.', 'Provider keys, local servers, browser models, and inference status for the signed-in player.'],
  ['Profile, settings, AI, balances, and account status', 'Profile, AI summary, balances, and account status'],
  ['Cloud, local, browser, and inference settings', 'Cloud, local, browser, and inference status'],
  ['Profile, settings, and AI controls', 'Profile, privacy, and settings handoff'],
  ['Profile, settings, and account data', 'Profile and account data'],
  ['Shop listings', 'Catalog items'],
  ['Loaded from Player Hub account settings.', 'Loaded from the account settings service when available.'],
  ['Notification preferences are managed in this hub.', 'Notification preference summary from account settings.'],
  ['Cloud API keys, local endpoints, browser models, and inference settings are managed in AI Setup.', 'AI runtime state is summarized here and edited in Settings.'],
  ['Shop remains the browsing and checkout surface.', 'Catalog browsing and checkout remain outside Player Hub.'],
  ['Private account hub for profile, settings, matches, learning, inventory, rewards, and competition ownership.', 'Private account hub for profile, matches, learning, inventory, rewards, and competition ownership.'],
  ['Profile, settings, privacy, AI, API, local AI, balances, and ownership are managed from Player Hub.', 'Player Hub manages profile-safe account data and summarizes settings that are edited on the Settings page.'],
  ['Player Hub is the account surface.', 'Player Hub is the account summary surface.'],
  ['Shop Handoff', 'Catalog Handoff'],
  ['Checkout stays in Shop', 'Purchases stay outside the hub'],
  ['Checkout stays in Shop.', 'Purchases stay outside Player Hub.'],
  ['Shop can sell tickets and passes.', 'Competition and catalog services own tickets and passes.'],
  ['/packages/app-assets/src/images/ShopPage/Profileframe.png', playerHubProfileImageUrl],
  ['/packages/app-assets/src/images/ShopPage/Avatars.png', playerHubProfileImageUrl],
  ['/packages/app-assets/src/images/ShopPage/TableThemes.png', playerHubSettingsImageUrl],
  ['/packages/app-assets/src/images/LobbyPlaceholders/AI_Showdown.png', playerHubAiImageUrl],
  ['/packages/app-assets/src/images/LobbyPlaceholders/AI_Coach.png', playerHubLearningImageUrl],
  ['/packages/app-assets/src/images/ShopPage/Treasury.png', playerHubBalancesImageUrl],
  ['/packages/app-assets/src/images/ShopPage/PrivateTable.png', playerHubMatchesImageUrl],
  ['/packages/app-assets/src/images/ShopPage/PublicTable.png', playerHubRoomHandoffImageUrl],
  ['/packages/app-assets/src/images/ShopPage/QualifierEntry.png', playerHubCompetitionImageUrl],
  ['/packages/app-assets/src/images/ShopPage/ChamPionPass.png', playerHubProgramsImageUrl],
  ['/packages/app-assets/src/images/ShopPage/Vault.png', playerHubInventoryImageUrl],
  ['/packages/app-assets/src/images/ShopPage/EarnFreeAC.png', playerHubRewardsImageUrl],
  ['/packages/app-assets/src/images/ShopPage/PlayersAccess.png', playerHubMatchesImageUrl],
]);

function normalizePlayerHubString(value: string): string {
  return STALE_PLAYER_HUB_COPY.get(value.trim()) ?? value;
}

function normalizePlayerHubStrings<T>(value: T): T {
  if (typeof value === 'string') {
    return normalizePlayerHubString(value) as T;
  }
  if (Array.isArray(value)) {
    return value.map(normalizePlayerHubStrings) as T;
  }
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as JsonRecord).map(([key, child]) => [key, normalizePlayerHubStrings(child)]),
    ) as T;
  }
  return value;
}

function assertKnownKeys(source: unknown, fallback: unknown, path: string) {
  if (!source || typeof source !== 'object' || Array.isArray(source) || !fallback || typeof fallback !== 'object' || Array.isArray(fallback)) {
    return;
  }
  const sourceRecord = source as JsonRecord;
  const fallbackRecord = fallback as JsonRecord;
  for (const key of Object.keys(sourceRecord)) {
    if (!(key in fallbackRecord)) {
      throw new Error(`Unknown Player Hub content field: ${path}.${key}`);
    }
    assertKnownKeys(sourceRecord[key], fallbackRecord[key], `${path}.${key}`);
  }
}

function mergeKnownValue<T>(fallback: T, source: unknown): T {
  if (Array.isArray(fallback)) {
    return Array.isArray(source) ? source as T : fallback;
  }
  if (fallback && typeof fallback === 'object') {
    const fallbackRecord = fallback as JsonRecord;
    const sourceRecord = asRecord(source);
    const merged: JsonRecord = { ...fallbackRecord };
    for (const [key, value] of Object.entries(fallbackRecord)) {
      merged[key] = mergeKnownValue(value, sourceRecord[key]);
    }
    return merged as T;
  }
  return typeof source === typeof fallback ? source as T : fallback;
}

function toShopTone(tone: PlayerHubTone): ShopTone {
  return tone as ShopTone;
}

function toShopIcon(icon: PlayerHubIcon): ShopIcon {
  return icon as ShopIcon;
}

function cardToShopItem(card: PlayerHubCard): ShopStaticItem {
  return {
    title: card.title,
    subtitle: card.subtitle,
    tone: toShopTone(card.tone),
    icon: toShopIcon(card.icon),
    badge: card.badge,
    imageUrl: card.imageUrl,
    price: card.cta,
    benefits: card.bullets ? [...card.bullets] : undefined,
    rightDetailTarget: rightDetailToShopTab[card.targetDetail],
  };
}

function sectionToShopSection(section: PlayerHubSection): ShopSection {
  return {
    title: section.title,
    subtitle: section.subtitle,
    footerTitle: section.footerTitle,
    footerItems: [...section.footerItems],
    categories: section.detailCards.map(cardToShopItem),
    featured: section.summaryCards.map(cardToShopItem),
  };
}

function navigationToShopSideItems(content: PlayerHubPageContentData): ShopSideItem[] {
  const seen = new Set<ShopPageTab>();
  return content.navigation.flatMap(item => {
    if (item.id === 'rewards' || item.id === 'account') return [];
    if (item.id === 'ai') {
      return [{
        id: item.id,
        key: 'Treasury',
        title: item.title,
        subtitle: item.subtitle,
        icon: toShopIcon(item.icon),
        tone: toShopTone(item.tone),
        imageUrl: item.imageUrl,
        rightDetailTarget: 'ai',
      }];
    }
    const key = sectionToShopTab[item.id];
    if (seen.has(key)) return [];
    seen.add(key);
    return [{
      key,
      title: item.title,
      subtitle: item.subtitle,
      icon: toShopIcon(item.icon),
      tone: toShopTone(item.tone),
      imageUrl: item.imageUrl,
    }];
  });
}

function previewTab(sectionId: PlayerHubSectionId): ShopPreviewRow['tab'] {
  if (sectionId === 'rewards') return 'Earn Free AC';
  if (sectionId === 'account' || sectionId === 'ai') return 'Treasury';
  return sectionToShopTab[sectionId];
}

function rightTabsToShopTabs(content: PlayerHubPageContentData): ShopRightTab[] {
  return content.rightTabs.map(tab => ({
    id: rightDetailToShopTab[tab.id],
    title: tab.title,
    accent: tab.accent,
  }));
}

function rewardActionToQuest(action: PlayerHubPageContentData['rewardActions'][number]): ShopQuest {
  return {
    key: action.key,
    group: action.group,
    title: action.title,
    reward: action.reward,
    cadence: action.cadence,
    tone: toShopTone(action.tone),
    icon: toShopIcon(action.icon),
    action: action.action,
    imageUrl: action.imageUrl,
    description: action.description,
    details: [...action.details],
  };
}

function inventoryGroupToVaultGroup(group: PlayerHubPageContentData['inventoryGroups'][number]): ShopVaultShowcaseGroup {
  return {
    key: group.key,
    title: group.title,
    subtitle: group.subtitle,
    tone: toShopTone(group.tone),
    icon: toShopIcon(group.icon),
    badge: group.badge,
    heroImageUrl: group.heroImageUrl,
    items: group.items.map(cardToShopItem),
  };
}

export function playerHubContentToShopContent(content: PlayerHubPageContentData): ShopPageContentData {
  const copy = content.uiCopy;
  return ShopPageContentDataSchema.parse({
    headerStats: content.headerMetrics.map(metric => ({
      label: metric.label,
      value: metric.fallbackValue,
    })),
    sideItems: navigationToShopSideItems(content),
    sections: {
      Treasury: sectionToShopSection(content.sections.overview),
      Elite: sectionToShopSection(content.sections.learning),
      Vault: sectionToShopSection(content.sections.inventory),
      'Play Access': sectionToShopSection(content.sections.matches),
      Events: sectionToShopSection(content.sections.competition),
    },
    vaultShowcaseGroups: content.inventoryGroups.map(inventoryGroupToVaultGroup),
    creditPacks: content.sections.overview.summaryCards.map(cardToShopItem),
    passes: content.sections.learning.summaryCards.map(cardToShopItem),
    previews: content.previews.map(row => ({
      title: row.title,
      tab: previewTab(row.sectionId),
      subtitle: row.subtitle,
      items: [...row.items],
      accent: row.accent,
      imageUrls: [...row.imageUrls],
    })),
    quests: content.rewardActions.map(rewardActionToQuest),
    rightTabs: rightTabsToShopTabs(content),
    rightRows: {
      wallet: content.rightRows.balances.map(row => [...row]),
      events: content.rightRows.competition.map(row => [...row]),
      recent: content.rightRows.recent.map(row => [...row]),
    },
    rightDetails: {
      account: content.rightDetails.account.map(row => ({ ...row })),
      settings: content.rightDetails.settings.map(row => ({ ...row })),
      wallet: content.rightDetails.balances.map(row => ({ ...row })),
      pass: content.rightDetails.learning.map(row => ({ ...row })),
      events: content.rightDetails.competition.map(row => ({ ...row })),
      recent: content.rightDetails.recent.map(row => ({ ...row })),
      ai: content.rightDetails.ai.map(row => ({ ...row })),
    },
    uiCopy: {
      header: {
        title: copy.header.title,
        subtitle: copy.header.subtitle,
        badges: copy.header.badges.map(badge => ({ ...badge, icon: toShopIcon(badge.icon), tone: toShopTone(badge.tone) })),
        balanceTitle: copy.header.balanceTitle,
        balanceUnit: copy.header.balanceUnit,
        balanceSub: copy.header.balanceSub,
      },
      passCard: {
        compactSummary: copy.detailView.learningSubtitle,
        summary: copy.detailView.learningSubtitle,
        compactBenefits: copy.detailView.learningRows.map(row => row.label),
        benefits: copy.detailView.learningRows.flatMap(row => row.values),
        lifetimeButton: copy.actions.view,
        selectButton: copy.actions.view,
      },
      earnPanel: {
        title: copy.rewards.title,
        description: copy.rewards.subtitle,
        buttonLabel: copy.actions.view,
      },
      earnRewards: {
        title: copy.rewards.title,
        subtitle: copy.rewards.subtitle,
        backLabel: copy.rewards.backLabel,
        closeLabel: copy.rewards.closeLabel,
        detailLabel: copy.rewards.detailLabel,
        shareTitlePrefix: copy.rewards.title,
        inviteTitle: copy.rewards.title,
        completeTitlePrefix: copy.rewards.title,
        shareHelper: copy.rewards.helper,
        inviteHelper: copy.rewards.helper,
        defaultHelper: copy.rewards.helper,
        shareFields: [...copy.rewards.fields],
        inviteFields: [...copy.rewards.fields],
        defaultFields: [...copy.rewards.fields],
        shareChips: [...copy.rewards.chips],
        inviteChips: [...copy.rewards.chips],
        defaultChips: [...copy.rewards.chips],
        shareMessage: copy.rewards.helper,
        inviteLink: PLAYER_HUB_EMPTY_VALUE,
        defaultChecklist: copy.rewards.helper,
        shareProof: PLAYER_HUB_EMPTY_VALUE,
        inviteStatus: copy.rewards.status,
        defaultStatus: copy.rewards.status,
        verificationStatus: copy.rewards.status,
        shareTargetStatus: copy.rewards.status,
        progressStatus: copy.rewards.status,
        rewardSuffix: '',
        openShare: copy.rewards.open,
        copyInvite: copy.rewards.copy,
        start: copy.rewards.start,
        checkVerify: copy.rewards.check,
        verifySpin: copy.rewards.check,
      },
      rightPanel: {
        walletTitle: copy.rightPanel.balancesTitle,
        passTitle: copy.rightPanel.learningTitle,
        eventsTitle: copy.rightPanel.competitionTitle,
        recentTitle: copy.rightPanel.recentTitle,
        accountTitle: copy.rightPanel.accountTitle,
        passName: copy.rightPanel.learningName,
        managePass: copy.rightPanel.manageLearning,
        viewProfile: copy.rightPanel.viewAccount,
        profileName: copy.rightPanel.profileName,
        profileElo: copy.rightPanel.profileLevel,
        emailUnavailable: copy.rightPanel.emailUnavailable,
        guestProfile: copy.rightPanel.guestProfile,
        initialsUnavailable: copy.rightPanel.initialsUnavailable,
        ratingUnavailable: copy.rightPanel.ratingUnavailable,
        gamesUnavailable: copy.rightPanel.gamesUnavailable,
        winRateUnavailable: copy.rightPanel.winRateUnavailable,
        eloPrefix: copy.rightPanel.levelPrefix,
        gamesSuffix: copy.rightPanel.gamesSuffix,
        winRateSuffix: copy.rightPanel.winRateSuffix,
        moreLabel: copy.rightPanel.moreLabel,
        openEliteShop: copy.rightPanel.openLearning,
      },
      actions: {
        comingSoon: copy.actions.comingSoon,
        purchase: copy.actions.open,
        topUp: copy.actions.open,
        select: copy.actions.open,
        view: copy.actions.view,
        open: copy.actions.open,
        claimFree: copy.actions.claim,
        freeBadge: copy.actions.claim,
        buyDigital: copy.actions.open,
        openVaultGroup: copy.actions.openGroup,
        working: copy.actions.working,
        details: copy.actions.details,
        backToShop: copy.actions.backToHub,
        backToPrefix: copy.actions.backToPrefix,
        vaultEntryCountSuffix: 'items',
        selectVaultGroup: copy.actions.openGroup,
      },
      payment: {
        titlePrefix: 'Player Hub action',
        defaultDescription: 'This action is not checkout from Player Hub.',
        idleMessage: 'Select an available player action.',
        providerOptions: [
          { provider: 'stripe', label: 'Stripe', detail: 'Unavailable from Player Hub.' },
          { provider: 'paypal', label: 'PayPal', detail: 'Unavailable from Player Hub.' },
          { provider: 'razorpay', label: 'Razorpay', detail: 'Unavailable from Player Hub.' },
          { provider: 'solana', label: 'Solana', detail: 'Unavailable from Player Hub.' },
        ],
        starting: 'Starting',
        working: copy.actions.working,
        select: copy.actions.open,
        cancel: 'Cancel',
        signInRequired: 'Sign in required.',
        successAccepted: 'Accepted.',
        providerNotConfigured: 'Provider unavailable.',
        checkoutFailed: 'Action failed.',
      },
      deckPreview: {
        title: copy.itemPreview.title,
        backToVault: copy.itemPreview.backToInventory,
        digitalDeck: copy.itemPreview.itemType,
        purchaseOptionsSuffix: copy.itemPreview.itemOptionsSuffix,
        printableDigital: copy.itemPreview.itemType,
        includedStarterDeck: copy.itemPreview.itemType,
        tableReadyDigitalDeck: copy.itemPreview.itemType,
        printableExportIncluded: copy.itemPreview.itemType,
        cardArtworkIncluded: copy.itemPreview.itemType,
        noDeckData: copy.itemPreview.noItemData,
        cardBackAlt: 'Item back',
        cardBackLabel: 'Back',
        missingImage: copy.itemPreview.missingImage,
        priceUnavailable: copy.itemPreview.priceUnavailable,
        previousCardImage: copy.itemPreview.previousImage,
        nextCardImage: copy.itemPreview.nextImage,
        closeCardDetail: copy.itemPreview.closeDetail,
        expand: copy.itemPreview.expand,
      },
      status: {
        loadingMarketplace: copy.status.loadingHub,
        clearError: copy.status.retry,
        unknownValue: copy.status.unknownValue,
      },
      footer: copy.footer.map(item => ({ ...item, icon: toShopIcon(item.icon), tone: toShopTone(item.tone) })),
    },
    infoDetails: {
      arenaCredits: {
        title: copy.detailView.accountTitle,
        subtitle: copy.detailView.accountSubtitle,
        cta: copy.detailView.accountCta,
        bullets: [...copy.detailView.accountBullets],
      },
      eliteBenefits: {
        title: copy.detailView.learningTitle,
        subtitle: copy.detailView.learningSubtitle,
        cta: copy.detailView.learningCta,
        tiers: copy.detailView.learningTiers.map(tier => ({
          key: tier.key,
          title: tier.title,
          price: tier.value,
          tone: toShopTone(tier.tone),
        })),
        rows: copy.detailView.learningRows.map(row => ({
          label: row.label,
          values: [...row.values],
        })),
      },
    },
  });
}

export function normalizePlayerHubPageContent(
  content?: PartialPlayerHubPageContentData | null,
): PlayerHubPageContentData {
  const fallback = cloneDefaultContent();
  if (content) {
    assertKnownKeys(content, fallback, 'playerHubContent');
    PartialPlayerHubPageContentDataSchema.parse(content);
  }
  const merged = mergeKnownValue(fallback, content);
  return PlayerHubPageContentDataSchema.parse(normalizePlayerHubStrings(merged));
}

export function parsePlayerHubPageContent(content: unknown): PlayerHubPageContentData {
  return PlayerHubPageContentDataSchema.parse(content);
}
